### ISSUE TITLE
Add attribute in termgroups

### ISSUE THREAD

**Issue by KbWorks** [SharePoint/PnP-Provisioning-Schema#115]
When you use a termgroup on site collection level you are not able to overwrite terms and get a exception they already exist.

it would be nice to have a option to overwrite or skip the termgroup provisioning if it already exists.

thanks.

Paul

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I've just defined in the next schema version an attribute UpdateBehavior for any TermGroup. Then, we will have to handle this attribute at the engine level. I will close this item.

**Comment by stact** [comment]
Hi @PaoloPia 
Is this option still working? Tried to update taxonomy and nothing (change term name, or label in translations)

Schema used:
```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema">
```

Termgroup sample:
```xml
<pnp:TermGroup Name="Custom group" ID="51114154-dcd2-479e-a8bb-8e94d90736f4" Description="" UpdateBehavior="Overwrite">
```

Term sample:
```xml
<pnp:Term Name="Engineering" ID="629efd31-f7d6-4d85-9800-c74476157ae8" Description="" CustomSortOrder="5" SourceTermId="629efd31-f7d6-4d85-9800-c74476157ae8">
   <pnp:Terms />
   <pnp:Labels>
      <pnp:Label Language="1031" Value="Ingenieurwesen" IsDefaultForLanguage="true" />
      <pnp:Label Language="1036" Value="Services techniques" IsDefaultForLanguage="true" />
   </pnp:Labels>
</pnp:Term>
```
