### ISSUE TITLE
Add "Hidden" attribute to ContentTypeBinding element

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#118]
In the UI it is possible to mark a CT as 'hidden' by removing it from the New button. This would require us to introduce a 'Hidden' attribute on the ContentTypeBinding element for a list instance. We then as a result make sure that the CT is not present in the UniqueContentTypeOrder property of the rootfolder of the list if that attribute is set to True.

See: https://github.com/OfficeDev/PnP-PowerShell/issues/357

**Comment by ruslanurban** [comment]
Please, add this in the next release of the Schema and Core.

I have a scenario when I need to create a cross-document set view displaying column values from the allowed content types. It works if I add (hidden) document types to the list of _ContentTypeBindings_, but does not work if I add a hidden field reference - PnP engine fails with the following error:

```error
Apply-PnPProvisioningTemplate : Column 'CUST_DocumentStatus' does not exist. 
It may have been deleted by another user.
```

Thus, I would need to hide the content types manually on all lists that exhibit such behavior.

**Comment by PaoloPia** [comment]
Thanks. I added a Hidden attribute to the ContentTypeBinding element. It will be available in the next schema. Of course, we will have to handle it at the engine level.

**Comment by JeanNetryValere** [comment]
Hi Paolo,
Could you tell us when a version including this will be released please ?

**Comment by ruslanurban** [comment]
I implemented the workaround in PowerShell:

```powershell
 ## Workaround: Content types in the New Document menu
        $listsWithContentTypeBindingEnhancements = $xeProvisioningTemplate.SelectNodes("//pnp:ListInstance[pnp:ContentTypeBindings/pnp:ContentTypeBinding/@ext:*]", $NSManager);        
        foreach($listInstance in $listsWithContentTypeBindingEnhancements){
            $spList = $ClientContext.Web.Lists | ? {$_.Title -eq $listInstance.Title} | select -First 1;

            if($spList){

                $ClientContext.Load($spList.ContentTypes);
                $ClientContext.Load($spList.RootFolder);
                $ClientContext.ExecuteQuery();

                $contentTypeBindings = $listInstance.ContentTypeBindings.ContentTypeBinding | sort Order | sort Default -Descending;
                $contentTypes = $spList.ContentTypes | sort Id -Descending;

                # Making generic ordered list of content type ids
                $ctList = New-Object System.Collections.Generic.List[Microsoft.SharePoint.Client.ContentTypeId];
                foreach ($contentTypeBinding in $contentTypeBindings)
                {
                    if(($contentTypeBinding.Hidden -like "true") -or ($contentTypeBinding.Remove -like "true")){ continue; }
                    $contentType = $contentTypes | ? {$_.Id.StringValue -like "$($contentTypeBinding.ContentTypeID)*"} | select -First 1;
                    if($contentType){
                        $ctList.Add($contentType.Id);
                    }
                }

                # Updating content type order
                $spList.RootFolder.UniqueContentTypeOrder = $ctList;
                $spList.RootFolder.Update();
                $spList.Update();
                $ClientContext.ExecuteQuery();

                Write-Output $spList;                

            } else {
                Write-Warning "Unable to update content type order on list $($listInstance.Title): List not found."
            }
        }
```
Notes: 
* The script is applied in post-processing. 
* The `ext' namespace nodes are removed from the template in pre-processing to ensure schema compliance.

Sample list definition:
```xml
<pnp:ListInstance Url="Example" Title="Example List" Description="This list showcases use of New Document menu extensions" TemplateType="101" ContentTypesEnabled="true">
	<pnp:ContentTypeBindings>
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Sample Document Set}" ext:Order="1" Default="true" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Demo Document Set}" ext:Order="3" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Test Document Set}" ext:Order="2" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Sample Document}" ext:Hidden="true" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Demo Document}" ext:Hidden="true" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Test Document}" ext:Hidden="true" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Link to a Document}" ext:Hidden="true" />
		<pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Document}" ext:Hidden="true" />
	</pnp:ContentTypeBindings>
</pnp:ListInstance>
```

**Comment by JeanNetryValere** [comment]
@ruslanurban Thank you to share your production. I have already created also a powershell script using UniqueContentTypeOrder to do the Job. 
Your template enhancement is a classy way to implement this, i will consider this approach as a model for my next tasks.
Thank again for the share.

**Comment by knightparsifal** [comment]
Has this been implemented in the current version?

**Comment by JeanNetryValere** [comment]
Not tested in February, but in december 2017 it was not.

You should go to Custom Handlers solution.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-16 11:38 GMT+01:00 knightparsifal <notifications@github.com>:

**Comment by knightparsifal** [comment]
Can you point me in the correct direction?
I do not get how to run the code above.

**Comment by ruslanurban** [comment]
First, you need to load an XML template and create a namespace manager to be able to [select XML nodes](https://msdn.microsoft.com/en-us/library/4bektfx9(v=vs.110).aspx).
Then, establish a connection with the target site and get [client context](https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/Get-PnPContext.md). The rest should be obvious.

**Comment by JeanNetryValere** [comment]
@knightparsifal Another approach (if you don't want to modify the generated templated) would be to code an assembly using a custom extensibility handler (in c#) and then apply it (pointing your dll) using [PowerShell](https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/Apply-PnPProvisioningTemplate.md#------------------example-7------------------) or C#.

**Comment by ruslanurban** [comment]
@knightparsifal The attributes are now in the [new 1801 schema](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2018-01.md#contenttypebinding), but handling of the Hidden and Remove attributes [has not been implemented yet](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs). 
I just hope it has not been forgotten because this issue is now closed...
