### ISSUE TITLE
Provisioning Fails When List Has "Allow items in this list to be rated?" Set To Yes

### ISSUE THREAD

**Issue by shanechristy** [SharePoint/PnP-Provisioning-Schema#119]
When the template XML has a list that had "Allow items in this list to be rated?" set to Yes, and you try to apply the template to a site, I get an exception when code create the views stating that "The column 'Ratedby' does not exist".

I think this happens because RatedBy is only added as a column when "Allow items in this list to be rated?" is enabled, and I'm not seeing any option to add that to the XML so the code fails due to field missing.

If possible, I think the provisioning schema should be able to provision a list with that option enabled without it throwing an exception.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I referenced this Issue in the right repository and i will close this one.
