### ISSUE TITLE
Provision Display template and other files at root web

### ISSUE THREAD

**Issue by krunal039** [SharePoint/PnP-Provisioning-Schema#120]
We are trying to provision subsite but there are some artfects which needs to be provisioned at root web like display templates and page layouts, is there way we can provision everything from same template but some at root web and other at subsute

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Provisioning Engine. Any Provisioning Template targets just one web site at a time. Thus, if you want to have a template applied to the root site, and another one to a sub-site, you will have to create two templates and apply them in the right sequence, for example using a bunch of PowerShell scripting.

**Comment by krunal039** [comment]
Hi,
Thanks, just thought so and managed to do same. thanks for update.
