### ISSUE TITLE
Add a NoCrawl attribute to a ListInstance element

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#123]

**Comment by ruslanurban** [comment]
Need this!

**Comment by dfeuerhake** [comment]
We need this, too!

**Comment by PaoloPia** [comment]
Done! Will show up in the next schema version.

**Comment by serverless-me** [comment]
It is not supported onpremises by PnP provisioning, but it can be achieved by a script writing it to the AllProperties attribute of the RootWeb.
