### ISSUE TITLE
Site Fields With Special Symbols Fails to Create

### ISSUE THREAD

**Issue by shanechristy** [SharePoint/PnP-Provisioning-Schema#124]
I am trying to provision fields that have special symbols in their display name, and I receive an exception stating that "The field was found invalid" when applying the template to site. I've managed to reproduce this issue with a question mark symbol and parenthesis. Removing the symbol from display name fixes the issue.

The exception is being thrown by the Void CreateField method in SharePoint.Client.Web.

Here is an example of a displayname in the schema throwing an exception

`DisplayName=\"{res:Virtual?_DisplayName}`

while this imports just fine

`DisplayName=\"{res:Virtual_DisplayName}`

I think, if possible,  I should be able to apply a template without having to manually replace the offending symbol in the schema.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Provisioning Engine. Can you share much more details about the exception (error message and stack trace) that you get? Of course you cannot use any not supported character in the field name, but we want to be sure that it is not an issue related to our custom implementation of the provisioning engine. Thanks.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1026

**Comment by VesaJuvonen** [comment]
Since this is around the PnP Provisioning Engine usage and not directly on the schema as such, will relocate this to PnP-Sites-Core repository.
