### ISSUE TITLE
Add Description attribute to FieldRef element in ListInstance

### ISSUE THREAD

**Issue by Jadei** [SharePoint/PnP-Provisioning-Schema#125]
Today, it's not possible to change description of field like "Title" in ListInstance. Can you add attribute Description to FieldRef element in ListInstance.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Actually, from a schema perspective, at the Field element level, we support any XML content, so we can add support for a custom Description at the engine level. From a FieldRef perspective, we already have the DisplayName property, so if it doens't work, again we have to fix it a the engine level.
Thus, I will close this item and open a new one at the engine level, referencing this item.
Thanks.
