### ISSUE TITLE
Error occured: Cannot Import this Web part.

### ISSUE THREAD

**Issue by BigBrahma** [SharePoint/PnP-Provisioning-Schema#127]
I have used the xml in below link to add webpart to a page. But it is throwing "Error occured: Cannot Import this Web part." . Can u please help?

[https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/Samples/WebPartPage.xml](url)

![import error](https://cloud.githubusercontent.com/assets/18693266/18950535/fa18d99c-865d-11e6-8a22-70567c35ebcd.PNG)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Provisioning Engine. Can you share a little bit more about the exception. I've just tried to apply that template and it works perfectly. Thanks. In the meantime I will close this issue, and I will re-open it in case of any further feedback.
