### ISSUE TITLE
Get-SPOProvisioningTemplate for SharePoint 2013 -PersistMultiLanguageResources not available

### ISSUE THREAD

**Issue by coupalm** [SharePoint/PnP-Provisioning-Schema#128]
Hi,
In the Get-SPOProvisioningTemplate PowerShell command for SharePoint 2013, the -PersistMultiLanguageResources is not available. 

Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Provisioning Engine. It is because that capability is not supported in SP2013. You need to have at least SP2016 or SPO to being able to manage resources.

**Comment by cheindel** [comment]
@PaoloPia Does this only affect export? Or can you also not import with multi lang resources on SP2013?
