### ISSUE TITLE
Column settings of list content types

### ISSUE THREAD

**Issue by r998877** [SharePoint/PnP-Provisioning-Schema#130]
If a column in a list content type is set to Hidden, this setting is not taken into account when a template is created from the site.
If the template is applied to a different site, the column is still shown as Required or Optional, not as Hidden.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Provisioning Engine. I moved this issue in the PnP-Sites-Core repository, which is the right one for such kind of requests. I will close this item.
