### ISSUE TITLE
Add Items (DaraRow) properties behind pnp:Folder 

### ISSUE THREAD

**Issue by jquintozamora** [SharePoint/PnP-Provisioning-Schema#132]
IN the specific scenario we'd like to add some items under specific folders we aren't able to do currently. It could be a good improvement to put pnp:DataRows as a posible child of pnp:Folder.

Regards!

**Comment by johnnliu** [comment]
We also think pnp:FieldDefaults on subfolders would be nice.  Right now, Default Column Values are only available at the root level.

**Comment by PaoloPia** [comment]
Hi José,
Thanks for your suggestion. Unfortunately, after evaluating your submission we considered that the investment to implement this is too high compared to the actual value of the feature. We might re-consider this for future schema versions, but we cannot implement it right now. In the meantime, you can implement it using a custom engine extension. Thanks.
