### ISSUE TITLE
Description field referenced in View leads to error

### ISSUE THREAD

**Issue by Alymcgeel** [SharePoint/PnP-Provisioning-Schema#137]
In the source site collection a standard task list was added. In the template the View for Calendar contains a field "Description". In the list, the field has the internal name "Body". Therefor it is not possible to use the template as the engine quits when applying the list views.

SharePoint 2016 on premises.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Could you please share the failing XML template within the new issue that I created in the right repository (https://github.com/SharePoint/PnP-Sites-Core/issues/873). In the meantime I will close this item.
