### ISSUE TITLE
Honor MobileView Attribute

### ISSUE THREAD

**Issue by NormanMann** [SharePoint/PnP-Provisioning-Schema#138]
When creating or updating a view using the provisioning engine the MobileView attribute seems to be ignored.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I move this issuein the proper repository (). I will close this one in the meantime.

**Comment by erwinvanhunen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#922

**Comment by VesaJuvonen** [comment]
Since issues has been relocated and fixed in the core component, will fix this one from here.
