### ISSUE TITLE
Remove FieldRef from Site Content Type

### ISSUE THREAD

**Issue by NormanMann** [SharePoint/PnP-Provisioning-Schema#139]
We would like to remove certain FieldRefs that are inherited by the parent content type.
For example inheriting from the default Issue site content type will give you all the fields of the parent content type 
Right now there seems to be no way of removing some of the fields (e.g. Related issues) during the provisioning process

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. So far, the capability that you request is not supported by the engine. I will put this issue in the "Next version Ideas" group, and in the next schema version we will think about it. Thanks.

**Comment by NormanMann** [comment]
Schema 201705 now seems to have a 'Remove' Attribute for FieldRef. Is is supported by the provisioning engine ?
