### ISSUE TITLE
How to enforce uniqueness on a Title field

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/PnP-Provisioning-Schema#141]
Since the Title field is excluded from the generated schema, how can we make it to enforce uniqueness and update other attribute such as DisplayName?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. Could you please expand a little bit more about this requirement? Thanks.

**Comment by VesaJuvonen** [comment]
Closed due no response on the requested information.
