### ISSUE TITLE
Adding .DWP as part of page when provisioning template

### ISSUE THREAD

**Issue by athrayee** [SharePoint/PnP-Provisioning-Schema#143]
I am trying to use pnp provisioning top deploy webpart pages and I have content editor webpart exported. the content editor gets exported as .DWP and it correxponds to xmlns v2. when embedding this in the pnp pages I get error as follows

Apply-PnPProvisioningTemplate : Cannot recognize the XML namespace of this Web Part.
At F:\CDocs\source\NYSite\powershellonline.ps1:15 char:5
+     Apply-PnPProvisioningTemplate -Path $templateFile
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

 my template is

      <pnp:Pages>
        <pnp:Page Url="~site/sitepages/home.aspx" Overwrite="true" Layout="TwoColumns">
          <pnp:WebParts>
            <pnp:WebPart Title="Rollup News" Row="1" Column="1">
              <pnp:Contents>
                <webParts>
                  <WebPart xmlns="http://schemas.microsoft.com/WebPart/v2">
                    <data>
                      <Title>News Rollup</Title>
                      <FrameType>None</FrameType>
                      <Description>Displays Rolled up News from initiatives to present at EPPL.</Description>
                      <IsIncluded>true</IsIncluded>
                      <ZoneID>wpz</ZoneID>
                      <PartOrder>4</PartOrder>
                      <FrameState>Normal</FrameState>
                      <Height />
                      <Width />
                      <AllowRemove>true</AllowRemove>
                      <AllowZoneChange>true</AllowZoneChange>
                      <AllowMinimize>true</AllowMinimize>
                      <AllowConnect>true</AllowConnect>
                      <AllowEdit>true</AllowEdit>
                      <AllowHide>true</AllowHide>
                      <IsVisible>true</IsVisible>
                      <DetailLink />
                      <HelpLink />
                      <HelpMode>Modeless</HelpMode>
                      <Dir>Default</Dir>
                      <PartImageSmall />
                      <MissingAssembly>Cannot import this Web Part.</MissingAssembly>
                      <PartImageLarge>/_layouts/15/images/mscontl.gif</PartImageLarge>
                      <IsIncludedFilter />
                      <Assembly>Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Assembly>
                      <TypeName>Microsoft.SharePoint.WebPartPages.ContentEditorWebPart</TypeName>
                      <ContentLink xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor">/teams/ONEMDIT-DEV/Style Library/Employee Productivity/dist/html/rollupnews.html</ContentLink>
                      <Content xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor" />
                      <PartStorage xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor" />
                    </data>
                  </WebPart>
                </webParts>
              </pnp:Contents>
            </pnp:WebPart>
            <pnp:WebPart Title="Rollup News" Row="2" Column="1">
              <pnp:Contents>
                <webParts>
                  <WebPart xmlns="http://schemas.microsoft.com/WebPart/v2">
                    <Title>Yammer Feed</Title>
                    <FrameType>Default</FrameType>
                    <Description>The web part to display yammer feed based on the information from a List</Description>
                    <IsIncluded>true</IsIncluded>
                    <ZoneID>wpz</ZoneID>
                    <PartOrder>0</PartOrder>
                    <FrameState>Normal</FrameState>
                    <Height />
                    <Width />
                    <AllowRemove>true</AllowRemove>
                    <AllowZoneChange>true</AllowZoneChange>
                    <AllowMinimize>true</AllowMinimize>
                    <AllowConnect>true</AllowConnect>
                    <AllowEdit>true</AllowEdit>
                    <AllowHide>true</AllowHide>
                    <IsVisible>true</IsVisible>
                    <DetailLink />
                    <HelpLink />
                    <HelpMode>Modeless</HelpMode>
                    <Dir>Default</Dir>
                    <PartImageSmall />
                    <MissingAssembly>Cannot import this Web Part.</MissingAssembly>
                    <PartImageLarge>/_layouts/15/images/mscontl.gif</PartImageLarge>
                    <IsIncludedFilter />
                    <Assembly>Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Assembly>
                    <TypeName>Microsoft.SharePoint.WebPartPages.ContentEditorWebPart</TypeName>
                    <ContentLink xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor">/teams/ONEMDIT-DEV/Style Library/Employee Productivity/dist/html/YammerFeed.html</ContentLink>
                    <Content xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor" />
                    <PartStorage xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor" />
                  </WebPart>
                </webParts>
              </pnp:Contents>
            </pnp:WebPart>
          </pnp:WebParts>
        </pnp:Page>
      </pnp:Pages>

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I created an issue in the PnP-Sites-Core repo, which is the one in target for this kind of issue, and I assigned it to me. I will close this one, which targets the wrong repo. Thanks again.
