### ISSUE TITLE
Get-SPOProvisioningTemplate The file is not checked out. You must first check out this document before making changes"

### ISSUE THREAD

**Issue by petercarson** [SharePoint/PnP-Provisioning-Schema#145]
I'm getting the error "Get-SPOProvisioningTemplate The file is not checked out. You must first check out this document before making changes".  I have write access, I've tried with an existing file there and not, and running PowerShell as administrator.  This is a SharePoint Online environment.
https://github.com/SharePoint/PnP/issues/921 sounds similar.  Any advice on solving this?

**Comment by petercarson** [comment]
So it seems to be an issue when creating a template from a Groups site.  Our https://envisionit.sharepoint.com tenant is First Release, and my plan was to create a template from a customized site from the Group site.  I tried again with a vanilla team site provisioned normally through SharePoint, and it created the template fine.  I then tried a brand new vanilla Groups site, and I got the same error.  Is this an incompatibility with the GROUPS#0 site template?

I ran it with Set-SPOTraceLog -On -Level Debug turned on to get a verbose log.  I've attached the results.  I also attached the log for the clean run.  You'll see right at the beginning there is an "Error occured while retrieving basetemplate" in the problem case.

[Debug Error.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/639988/Debug.Error.txt)
[Debug Success.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/639987/Debug.Success.txt)

**Comment by petercarson** [comment]
Chatting outside of this thread, and it sounds like I'm a little early for PnP Remote Provisioning with Groups sites.  Support is planned for the December release that is imminently coming.  I'll update with the results from that when it comes out.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1028

**Comment by VesaJuvonen** [comment]
Hi petercarson, any news on the new testing around the capability. PnP Provisioning Engine does have support for modern team sites, but due the noscript settings in these sites, there are quite a few API limitations what can be done. Since this also is more around the provisioning engine topic, rather than schema definitions, will relocate this issue to PnP-Sites-Core repository and close this one.
