### ISSUE TITLE
Add fields and content types defined at subsite level

### ISSUE THREAD

**Issue by nicolabarbon** [SharePoint/PnP-Provisioning-Schema#146]
I would like to export fields and content types defined specifically at subsite level. 
If I understand how provisioning-template works, right now, the exported template contains fields and content types only for the root web of the site collection.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This an issue related to the engine and not to the schema. Thus I created a new issue in the PnP-Sites-Core repo and I will close this one.
