### ISSUE TITLE
Request - Have audience attribute for navigation nodes in schema

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Provisioning-Schema#149]
Would be used in publishing sites - for both audience and group level filtering.

**Comment by VesaJuvonen** [comment]
awesome. Let's do this.

**Comment by PaoloPia** [comment]
After discussion with you as a team we decided to skip this one because of lack of capability on CSOM.

**Comment by thespooler** [comment]
Since audience targetting for modern navigation is [coming soon (Q1 2020)](https://www.microsoft.com/en-US/microsoft-365/roadmap?filters=&searchterms=34251), does it change the status of this issue?
