### ISSUE TITLE
"Show or hide the tree view for site navigation" missing

### ISSUE THREAD

**Issue by cheindel** [SharePoint/PnP-Provisioning-Schema#151]
It looks like the schema does not support setting the property "Enable Tree View" via XML or PowerShell command.

Could you please consider adding it, so that this step could be automated for provisioning: https://support.office.com/en-us/article/Show-or-hide-the-tree-view-for-site-navigation-21ccd201-e02e-4bdb-aef6-877d66648eb2?ui=en-US&rs=en-US&ad=US&fromAR=1

**Comment by VesaJuvonen** [comment]
thx Christian, there's limited support for that setting in general in the remote APIs of SharePoint, but we'll absolutely have a look on this when we build the new schema version. Thx for providing your input.

**Comment by PaoloPia** [comment]
I've added an attribute EnableTreeView at the Navigation element level. It will show up in the experimental branch.
