### ISSUE TITLE
Field in ListInstance is not support multi-language

### ISSUE THREAD

**Issue by iiunknown** [SharePoint/PnP-Provisioning-Schema#152]
Hi,

I defined Field in ListInstance,  and want to use multi-language resource, I got an error:

```
Apply-SPOProvisioningTemplate : The field was found invalid:  {{listid:****}
```

The template xml file is in the blow:

```xml
...
 <pnp:ListInstance ...>
          ...
          <pnp:Fields>
            <Field ID="{bada6643-e44b-4c88-8eb7-923a119b6ed2}" Name="Memo" Type="Note" DisplayName="{resource: Note}" ... />
          </pnp:Fields>
 </pnp:ListInstance>
...
```

Multi-language lable is ok for SiteField, so, I think it's a bug, please help me, thanks.

**Comment by iiunknown** [comment]
Is it a  bug or something? anybody help me?

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1029

**Comment by VesaJuvonen** [comment]
Relocating this to PnP-Sites-Core, since issue this is clearly something on how the engine is provisioning the field values. Closing this one and we can continue discussion on the Sites-Core repository.
