### ISSUE TITLE
provision page layout + associated content type, publishing page instance

### ISSUE THREAD

**Issue by dorin2006** [SharePoint/PnP-Provisioning-Schema#158]
People please help!!! Great tool, but... 

1. how to provision publishing page instance in pages library ?

Or this is not supported yet ?

thanks in advance!!!

p.s. I've managed to provision custom publishing page layout and associated content type ( not a publishing page instance yet ) as follows:
 <pnp:File Src="PageLayouts\GenericPageLayout.aspx" Folder="_catalogs/MasterPage" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentType" Value="Page Layout" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#Page;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39;#" />
          </pnp:Properties>
        </pnp:File>

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1033

**Comment by VesaJuvonen** [comment]
since this is more around the PnP-Sites-Core engine, will relocate this to PnP-sites-Core repository for further processing.
