### ISSUE TITLE
JSLink in XSLTListViewWebpart : ~sitecollection is interprated

### ISSUE THREAD

**Issue by Amysno** [SharePoint/PnP-Provisioning-Schema#160]
hello there !
When provisioning a simple page with layout OneColumn, i'm adding a XsltListViewWebPart.
In that webpart, i specify the URL of a JSLink, located in the Style Library on the Root Web.
Here is that property : (inside <properties></properties>)

>       <property name="JSLink" type="string">~SiteCollection/Style Library/js/contacts_JSLink.js</property>

As you certainly know, when it comes to JSLink URL in Webparts, it has to be written using "~siteCollection" in WP, it appears like this : 

> ~siteCollection/Style Library/

But strangely, here, the ~ is interpreted and becomes /teams/Myteam/Style Library... which does not work.

I tried using these, and i write the results for you : 

- with `~siteCollection` result :  /teams/LY/Style Library => SP does interprete this one.

- with `&#152;siteCollection` result : siteCollection/Style Library  => No ~ , SP does not understand that url.

- with `&#126;siteCollection` result : /teams/LY/Style Library/   => SP does interprete, and replaces by the real names, but this is not what we want.

Could you please help me ?

thanks a lot.
have a nice day

**Comment by erwinvanhunen** [comment]
Hi,

Thank for you reporting this issue. Are you using the PnP Provisioning engine to provision that page?

**Comment by erwinvanhunen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#938

**Comment by Amysno** [comment]
Sorry for the delay, yes i am using the pnp provisioning engine.
Thanks for your actions @erwinvanhunen  ! :)
