### ISSUE TITLE
No "RootWebOnly" attribute on the <pnp:File> element

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#161]
_From @vman on January 12, 2017 15:7_

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When provisioning a File with the <pnp:File> attribute, we should be able to specifiy "RootWebOnly=true" to specific that this file should be provisioned only if the site being provisioned is RootWeb of a site collection.

This would be helpful if you are using the same template to provision site collections (rootweb) as well as subsites. Files like display templates, spcolor files etc are only supposed to be provisioned at the root level. 

#### Observed Behavior
There is no "RootWebOnly" attribute on the <pnp:File> element.

Thank you.

_Copied from original issue: SharePoint/PnP-Sites-Core#966_

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We discussed your request and we decided to skip it because you can simply apply different templates to different targets, and the efforts needed to provide support for this capability are not jutified by the return of investment. I hope you will understand. Thanks.
