### ISSUE TITLE
Creation of subsite using <pnp:Site not working

### ISSUE THREAD

**Issue by harinvp** [SharePoint/PnP-Provisioning-Schema#164]
Not able to create any subsite using <pnp:Site> , Please see the xml below. It does not throw any error,however no susbite is getting created. Is anyone familiar with this issue?
Applying the below template using ApplyProvisioningTemplate(".xml")

`<?xml version="1.0"?>
<pnp:Provisioning  xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Version="1.0">  
  </pnp:Preferences>
  <pnp:Templates>
    <pnp:ProvisioningTemplate ID="subSites" Version="1.0" xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema"  DisplayName="GroupCompass_SiteProvisioningSchema" Description="Provisioning schema for Group Compass Site"   >
       <pnp:Lists>
        <pnp:ListInstance Title="Pages" Description="This system library was created by the Publishing feature to store pages that are created in this site." TemplateType="850" Url="Pages" RemoveExistingContentTypes="true" ContentTypesEnabled="true" EnableAttachments="false">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF3900242457EFB8B24247815D688C526CD22D" Default="true" />
          </pnp:ContentTypeBindings>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>

  </pnp:Templates>
  <pnp:Sequence  ID="SAMPLE-SEQUENCE" SequenceType="Synchronous">
   
      <pnp:Site Language="1033"
             SiteTemplate="BLANKINTERNET#2"
             QuickLaunchEnabled="true"
             TimeZone="1"
             Title="Intranet Workflows"
             Url="Workflows"
             UseSamePermissionsAsParentSite="true">
        <pnp:Templates>
          <pnp:ProvisioningTemplateReference ID="subSites" />
        </pnp:Templates>
      </pnp:Site>
      
   
  </pnp:Sequence>
</pnp:Provisioning>`

Best Regards,
Hari

**Comment by VesaJuvonen** [comment]
Hi harinvp, 
this is actually by design, since the PnP Provisioning Engine available from the PnP Sites Core component has not yet implemented full set of the schema. Schema design is independent from the actual engine support implementation, since also other provisioning engines could use the same scheme. Right now PnP Engine has been concentrating only on the site level customization and modifications related on the template. We do not currently have timeline for the site collection and sub site creation support, since this also depends on the community contributions on this topic.

**Comment by harinvp** [comment]
Ok. Thank you.

**Comment by iratherscribble** [comment]
@VesaJuvonen It would be helpful to create an additional schema that is supported by the PnP Provisioning Engine. It causes people a lot of confusion when documentation states "Current implemented version (in the PnP Provisioning Engine)" and links to ProvisioningSchema-2016-05.xsd which has listed SiteCollection and Site underneath Sequence.

There is a schema for a spec, but there should also be a schema for the input to the Provisioning Engine itself as developers and administrators need to know what is valid for the Engine.
