### ISSUE TITLE
Add support for removing RoleAssignment and not only for adding them

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Provisioning-Schema#166]
See here: https://github.com/SharePoint/PnP-Sites-Core/issues/667

**Comment by PaoloPia** [comment]
Just added the Remove attribute to the RoleAssignment element.

**Comment by TanmayDharmaraj** [comment]
Is there documentation around this? 
I found this way [here](https://github.com/SharePoint/PnP-Sites-Core/issues/918) using extensiblity handler but would like to avoid this if it is supported internally.
