### ISSUE TITLE
Listview ViewStyle ID not applied

### ISSUE THREAD

**Issue by TomGoorts** [SharePoint/PnP-Provisioning-Schema#168]
When creating a new list with views, the ViewStyle won't be applied.

This is the XML used in the PnP Provision template:

`<View Name="{F75FC6A6-D4AB-4A87-8AEA-0ED5ADF5EDA2}" MobileView="TRUE" Type="HTML" DisplayName="Welkomstpagina" Url="/sites/{parameter:SiteCollectionUrl}/parameter:SiteUrl}/Lists/SiteMetaData/Welkomstpagina.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=44">
	<Query>
		<OrderBy>
			<FieldRef Name="ID" />
		</OrderBy>
	</Query>
	<ViewFields>
		<FieldRef Name="Title" />
		<FieldRef Name="Projecttype" />
		<FieldRef Name="VastgoedProjectStatus" />
		<FieldRef Name="Eigenaar" />
		<FieldRef Name="Opdrachtgever" />
		<FieldRef Name="Projectnummer" />
	</ViewFields>
	<RowLimit Paged="TRUE">100</RowLimit>
	<Aggregations Value="Off" />
	<ViewStyle ID="13" />
	<JSLink>clienttemplates.js</JSLink>
</View>`

This is the result in the view html once applied on a list:

`<XmlDefinition>
	<View Name="{E53FD7B9-4EFB-443A-A362-22EE51E4C041}" Type="HTML" DisplayName="Welkomstpagina" Url="/sites/projecten-vastgoed/provisioning18/Lists/SiteMetaData/Welkomstpagina.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=44" >
		<Query>
			<OrderBy>
				<FieldRef Name="ID"/>
			</OrderBy>
		</Query>
		<ViewFields>
			<FieldRef Name="Title"/>
			<FieldRef Name="Projecttype"/>
			<FieldRef Name="VastgoedProjectStatus"/>
			<FieldRef Name="Eigenaar"/>
			<FieldRef Name="Opdrachtgever"/>
			<FieldRef Name="Projectnummer"/>
		</ViewFields>
		<RowLimit Paged="TRUE">100</RowLimit>
		<JSLink>clienttemplates.js</JSLink>
		<XslLink Default="TRUE">main.xsl</XslLink>
		<Toolbar Type="Standard"/>
	</View>
</XmlDefinition>`

without the `<ViewStyle ID="13" />` tag

**Comment by TomGoorts** [comment]
With this piece of code it's possible to correct the missing ViewStyle, so setting the property is allowed by MS :-) :
`$ctx = Get-PnPContext
$list = $ctx.Web.Lists.GetByTitle("Projectinformatie")
$views = $list.Views
$view = $views.GetByTitle("Welkomstpagina")
$ctx.Load($view)
$ctx.ExecuteQuery()
[int]$styleId = 13;

$doc = New-Object System.Xml.XmlDocument;
$doc.LoadXml($view.ListViewXml);

[System.XML.XMLElement]$element = $doc.SelectSingleNode("//View//ViewStyle");
if ($element -eq $null)
{
    $element = $doc.CreateElement("ViewStyle");
    $element.SetAttribute("ID", $styleId.ToString());
    $doc.DocumentElement.AppendChild($element);    
}
else
{
    $element.SetAttribute("ID", $styleId.ToString());
}

$view.ListViewXml = $doc.FirstChild.InnerXml;
$view.Update();
$ctx.ExecuteQuery(); 
`

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, the View XML is based on CAML and we simply use an xsd:any element to represent that information. Thus, we cannot fix this issue at schema level. I will create a new issue in the PnP-Sites-Core repository and we will see if we can somehow handle your request at the engine level. I will close this item.
