### ISSUE TITLE
Navigation provisioning does not seem to support Audience?

### ISSUE THREAD

**Issue by AlexRutschk** [SharePoint/PnP-Provisioning-Schema#169]
I don't know how this should be tagged, but the thing is simple ;

We want to provision the navigation of our subsite, but apply some audience on one of the items in the menu. At this moment, is it something possible through the provisioning engine at all?

What we did is add a bit of javascript in the masterpage, so the desired item is hidden according to the group the current connected user is in. 
But since we know that in some of our sites, we are able to put an audience on that, we're wondering if this can be done by provisioning itself. And if it is not, can we hope it to be implemented?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This item is related to this one:

https://github.com/SharePoint/PnP-Provisioning-Schema/issues/149

So, I will close this item and keep just the previous one open. Thanks.
