### ISSUE TITLE
Add support for List.ListExperienceOptions

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Provisioning-Schema#171]
To allow forcing classic/modern views on provisioned lists in SPO.

Scenario: Tenant is set to classic by default, but you want to enable modern on new sites you create.

**Comment by PaoloPia** [comment]
Hi Mikael,
Thanks for your feedback. This requirement has already been satisfied by handling this issue:

https://github.com/SharePoint/PnP-Provisioning-Schema/issues/136

It will show up in the next schema version. I will close this item.
