### ISSUE TITLE
Support external lists

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Provisioning-Schema#172]
See https://github.com/SharePoint/PnP-Sites-Core/issues/1044 from @Pieter-Veenstra 

Category
[ X ] Bug
[ ] Enhancement
Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
Expected or Desired Behavior
External lists are exported without any problem (although maybe some information needed to recreate the list may need to be added)
Observed Behavior
When Applying the template the external list is failing
More details also on tech community:
https://techcommunity.microsoft.com/t5/SharePoint-Developer/PnP-Provisioning-Engine-and-external-lists/m-p/44464/highlight/false#M1431
Steps to Reproduce
Add external list to a site.
export the site as a template. Then apply the template to a new site.

====

I've done some more investigation into this issue today.
For external lists we're not storing any data source connections etc. So this is likely to need schema changes etc.
Are there any plans to implement this? External lists are quite a common element of our solutions and therefore this could be quite painful if this isn't included.

**Comment by PaoloPia** [comment]
We added the DataSource element to the ListInstance element. It will show up in the upcoming schema release.

**Comment by dmytrol** [comment]
@PaoloPia I've tried to generate a provisioning template with `Get-SPOProvisioningTemplate` but didn't get any DataSource elements in the generated template for the external list.

The content type bindings for this external list look like
```
<pnp:ContentTypeBindings>
    <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
</pnp:ContentTypeBindings>
```

The ` <pnp:Views>` looks like it is referencing correct methods and fields but neither does it seem to reference the proper external content type.
