### ISSUE TITLE
Webpart XML Definition will be ignored

### ISSUE THREAD

**Issue by StefanKiessig** [SharePoint/PnP-Provisioning-Schema#173]
Hi,

on one webpart on my root site there will be ignore the property XmlDefinition on creation process. The template was created with Get-PnPProvisioningTemplate . The template runs without any errors. But it ignores the property XmlDefinition and shows the toolbar in this webpart

`<property name="XmlDefinition" type="string">&lt;View Name="{F29AD76F-552F-41ED-9B21-9472ED928E31}" Type="HTML" Hidden="TRUE" TabularView="FALSE" DisplayName="" Url="{site}/SitePages/Home.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=44" &gt;&lt;Query&gt;&lt;OrderBy&gt;&lt;FieldRef Name="ID"/&gt;&lt;/OrderBy&gt;&lt;/Query&gt;&lt;ViewFields&gt;&lt;FieldRef Name="LinkTitle"/&gt;&lt;FieldRef Name="Name"/&gt;&lt;/ViewFields&gt;&lt;RowLimit Paged="TRUE"&gt;30&lt;/RowLimit&gt;&lt;Aggregations Value="Off"/&gt;&lt;JSLink&gt;clienttemplates.js&lt;/JSLink&gt;&lt;XslLink Default="TRUE"&gt;main.xsl&lt;/XslLink&gt;&lt;Toolbar Type="None"/&gt;&lt;/View&gt;</property>`

Regards
Stefan

**Comment by allemaalvisjes** [comment]
I concur.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, from a shema perspective the XML content of a Web Part is just a xsd:any element. Thus, this issue is more engine related, rather than schema related. I will create a new item in the PnP-Sites-Core repository and I will close this item.
