### ISSUE TITLE
Navigation switching and links

### ISSUE THREAD

**Issue by jyou338** [SharePoint/PnP-Provisioning-Schema#174]
I'm trying to provision the navigation settings through provisioning and there are 2 issues that are occurring. I'm using this navigation xml
```
<pnp:Navigation>
  <pnp:GlobalNavigation NavigationType="Structural">
    <pnp:StructuralNavigation RemoveExistingNodes="true">
      <pnp:NavigationNode Title="Knowledge Base" Url="https://test.com/sites/kb" IsExternal="true" />
      <pnp:NavigationNode Title="Page not found" Url="{site}/Pages/PageNotFoundError.aspx" />
    </pnp:StructuralNavigation>
  </pnp:GlobalNavigation>
  <pnp:CurrentNavigation NavigationType="Structural">
    <pnp:StructuralNavigation RemoveExistingNodes="true">
      <pnp:NavigationNode Title="Page not found" Url="{site}/Pages/PageNotFoundError.aspx" />
      <pnp:NavigationNode Title="Documents Library" Url="{site}/Documents/Forms/AllItems.aspx" />
      <pnp:NavigationNode Title="Page not found" Url="{site}/Pages/PageNotFoundError.aspx" />
    </pnp:StructuralNavigation>
  </pnp:CurrentNavigation>
</pnp:Navigation>
```

The first issue is that ` NavigationType="Structural">` isn't switching over the button from Managed Navigation to Structural Navigation. I'm using some CSOM code to switch it over manually and check the show subsites checkboxes below.

The other issue is that all of these are being added as Headings while I want them to be Links. Oddly enough. they are added as Links if they are child nodes.

**Comment by mozdzen** [comment]
To add to that, setting up Headings without providing Url is not possible.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this is an issue related to the engine, rather than to the schema. Thus, I will close this item and create another one in the PnP-Sites-Core repository.
