### ISSUE TITLE
Add attribute @RemoveContentTypes to AllowedContentTypes element

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#175]
When Document Set content types inherit from another Document Set content type, they inherit the Allowed Content Types, and will appear before the added content types in the New Document menu in document libraries. 
The `@RemoveContentTypes` attribute would allow to add/remove content types and to control their sequence.
```xml
<pnp:AllowedContentTypes RemoveContentTypes="true">
   <!-- Add new content types -->
   <!-- Add parent content types in correct order -->
</pnp:AllowedContentTypes >
```

**Comment by ruslanurban** [comment]
If the content types cannot be removed, there should be another way to change order of content types in a document set.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I added the RemoveExistingContentTypes attribute to the AllowedContentTypes element. It will show up in the next schema version.
