### ISSUE TITLE
Missing documentation - provisioning DataRows TaxonomyField

### ISSUE THREAD

**Issue by jakobnotseth** [SharePoint/PnP-Provisioning-Schema#176]
Provisioning DataRows to a list With taxonomy Works on single values
`<pnp:DataValue FieldName="AMultiTaxonomyField">-1;#<label>|<guid></pnp:DataValue>`
But how do you provision the same for multiple values?
`<pnp:DataValue FieldName="AMultiTaxonomyField">-1;#<label>|<guid>;-1;#<label2>|<guid2></pnp:DataValue>`
Above example would give an Exception stating the values is invalid for taxonomy Field, not using the specific format `<int>;#<label>|<guid>`

Cannot find any good documentation on this either

**Comment by jakobnotseth** [comment]
After digging through, I found the exception comes from the constructor of a TaxonomyFieldValueCollection (SPFieldValidationException), and instead of separating With `;` between items, it Works using `;#`

**Comment by PaoloPia** [comment]
Great! Thanks for your feedback. I will close this item.
