### ISSUE TITLE
Missing template token - {termid:<Group>:<Set>:<TermLabel>} / {sitecollectiontermid:<Set>:<TermLabel>}

### ISSUE THREAD

**Issue by jakobnotseth** [SharePoint/PnP-Provisioning-Schema#177]
When provisioning taxonomyfields, and needing to specify an anchor property, you need to be able to get a termid:
`<Property>
    <Name>AnchorId</Name>
    <Value xmlns:q3="http://www.w3.org/2001/XMLSchema" p4:type="q3:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">{termid:<Group>:<Set>:<TermLabel>}</Value>
</Property>
`
Proposing 2 new tokens:
`{termid:<Group>:<Set>:<TermLabel>}`
`{sitecollectiontermid:<Set>:<TermLabel>}`

I could have used static guids if I didn't also have to provision the termstore using pnp-provisioning, and provisioning to the sitecollection-termgroup to allow multiple installations on the same tenant.

**Comment by jakobnotseth** [comment]
Same token should be available also when provisioning DataRows on lists

**Comment by jakobnotseth** [comment]
Also see https://github.com/SharePoint/PnP-Sites-Core/issues/961 for related issue

**Comment by jakobnotseth** [comment]
Also setting a DefaultValue on a Taxonomy-Field needs termid

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, it relates to the PnP-Sites-Core repository rather than on this one. Since, there are already other PRs and Issues there related to this topic, I will close this item. Thanks again.
