### ISSUE TITLE
AuditLog Settings

### ISSUE THREAD

**Issue by ploete** [SharePoint/PnP-Provisioning-Schema#178]
All audit log settings are exported, except for the location where the audit log reports are stored when the log are trimmed. Can this property be added to the schema?

This seems to be stored in a property (“_auditlogreportstoragelocation”) in the property bag (as is the setting for the number of days to retain logging - _auditlogtrimmingretention), but this property is not exported when exporting a template (and of course not set when applying the template – the mentioned library does exist in the site). 
The property can be set by updating the property in the property bag.

The scenario at hand is to include all necessary audit logging settings in the site template so that everything is set up and configured properly after site provisioning without further intervention.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This request is engine related. Thus, I will close this item and I created a new one in the PnP-Sites-Core repo.
