### ISSUE TITLE
Apply-PnPProvisioningTemplate: Access Denied after provisioning Content Types

### ISSUE THREAD

**Issue by d0cHolland** [SharePoint/PnP-Provisioning-Schema#183]
I've been attempting to write a provisioning script for my company. 

It creates an Office 365 Unified Group successfully, and then attempts to apply the provisioning template defined in my schema.xml file. It successfully creates all of the site columns I've defined, as well as creates the single content type I've defined. Once it gets to the end of provisioning the content types, however, I receive the following error message:

```Powershell
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.
At E:\github\threewill\Project Site Provisioning\provision.ps1:42 char:5
+     Apply-PnPProvisioningTemplate -Path ".\schema.xml"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
```

I took at a look at the team site, created a custom list, enabled content types. and attempted to add an existing content type. Sure enough, my content type was there with all of the site columns. 

So somewhere at the end of of provisioning my content type, this error is being thrown. 

I've attached my source code.
[provisioning.zip](https://github.com/SharePoint/PnP-Provisioning-Schema/files/828634/provisioning.zip)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this issue is more engine related, rather than schema related. Thus, I will close this item and I will refer it with a new issue in the PnP-Sites-Core repository.

**Comment by Teariest** [comment]
So how do we fix this???????????

**Comment by VishwanathaNayak** [comment]
Any suggestions how to handle this error? Thanks in advance
