### ISSUE TITLE
Support for web part connections

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Provisioning-Schema#184]
Currently there is no support for web part connections in the Provisioning Schema. Further to issue 1103 in PnP Sites Core there is a need to support web part connections.

https://github.com/SharePoint/PnP-Sites-Core/issues/1103

**Comment by Pieter-Veenstra** [comment]
@VesaJuvonen I had a further look into this as I wanted to try and work around this issue. the CSOM version of the LimitedWebPartManager doesn't have GetConsumerConnectionPoints. So it looks like this also needs some updates the CSOM.

**Comment by PaoloPia** [comment]
Hi Pieter,
Thanks for your suggestion. Unfortunately, after evaluating your submission we considered that the investment to implement this is too high compared to the actual value of the feature. We might re-consider this for future schema versions, but we cannot implement it right now. In the meantime, you can implement it using a custom engine extension. Thanks.

**Comment by Pieter-Veenstra** [comment]
Hi @PaoloPia, How would I develop this if I can't get to the web part connections through CSOM?
