### ISSUE TITLE
List Instance: Add Content Type Instance (to fix Document Set Default Welcome Page View and other issues) 

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#185]
# Problem

In SharePoint, it is not enough to just create a default view that is scoped to *folders of content type `Document Set Content Type`*.  Document set welcome page contains *Document Set Contents* web part that relies on the default welcome page view property value to display nested document content type columns. 
The following page explains how to set it.
[https://camerondwyer.wordpress.com/tag/document-set-views/#documentset](https://camerondwyer.wordpress.com/tag/document-set-views/#documentset).

Current schema only references existing content types in list instance, but it does not allow creating of list content types. Thus, there is no way to set the default view for the welcome page explicitly in a list instance. 

# Use Case/Test Scenario
Create document set based document library with customized document set view.

## Content Types
1. `Test Document` *Document* content type references fields:
 * `Assigned Test Analyst` *(Person)*
 * `Passed Count` *(Number)*
 * `Failed Count` *(Number)*

2. `Test Suite` *Document Set* content type references fields:
 * `Test Suite ID` *(Text)*
 * `Use Case IDs` *(Lookup, multi-select)*
 * `Test Manager` *(Person)*

Allowed content types:
 * `Test Document`
 * `Link to a document`

Shared fields:
 * `Test Suite ID` *(Text)*

Welcome page fields:
 * `Test Suite ID` *(Text)*
 * `Use Case IDs` *(Lookup, multi-select)*
 * `Test Manager` *(Person)*

## List Instance

`Tests` document library configuration:
 * Allow management of content types
 * Add content type `Test Suite`
 * Add content type `Test Document` *(need it to create cross document set view)*
 * Remove content type `Document`
 * In the *Change new button order and default content type* dialog make `Test Suite` default and hide `Test Document`
* Modify default `All documents` view
   - Add `Test Suite` shared fields:  `Test Suite ID`
* Create standard view `Test Suite Default View`
   - Mark it as default view
   - Add `Test Document` fields:   `Assigned Test Analyst`, `Passed Count`, `Failed Count`
   - Set *Folders* settings: *Show this view in folders of content type `Test Suite`*
* Create standard view `Cross Document Set View`
   - Mark it as default view
   - Add `Test Suite` shared fields:  `Test Suite ID` *(to identify document set)*
   - Add `Test Document` fields:   `Assigned Test Analyst`, `Passed Count`, `Failed Count`
   - Set *Folders* settings: *Show this view in folders of content type `Test Suite`*

## Test
In this test will confirm that the `Test Suite Default View` id not being applied despite being marked as default view for the folder content type.

 * Create new `Test Suite`. Enter **TS-001** in the *Test Suite ID* field, and any values in all other fields.
 * Click on the added document set with *Test Suite ID*= **TS-001** in the  *Add documents* view
 * Document set welcome page opens. It displays test suite title, description, ID, use case IDs, test manager
 * Add a new `Test Document` document. Enter values in all property fields.
 * Notice columns and their values in the documents list. The columns are from the list default view *All Documents*.

## Analysis 
The reason for this behavior is that instead of folder-type-linked default view, SharePoint is using data set welcome page and welcome page default view value to display list of documents in the  *Document Set Contents* web part on the page. To fix that, list instance content type reference needs to be converted into a list content type and the welcome page default view needs to be set to `Test Suite Default View`, which is currently not supported.

# Other things to consider
The default  view can be identified implicitly by the `Default` and `ContentTypeID` properties on the view, but behind the scenes, another content type still need to be created to set the welcome page view value.  Also, cannot set this value on a content type in content type hub. It needs to be set explicitly on a list. 
A number of other issues may arise later, e.g. default document for the allowed content types, welcome page customizations (e.g. image), etc.

**Comment by PaoloPia** [comment]
Hi Ruslan,
Thanks for your complete and deep analysis. However, this issue is more engine related, rather than schema related. Thus, I will close this item and create another one, referencing this, in the PnP-Sites-Core repository. Thanks again.

**Comment by heinrich-ulbricht** [comment]
@PaoloPia Unfortunately https://github.com/pnp/PnP-Sites-Core/issues/1190 is in a now archived repo and only points back to this ticket. Has there ever been a development in this direction?
