### ISSUE TITLE
Add support for uploading files with specific file name

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Provisioning-Schema#189]
Related to the [pnp:File](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#file) element.

I would like to have added an extra attribute, (proposed) `URL` so that I can provision a file with a name different from its template, or provision multiple files from the same template

```xml
<pnp:File 
   Src="Files\doctemplate.docx" 
   Folder="{site}/Documents" 
  Overwrite="true" 
  Level="Published"
  URL="Document1.docx">
...
</pnp:File>
<pnp:File 
   Src="Files\doctemplate.docx" 
   Folder="{site}/Documents" 
  Overwrite="true" 
  Level="Published"
  URL="Document2.docx">
...
</pnp:File>
```

**Comment by PaoloPia** [comment]
Hi,
I defined a TargetFileName attribute, which supportes tokenization. It will show up in the next schema version. I will close this item. Thanks for your feedback.
