### ISSUE TITLE
add to schema Functionality to set Document set view

### ISSUE THREAD

**Issue by KbWorks** [SharePoint/PnP-Provisioning-Schema#190]
It would be nice to have the possibility to add a view to a document set per listinstance.

<pnp:Documentset>
     <pnp:contenttype id="" name="">
         <pnp:view name="all documents"></pnp:view>
     <pnp:contenttype>
</pnp:Documentset>

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The idea is great, and someone else already submitted it, too. However, we need to figure out how to implement this capability at the engine level.

**Comment by KbWorks** [comment]
Hi Paolo,

thank you i wrote a extension method for it maybe you can use it in the core in combination with the schema change.

**Comment by PaoloPia** [comment]
Hi Paul,
Sorry for the delayed answer, where is the extension method? Is it in Core or in your own code somewhere else? Can you share it? Thanks.

**Comment by KbWorks** [comment]
Hi Paolo,

will look it up and send a message thanks again.

Paul

**Comment by KbWorks** [comment]
Hi Paulo,

have not tested if it still works but i can test it if you want.
`  /// <summary>
        /// sets the view for a Documentset welcome page.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <param name="web">The web.</param>
        /// <param name="list">The list.</param>
        /// <param name="contenttype">The contenttype.</param>
        /// <param name="welcomePageview">The contenttype.</param>
        private void SetDocumentSetView(ClientContext context, Web web, List spList, string pContentType, string welcomePageview)
        {
            
            //var contenttype = spList.ContentTypes.GetById(pContentType);
            context.Load(spList, l => l.ContentTypes);
            context.ExecuteQuery();

            var contenttype = spList.ContentTypes.FirstOrDefault(c => c.Name == pContentType);
            var viewid = spList.GetViewByName(welcomePageview).Id;

            var docSetTemplate = DocumentSetTemplate.GetDocumentSetTemplate(context, contenttype);

            //context.Load(contenttype, c => c.SchemaXmlWithResourceTokens);
            context.Load(contenttype, c => c.SchemaXml, c => c.SchemaXmlWithResourceTokens);
            context.Load(docSetTemplate);
            context.ExecuteQuery();

            var xmlschema = string.IsNullOrEmpty(contenttype.SchemaXmlWithResourceTokens) ? contenttype.SchemaXml : contenttype.SchemaXmlWithResourceTokens;
            if (xmlschema.Contains("XmlDocuments"))
            {
                XmlDocument xmldocument = new XmlDocument();
                xmldocument.LoadXml(xmlschema);

                XmlNodeList xmldocs = xmldocument.SelectNodes("ContentType/XmlDocuments/XmlDocument");
                foreach (XmlNode xmldoc in xmldocs)
                {
                    if (xmldoc.ChildNodes.Count > 0)
                    {                    
                        var firstChildNodeName = xmldoc.FirstChild.Name;    //xmldoc.ChildNodes[0].Name;
                        if (firstChildNodeName == "WelcomePageView")
                        {
                            // Create new default view XML
                            string newDefaultViewXml = string.Format(@"<wpv:WelcomePageView xmlns:wpv='http://schemas.microsoft.com/office/documentsets/welcomepageview' ViewId='{0}' />", viewid);

                            // Replace default view XML
                            xmldoc.FirstChild.InnerXml = newDefaultViewXml;

                            // Exit foreach loop
                            break;
                        }
                    }
                }

                StringWriter sw = new StringWriter();
                XmlTextWriter tx = new XmlTextWriter(sw);
                xmldocument.WriteTo(tx);
                xmlschema = sw.ToString();

                 contenttype.Update(false);
               
            }
        }`

**Comment by PaoloPia** [comment]
Hi @KbWorks,
We just added to the upcoming new schema version a XmlDocuments element for the DocumentSet. In the future, we will add corresponding functionality at the engine level. Thanks.

**Comment by rajajii** [comment]
Hi KbWorks 
Most likly your code is for SharePoint onpremises. I tried your approach on sharepoint online, but it did not work since SchemaXml is readonly property in online version. 

Thaks anyway

**Comment by frankok** [comment]
Hi @PaoloPia,
Is this now added and supported in 2018/07 schema, or has it just been added for future use?

**Comment by holylander** [comment]
Hi @PaoloPia ,

I am trying to define the default view for a docset using this code
` <XmlDocument NamespaceURI="http://schemas.microsoft.com/office/documentsets/welcomepageview">
                <WelcomePageView xmlns="http://schemas.microsoft.com/office/documentsets/welcomepageview" LastModified="1/1/1 0:00:01 AM" />
              </XmlDocument>`
but It doesnt work. Any suggestion idea how to fulfill this? thanks!!

**Comment by holylander** [comment]
It seems there is not any way to implement this
https://sharepoint.stackexchange.com/questions/256463/pnp-provisioning-welcomepageview-in-document-sets

**Comment by holylander** [comment]
> 
> 
> Hi KbWorks
> Most likly your code is for SharePoint onpremises. I tried your approach on sharepoint online, but it did not work since SchemaXml is readonly property in online version.
> 
> Thanks anyway

I can confirm the previous statement.
It seems there is not any way to implement this on sharepoint online so far
https://sharepoint.stackexchange.com/questions/256463/pnp-provisioning-welcomepageview-in-document-sets

**Comment by poidah** [comment]
So here we are 5 years later and there doesn't seem to be a programatic or declaritive way to set the view to be used within a document set.

One would assume this would have to be a setting at the library level - this is because:
-  There are no views defined at a site level (alone with site columns and site content types)
-  The library and the view need to exist for there to be a ViewID to reference

Please Microsoft, how do we use your tools in a scalable way?

**Comment by T-LeGranc** [comment]
So here we are 2 more years later and this is still not possible.

**Comment by MrRCG5** [comment]
Can we update the "ViewId" in the "SchemaXML"? I tried and the SchemaXML is read-only.

**Comment by zenlord** [comment]
@MrRCG5 Yes, that's the way to do it currently, and it is pretty easy:

```
$welcomePageView = Get-PnPView -Identity $view.Displayname -List $list
$xml = [xml](Get-PnPContentType -Identity $ctType.Name -List $library | Select -Expand SchemaXml)
$node = $xml.ContentType.XmlDocuments.XmlDocument | where {$_.NamespaceURI -eq 'http://schemas.microsoft.com/office/documentsets/welcomepageview'}
$node.InnerXml = "<wpv:WelcomePageView xmlns:wpv=`"http://schemas.microsoft.com/office/documentsets/welcomepageview`" ViewId=`"$($welcomePageView.Id)`" />"
```

**Comment by MrRCG5** [comment]
> newDefaultViewXml

It is not working for me using SharePoint online. How is "$node.InnerXml" being updated? Do I need to execute or invoke a change?

**Comment by zenlord** [comment]
> > newDefaultViewXml
> 
> It is not working for me using SharePoint online. How is "$node.InnerXml" being updated? Do I need to execute or invoke a change?

You are correct. I must have been testing the wrong variables and assumed wrongly it was working, but it is not. The property 'SchemaXml" is read-only. I don't know if this is a setting that can be changed per instance, or not.
Cross link: https://sharepoint.stackexchange.com/a/314039/68024
