### ISSUE TITLE
Cannot create files within subfolders with either File or Directory

### ISSUE THREAD

**Issue by moontear** [SharePoint/PnP-Provisioning-Schema#191]
I'm trying to use the recursive directory create to upload stuff to SiteAssets. However it always fails to create the folder ("Folder") and upload files within that folder (or subfolders) in one go. Upon calling Apply-PNPProvisioningTemplate a second time, all files within the folders including nested subfolders are provisioned just fine.

I can reproduce this with the following template.xml - the problem exists both when using `File` with a `Folder` path of `SiteAssets/Folder` and when using `Directory` with `recursive=true`. 

My folder structure is simple:
- .\template.xml
- .\logo.png
- .\Folder\
- .\Folder\customJsFile.js
- .\Folder\SubFolder\AnotherFile.js

I want to recreate the same structure within SiteAssets. Running `Apply-PnPPublishingTemplate template.xml` the first time creates the folder "Folder", uploads the `logo.png`file and throws a *File not found* exception. Running the same command a second time uploads the `customJsFile.js` just fine (and any other files in that folder). Funnily also `SubFolder\AnotherFile.js` is also created on the second run (meaning folder & file). Basically everything on the first level is uploaded on the first run, but subsequent levels are not.

```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.0.1601.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="WM-SCFile">
    <pnp:ProvisioningTemplate ID="SCFile" Version="1">
      <pnp:Files>
        <!-- BUG: Creates sub folders, but doesn't add files (file not found). On second run, files are created-->
        <pnp:Directory Src=".\" Folder="SiteAssets" Overwrite="true" Recursive="true" ExcludedExtensions="*.xml"/>
        <!--<pnp:File Src=".\Folder\customJsFile.js" Folder="SiteAssets/Folder" Overwrite="true" />-->
      </pnp:Files>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this issue is more engine related, rather than schema related. Thus, I will close this item and I will refer it with a new issue in the PnP-Sites-Core repository.
