### ISSUE TITLE
Allow for typed (and untyped) Field elements

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#193]
Typed field elements would allow for schema-driven validation, intellisense in XML tools that support such functionality. It would also improve readability of the templates, and would make deployments more predictable because currently it is relatively simple to introduce elements and attributes that may not be supported by a particular field type, and failure would happen at runtime.
The field schema type names should match names of the classes in the namespace Microsoft.SharePoint.Client and attribute names should match class property names (see [https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.field.aspx#Inheritance hierarchy](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.field.aspx#Inheritance%20hierarchy))

Support for untyped Field elements can mean easier upgradeability for the existing templates and would allow to implement some quirky (sometimes undocumented) functionality like provisioning of computed fields. 

Utilities like [AutoMapper](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started) can simplify value mapping routines. 

Example:
```xml

<pnp:Fields>

	<pnp:FieldMultiLineText ID="e7f0a591-c790-4fc2-9ea7-6181920eee00"
		Title="Request Reason Hidden Field"
		Name="CUST_RequestReason_0"
		Group="_Hidden"
		ShowInViewForms="false"
		Required="false"
		Hidden="true"
		CanToggleHidden="true" />

	<pnp:TaxonomyField ID="e7f0a591-c790-4fc2-9ea7-6181920eee01"
		Title="Request Reason"
		Name="CUST_RequestReason"
		Group="Admin"
		Required="false"
		EnforceUniqueValues="false"
		SspId="{sitecollectiontermstoreid}"
		TermSetId="{termsetid:Admin:Requests}"
		AnchorId="{termid:Admin:Requests:Request Reason}"
		DefaultValue="{termid:Admin:Requests:Request Reason:Vacation}"
		TextField="{fieldid:Request Reason Hidden Field}" />

	<Field ID="051fecad-eb0d-404e-b19e-f767b1231612" 
		DisplayName="Travel Method" 
		Name="CUST_TravelMethod" 
		StaticName="CUST_TravelMethod"
		Group="Admin" 
		Type="Choice" 
		Format="Dropdown" 
		FromBaseType="false" 
		Required="false" 
		EnforceUniqueValues="false" 
		Indexed="false" 
		FillInChoice="false" >
		<Default>Air</Default>
		<CHOICES>
			<CHOICE>Air</CHOICE>
			<CHOICE>Bus/coach</CHOICE>
			<CHOICE>Public transportation</CHOICE>
			<CHOICE>Rental vehicle</CHOICE>
			<CHOICE>Personal vehicle</CHOICE>
			<CHOICE>Train</CHOICE>
			<CHOICE>Walking</CHOICE>
			<CHOICE>Other</CHOICE>
		</CHOICES>
	</Field>

</pnp:Fields>

```

The negative impact can be that the routines to determine changes in field definitions that currently rely on field schema XML comparison can become more complicated.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The idea is good and we are already thinking about it, since a while ago. However, it requires a significant amount of work and engine refactoring, because right now we use CAML to be easily backward compatible and to use native capabilities of CSOM. We will keep this item on hold.

**Comment by ruslanurban** [comment]
The implementation should allow for removal of Taxonomy-backing note fields and can prevent from search crawling issues as described in [Issue #49](https://github.com/SharePoint/PnP-Provisioning-Schema/issues/49).

**Comment by ruslanurban** [comment]
Also, the note field should not get exported to prevent from issues when re-applying the template.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
