### ISSUE TITLE
ComposedLook resetting MasterPage

### ISSUE THREAD

**Issue by moontear** [SharePoint/PnP-Provisioning-Schema#194]
The `ComposedLook` element https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#composedlook resets the **MasterPage** to the default (e.g. seattle.master) when applying.

This can only be remedied by also having a `WebSettings` element in the provisioning template setting the `MasterPageUrl` and the `CustoMasterPageUrl`. If both `WebSettings` and `ComposedLook` elements exist in the template, everything works fine. If a custom master page was previously set, the setting is not retained in the composed look.

I assume we would also need a `MasterUrl` property for `pnp:ComposedLook` or at least some documentation that `WebSettings` are always needed if a customer master page is to be used.
Secondly it would be great if the composed look would simply use the current master page instead of using the default.

**Comment by PaoloPia** [comment]
Hi @moontear,
Thanks for your feedback. This is more related to the engine, rather than to the schema. We will try to document the right behavior of the engine. Thanks.
