### ISSUE TITLE
Cannot set integer and "special" properties on Files

### ISSUE THREAD

**Issue by moontear** [SharePoint/PnP-Provisioning-Schema#195]
Trying to deploy a display template JavaScript file as shown here:
http://sharepointcookies.com/2015/07/working-with-display-templates-with-the-new-pnp-provisioning-core-engine/

I get the exception `Apply-PnPProvisioningTemplate : Error converting value 15 to type 'System.String[]'. Path '', line 1, position 2.`

The same error happens when I remove the `UIVersion` property with the TemplateHidden` property`. Another error happens with the "special" characters for `TargetControlType`: `;#SearchResults;#`. The exception is: `Apply-PnPProvisioningTemplate : Unexpected character encountered while parsing value: ;. Path '', line 0, position 0.`
The error messages don't really help...

The only fix is to **not** have the following properties
- 	`<pnp:Property Key="UIVersion" Value="15" />`
- 	`<pnp:Property Key="TemplateHidden" Value="0" />`
-	`<pnp:Property Key="TargetControlType" Value=";#SearchResults;#" />`

Without these file properties (basically any `int` property and special character such as `#`) the display template provisions just fine, but it cannot be selected in a search result web part because the `TargetControlType` is missing. Once I set this manually everything is fine.

Setting those properties with PnP PowerShell (i.e. Set-PnPListItem ...) works without problem, so it is a problem with provisioning.

Environment is SP2013 OnPrem, using SharePointPnPPowerShell2013 2.14.1704.0.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this issue is more engine related, rather than schema related. Thus, I will close this item and I will refer it with a new issue in the PnP-Sites-Core repository.
