### ISSUE TITLE
Make it possible to provision SPFx client side web parts and modern pages

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Provisioning-Schema#196]
At the schema level:
- We need to provision client side web parts in classic and modern sites
- We need to provision modern pages with client side web parts (being able to define sections with type or number of columns, or a free hierarchy of sections, including the ordering of sections)
- We need to provision SPFx solutions and add-ins in the App Catalog at the highest level of the schema
- We need to deploy SPFx solutions and add-ins into a site

**Comment by patrick-blanc** [comment]
Hi there :)
Would it be possible in a near future to provision modern page with pnp provisioning schema ?
I did it right now using <PnP:Files> and it is working fine. Only thing that is frustrating for me is that I should have the source page in my drive.
For example I have the structure 
- .\ProvisioningSchema.xml
- .\SitePages\MyPage.aspx 

This page is quite simple, for me this is more a template that the page created in SharePoint at the end because content of the page is created with the schema XML.

In the XML file I have a file section where I specify the CanvasContent to add my spfx webpart for example. All of this is working fine.
```
<pnp:File Src="SitePages\MyPage.aspx" Folder="{site}/SitePages" Overwrite="true" Level="Published">
	<pnp:Properties> 
		<pnp:Property Key="ContentTypeId" Value="0x0101009D1CB255DA76424F860D91F20E6C4118" />
		<pnp:Property Key="Title" Value="Home... Sweet Home" />
		<pnp:Property Key="ClientSideApplicationId" Value="b6917cb1-93a0-4b97-a84d-7cf49975d4ec" />
		<pnp:Property Key="PageLayoutType" Value="Article" />
		<pnp:Property Key="CanvasContent1" Value="... spfx content ..." />
		<pnp:Property Key="BannerImageUrl" Value="https://testsbb.sharepoint.com/_layouts/15/images/sitepagethumbnail.png, /_layouts/15/images/sitepagethumbnail.png" />
		<pnp:Property Key="PromotedState" Value="0" />
	</pnp:Properties>
</pnp:File>
```

I want to know is, is there a simple way in the future to get rid of the 
- .\SitePages\MyPage.aspx ? 

For example use the <PnP:Pages> to provision a modern page ?
```
<PnP:Pages>
	<PnP:SitePage Url="SitePages\MyPage.aspx" UseModernDesign="true">
</PnP:Pages>
```
Or is there a way to specify the destination file name of a file. 
```
<PnP:Files>
	<pnp:File Src="SitePages\MyPage.aspx" Folder="{site}/SitePages" Dest="Home.aspx" Overwrite="true" Level="Published">
<PnP:Files>
```

This would be fine, with this last schema, we would be able to use only one source page as template and to provision multiple page in the site pages library.

```
<PnP:Files>
	<pnp:File Src="SitePages\Template.aspx" Folder="{site}/SitePages" Dest="Home.aspx" Overwrite="true" Level="Published">...</PnP:File>
	<pnp:File Src="SitePages\Template.aspx" Folder="{site}/SitePages" Dest="Home.aspx" Overwrite="true" Level="Published">...</PnP:File>
</PnP:Files>
```
Something like that.

Thanks for your answer 👍

**Comment by patrick-blanc** [comment]
I also agree for the other point 👍 

It would be really fine if we can install an app to a site from the addin catalog through the template

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. In the new schema (201705) we include the capability to declare client-side pages and client-side web part (which however still have to be installed manually, before). I will close this item.

**Comment by amitsaraswat83** [comment]
Hi PaoloPia, 

i am still didn't find the solution for provision SPFx client side web parts and modern pages in Provision new schema (201705).

Waiting for your response as i need it in urgent.

**Comment by patrick-blanc** [comment]
Hi @amitsaraswat83 
It is included in schema @PaoloPia  mentionned above. Please visite [this link](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2017-05.md#clientsidepages) 

XML looks like this :
```XML
<pnp:ClientSidePages>
  <pnp:ClientSidePage PageName="HomePage.aspx" PromoteAsNewsArticle="false" Overwrite="true">
    <pnp:Sections>
      <pnp:Section Order="1" Type="OneColumn">
        <pnp:Controls>
          <pnp:CanvasControl WebPartType="Custom" JsonControlData="webpart property json" ControlId="..." Column="1" />
        </pnp:Controls>
      </pnp:Section>
    </pnp:Sections>
  </pnp:ClientSidePage>
</pnp:ClientSidePages>
```

If you update your PowerShell module and then use the following commands, you should get the corresponding XML for your client side page including the SPFX webparts content

```PowerShell
Connect-PnPOnline -Url "your web site url"
Get-PnPProvisioningTemplate -Out D:\myTemplate.xml
```

Be sure to run before doing it.

```PowerShell
Update-Module SharePointPnPPowerShell*
```

**Comment by amitsaraswat83** [comment]
@patrick-blanc  Thanks for your update and i have tried this already in my site for site provisioning but problem is when i extract the schema from my site and extracted schema is old  which is not supporting modern pages "<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">" 

I have raised this to Microsoft they tried to help me but no luck.

Note :- My Tenant update for First Release.

**Comment by codingWithAshish01** [comment]
Yes It is possible I have Tried with this link : ["https://technoinfoforknowledge.blogspot.com/2023/07/create-sharepoint-page-and-web-part.html"](https://technoinfoforknowledge.blogspot.com/2023/07/create-sharepoint-page-and-web-part.html)
