### ISSUE TITLE
Apply-PnPTemplate does not assign Term Group Contributors

### ISSUE THREAD

**Issue by d0cHolland** [SharePoint/PnP-Provisioning-Schema#199]
This issue was encountered using PnP-PowerShell for SharePoint 2016, and using the "http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema" schema that was generated using PnP.

When attempting to use the Apply-PnPTemplate cmdlet on my site, I've noticed that the users I specified as Term Group Contributors for my term group are not being listed.

The terms and everything else provision correctly. 
Here's the section of my template in question. The user listed is a valid AD user and has access to the site.

````
<pnp:TermGroup Name="{sitecollectiontermgroupname}" Description="" SiteCollectionTermGroup="true">
   <pnp:TermSets>...</pnp:TermSets>
   <pnp:Contributors>
            <pnp:User Name="mydc\jenkinsd" />
    </pnp:Contributors>
</pnp:TermGroup>
````

For the "Name" property, I've tried the following
- 1:0#.w|mydc\jenkinsd
- mydc\jenkinsd
- jenkinsd
- jenkinsd@mydc

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this issue is more engine related, rather than schema related. Thus, I will close this item and I will refer it with a new issue in the PnP-Sites-Core repository.
