### ISSUE TITLE
Missing properties for SPList in schema

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-Provisioning-Schema#200]
For one of our customers we're trying to set the ImageUrl property of a List using pnp provisioning.
I was surprised to see that's it's missing from the schema https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#listinstance
However this property has been available in the CSOM for quite a while now https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.list_properties.aspx
It's also available in the REST API https://msdn.microsoft.com/en-us/library/office/dn531433.aspx 
Comparing a little bit more the schema and the CSOM reference I noticed a lot of properties are actually missing.
Is there any particular reason for that? Is there any plan to add these missing properties?
Thanks!

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We added some of the missing property (including the ImageUrl) and they will show up in the upcoming new schema version. I will close this item.

**Comment by baywet** [comment]
Thanks very much for implementing that so quickly!!!
I couldn't find information about the timeframe for that next version, could you please share something around that?

**Comment by PaoloPia** [comment]
The new schema should be 201705, i.e. this month :) ... of course, the engine part of the implementation will come later, because it can start just after the release of the new schema version.
