### ISSUE TITLE
Add attribute `ErrorAction` to allow for provisioning of critical elements; Review error handling and execution reporting

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#201]
# Problem
Currently, provisioning ***stops if there is any kind of error*** in the templates. 
This creates lot of headaches, especially when provisioning of very large templates into multiple environments. Finding of the elements that break the process based on the trace logs is often challenging because not all of the context information can be esily identifiable in the logs (e.g. when error is in the list view definition, list title can appear earlier in the logs and it is hard to correlate the view with the list. 

# Proposed solution
The attribute **`ErrorAction`**="**`Stop`**|**`Continue`**|**`Ignore`**" would allow to continue provisioning if the error was in a view definition, for example, but the rest of the site would be provisioned. 

* **`Stop`** is a critical/halt condition when further execution could create potential problems or break dependencies (default behavior).
*  **`Continue`** is a non-critical condition that will continue execution, but will log (and display) a warning.
* **`Ignore`** would simply ignore the error. It should still appear in the logs (and potentially displayed) when trace level is Debug or Verbose.

The `ErrorAction` element should be applied to most top-level `ProvisioningTemplate` children and most individual elements, such as `ListInstance`, `View`, `NavigationNode`, `User`, etc.

`ErrorAction` applied to a container should be propagated to all of its children. Children can override the behavior.

## Execution Report
Ideally, provisioning engine should be able to provide with an **execution report** that contains information of which elements had ***failed***, what got ***added***, ***modified***, ***skipped*** or ***removed***. Such report would allow to create environment-specific patches, and can significantly simplify troubleshooting, reporting and change management processes.

**Comment by PaoloPia** [comment]
Hi @ruslanurban,
Thanks for your feedback. We plan to support native arguments of PowerShell or in the engine at the .NET level in order to do that, rather than changing the schema. Thus, I will close this item and we will keep on working "under the cover".

**Comment by ruslanurban** [comment]
You may want to control it at different levels. Like if an error happens in a list instance View, you may want to report an error rather than break on an error

**Comment by GamalMohamed** [comment]
Any updates on this issue?
