### ISSUE TITLE
Extend Parameter element to have Type and TypeRelatedInfo attribute

### ISSUE THREAD

**Issue by slackeramit** [SharePoint/PnP-Provisioning-Schema#204]
In the PnP Partner Pack(and other custom implementations), the parameters element is used to take input from users and update it in the template before passing it on to the provisioning engine.
Now these parameters could be of different types like Managed Metadata, People, Lookup, String, Int, Choice etc. and when we present the input form to user, we would like to be able to provide a UI consistent with SharePoint/Office365 like a Taxonomy Picker for Managed Metadata values, Poeple Picker for People values, Drop down for Choice values and so on.
Further, the Type will also help us validate the values before passing it on to the engine and prevent/avoid any errors due to type conversion/mismatch errors.
I propose two attributes:
1. Type - Optional - Should have the Fully Qualified Type Name/Assembly Qualified Name, e.g., Microsoft.SharePoint.Client.Taxonomy.TaxonomyFieldValue for Metadata values and so on.
2. TypeRelatedInfo - Optional - Should have extra information that might be required to show the UI, e.g., the TermSetId in case of ManagedMetadata values, List of Choices for Choice value etc.

**Comment by PaoloPia** [comment]
Hi @slackeramit,
We investigated your request. So far, we cannot implement it, because it would be a very breaking change for existing templates and schemas. I would suggest using a prefix for the parameters' names, in order to identify the corresponding type, and to create a custom UI on top of the template. Thanks.
