### ISSUE TITLE
Empty title when provisioning data rows with user field value

### ISSUE THREAD

**Issue by marcelabovio** [SharePoint/PnP-Provisioning-Schema#207]
Whenever I deploy a DataRow item in a list including a user field value, the title field is empty even though I also provide a value for it. 

I've used the code below (taken from one of the repository samples). I've deployed this to a brand new, empty standard team site in both English and Dutch languages.

--------------------------------------------

`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.9.1611.0, Culture=neutral, PublicKeyToken=3751622786b357c2">
    <pnp:Parameters>
      <pnp:Parameter Key="Site_Title" Required="true">Test site</pnp:Parameter>
      <pnp:Parameter Key="Site_Doel" Required="true">Testen</pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
  <pnp:Templates ID="TEAMSITE3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-TEAMSITE3" Version="1">
       <pnp:SiteFields>
         <Field ID="{2735DBDB-F789-4E72-A956-FBA7B6FB21E9}" Name="PnPOrderTarget" StaticName="PnPOrderTarget" DisplayName="Target User" Group="PnP Site Columns" Type="User" List="UserInfo" UserSelectionMode="PeopleOnly" />
         <Field ID="{55D68C76-D375-4FF2-AB60-E9281521F738}" Name="PnPOrderSupplier" StaticName="PnPOrderSupplier" DisplayName="Supplier" Group="PnP Site Columns" Type="Text" />
         <Field ID="{55343AEA-D070-4336-8519-798BA3C1CA51}" Name="PnPOrderNote" StaticName="PnPOrderNote" DisplayName="Notes" Group="PnP Site Columns" Type="Text" />
         <Field ID="{813E0521-D94D-41D3-8E81-E79FB247DF75}" Name="PnPOrderApproved" StaticName="PnPOrderApproved" DisplayName="Approved" Group="PnP Site Columns" Type="Boolean" />
         <Field ID="{5E536E99-6EA7-4A0D-95E0-122C6DD61467}" Name="PnPOrderItemDescription" StaticName="PnPOrderItemDescription" DisplayName="Item Description" Group="PnP Site Columns" Type="Text" />
         <Field ID="{A545F52E-3A82-4F63-9EE4-0751E12D72A9}" Name="PnPOrderItemQuantity" StaticName="PnPOrderItemQuantity" DisplayName="Quantity" Group="PnP Site Columns" Type="Integer" />
         <Field ID="{6B426432-34EC-4EDA-A918-BC36109134B7}" Name="PnPOrderItemPrice" StaticName="PnPOrderItemPrice" DisplayName="Price" Group="PnP Site Columns" Type="Currency" />
         <Field ID="{AE724011-F6A5-4DDE-8E53-72B5B51DD0B4}" Name="PnPOrderItemOrderLookup" StaticName="PnPOrderItemOrderLookup" DisplayName="Order" Group="PnP Site Columns" Type="Lookup" List="Lists/Orders" ShowField="Title" />
      </pnp:SiteFields>
      <pnp:ContentTypes>
        <pnp:ContentType ID="0x01002D415D16908E4116B6E2A940036C2028" Name="PnPOrder" Description="Order" Group="PnP Content Types">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" />
            <pnp:FieldRef ID="2735dbdb-f789-4e72-a956-fba7b6fb21e9" Name="PnPOrderTarget" Required="true" />
            <pnp:FieldRef ID="55d68c76-d375-4ff2-ab60-e9281521f738" Name="PnPOrderSupplier" Required="true" />
            <pnp:FieldRef ID="55343aea-d070-4336-8519-798ba3c1ca51" Name="PnPOrderNote" />
            <pnp:FieldRef ID="813e0521-d94d-41d3-8e81-e79fb247df75" Name="PnPOrderApproved" Required="true" />
          </pnp:FieldRefs>
        </pnp:ContentType>
        <pnp:ContentType ID="0x010080DB087266A240829DF6311D1DE4BEDB" Name="PnPOrderItem" Description="Order Item" Group="PnP Content Types">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="5e536e99-6ea7-4a0d-95e0-122c6dd61467" Name="PnPOrderItemDescription" Required="true" />
            <pnp:FieldRef ID="a545f52e-3a82-4f63-9ee4-0751e12d72a9" Name="PnPOrderItemQuantity" Required="true" />
            <pnp:FieldRef ID="6b426432-34ec-4eda-a918-bc36109134b7" Name="PnPOrderItemPrice" Required="true" />
            <pnp:FieldRef ID="ae724011-f6a5-4dde-8e53-72b5b51dd0b4" Name="PnPOrderItemOrderLookup" Required="true" />
          </pnp:FieldRefs>
        </pnp:ContentType>
      </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="Orders" OnQuickLaunch="true" TemplateType="100" Url="Lists/Orders" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0"
                          RemoveExistingContentTypes="true" ContentTypesEnabled="true">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01002D415D16908E4116B6E2A940036C2028" Default="true" />
          </pnp:ContentTypeBindings>
          <pnp:Views RemoveExistingViews="true">
            <View Name="{72B7CFFE-A861-4AF8-90D1-4DEA0CE952F6}" DefaultView="TRUE" MobileView="TRUE" Type="HTML" DisplayName="Orders" Url="{site}/Lists/Orders/Orders.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=39">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="DocIcon" />
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="PnPOrderTarget" />
                <FieldRef Name="PnPOrderSupplier" />
                <FieldRef Name="PnPOrderApproved" />
                <FieldRef Name="PnPOrderNote" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off" />
              <JSLink>clienttemplates.js</JSLink>
              <XslLink Default="TRUE">main.xsl</XslLink>
              <Toolbar Type="Standard" />
            </View>
          </pnp:Views>
          <pnp:DataRows>
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">Order #1</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderSupplier">Fabrikam</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderNote">This is the first sample order</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderApproved">1</pnp:DataValue>
            </pnp:DataRow>
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">Order #2</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderSupplier">PiaSys.com</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderNote">This is the second sample order</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderApproved">1</pnp:DataValue>
            </pnp:DataRow>
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">Order #3</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderTarget">marcela@marcelatest1.onmicrosoft.com</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderSupplier">Contoso</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderNote">This is the third sample order</pnp:DataValue>
              <pnp:DataValue FieldName="PnPOrderApproved">0</pnp:DataValue>
            </pnp:DataRow>
          </pnp:DataRows>
        </pnp:ListInstance>
        <pnp:ListInstance Title="Order Items" OnQuickLaunch="true" TemplateType="100" Url="Lists/OrdersItems" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" RemoveExistingContentTypes="true" ContentTypesEnabled="true">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010080DB087266A240829DF6311D1DE4BEDB" Default="true" />
          </pnp:ContentTypeBindings>
          <pnp:Views RemoveExistingViews="true">
            <View Name="{5FE34720-EE36-45A9-B80E-99A088F45F8C}" DefaultView="TRUE" MobileView="TRUE" Type="HTML" DisplayName="Order Items" Url="{site}/Lists/OrdersItems/Order Items.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=39">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="DocIcon" />
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="PnPOrderItemOrderLookup" />
                <FieldRef Name="PnPOrderItemPrice" />
                <FieldRef Name="PnPOrderItemQuantity" />
                <FieldRef Name="PnPOrderItemTotal" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off" />
              <JSLink>clienttemplates.js</JSLink>
              <XslLink Default="TRUE">main.xsl</XslLink>
              <Toolbar Type="Standard" />
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Calculated" ID="{8D4B54A8-41AF-4D41-AE31-F66A1A15F885}" StaticName="PnPOrderItemTotal" Name="PnPOrderItemTotal" DisplayName="Total" LCID="1033" ResultType="Currency" ReadOnly="TRUE" Version="1">
              <Formula>=Price*Quantity</Formula>
              <FieldRefs>
                <FieldRef Name="PnPOrderItemQuantity" />
                <FieldRef Name="PnPOrderItemPrice" />
              </FieldRefs>
            </Field>
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="5e536e99-6ea7-4a0d-95e0-122c6dd61467" Name="PnPOrderItemDescription" DisplayName="Item Description" />
            <pnp:FieldRef ID="a545f52e-3a82-4f63-9ee4-0751e12d72a9" Name="PnPOrderItemQuantity" DisplayName="Quantity" />
            <pnp:FieldRef ID="6b426432-34ec-4eda-a918-bc36109134b7" Name="PnPOrderItemPrice" DisplayName="Price" />
            <pnp:FieldRef ID="ae724011-f6a5-4dde-8e53-72b5b51dd0b4" Name="PnPOrderItemOrderLookup" DisplayName="Order" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>`

**Comment by stact** [comment]
+1 same issue here.

Cf: #229

**Comment by stact** [comment]
Here a workaround while PnPTeam is finding a solution.

I've changed the order of DataRow, by placing the user value first.
It's populating other values and at the end the user.

But this solution works only if you have one user to set, no chance with 2 because the process will stop on the first one.
```xml
<pnp:DataRow>
  <pnp:DataValue FieldName="BusinessDomainAdministrators">domain\login</pnp:DataValue>
  <pnp:DataValue FieldName="Title">HR</pnp:DataValue>
  <pnp:DataValue FieldName="BusinessDomain">-1;#HR|00dd381d-dd2b-464e-8e8c-b50a8d7e98da</pnp:DataValue>
  <pnp:DataValue FieldName="BusinessDomainEmail">hr@domain.lan</pnp:DataValue>
</pnp:DataRow>
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
