### ISSUE TITLE
Add support for metadata navigation in lists instances

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#216]
# Feature
Add support for metadata navigation in list instances.

## Recommendation
**Option 1: ** Add `<pnp:MetadataNavigation />` section with applicable configuration attributes and elements and apply the metadata navigation settings to `List.RootFolder` CSOM object

*Example*
```xml
<pnp:ListInstance Title="General Documents"
			 Description="Project Documents are stored here"
			 DocumentTemplate=""
			 OnQuickLaunch="true"
			 TemplateType="101"
			 Url="Lists/GeneralDocuments"
			 EnableVersioning="true"
			 RemoveExistingContentTypes="true">
	<pnp:ContentTypeBindings>
		<pnp:ContentTypeBinding ContentTypeID="0x01005D4F34E4BE7F4B6892AEBE088EDD215E" Default="true"/>
	</pnp:ContentTypeBindings>
	<pnp:ManagedNavigation SchemaVersion='1' IsEnabled='true' AutoIndex='true'>
		<pnp:NavigationHierarchies>
			<pnp:FolderHierarchy HideFoldersNode='false' />
			<pnp:FieldRef FieldID='{fieldid:CUST_Project}' Indexed='true'/>
		</pnp:NavigationHierarchies>
		<pnp:KeyFilters>
			<pnp:FieldRef FieldID='{fieldid:CUST_Project}' Indexed='true'/>
			<pnp:FieldRef FieldID='{fieldid:CUST_Location}' DisplayName="Project Location" />
			<pnp:FieldRef FieldID='{fieldid:Editor}' />
		</pnp:KeyFilters>
	</pnp:ManagedNavigation>
</pnp:ListInstance>
```

**Option 2:** Because managed navigation settings are applied to folders, add them to `<pnp:Folder />` element.

*Example*
```xml
<pnp:ListInstance Title="General Documents"
			 Description="Project Documents are stored here"
			 DocumentTemplate=""
			 OnQuickLaunch="true"
			 TemplateType="101"
			 Url="Lists/GeneralDocuments"
			 EnableVersioning="true"
			 RemoveExistingContentTypes="true">
	<pnp:ContentTypeBindings>
		<pnp:ContentTypeBinding ContentTypeID="0x01005D4F34E4BE7F4B6892AEBE088EDD215E" Default="true"/>
	</pnp:ContentTypeBindings>
	<pnp:Folders>
		<!-- Root folder -->
		<pnp:Folder Name="">
			<pnp:Settings>
				<pnp:ManagedNavigation SchemaVersion='1' IsEnabled='True' AutoIndex='True'>
					<pnp:NavigationHierarchies>
						<pnp:FolderHierarchy HideFoldersNode='false' />
						<pnp:FieldRef FieldID='{fieldid:CUST_Project}' Indexed='true'/>
					</pnp:NavigationHierarchies>
					<pnp:KeyFilters>
						<pnp:FieldRef FieldID='{fieldid:CUST_Project}' Indexed='true'/>
						<pnp:FieldRef FieldID='{fieldid:CUST_Location}' />
						<pnp:FieldRef FieldID='{fieldid:CUST_Editor}' />
					</pnp:KeyFilters>
				</pnp:ManagedNavigation>
			</pnp:Settings>
		</pnp:Folder>
	</pnp:Folders>
</pnp:ListInstance>
```

## References
* [How to: Deploy Metadata Navigation without using code](http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2011/02/09/how-to-deploy-metadata-navigation-without-using-code.aspx)
* [Setting List Metadata Navigation settings using CSOM](https://sharepoint.stackexchange.com/questions/144134/setting-list-metadata-navigation-settings-using-csom)

## Additional actions
* Update schema documentation
* Update schema samples

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
