### ISSUE TITLE
Samples: Organize by schema version, sites and scenarios with real-life examples

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#217]
# Current State

The PnP Provisioning projects have come a long way since the inception of the idea. Great work guys, and thank you for all of the effort many people have put into it.
And, since it is the time for the new schema version release, I feel like it can be an opportunity to do some review, cleanup and refactoring. I noticed a few things that can be improved upon. 
_Disclaimer_: These are my personal views and ideas, and I can be very wrong with my assessment :-)

* Schema files are mixed with sample files in the folder [OfficeDevPnP.ProvisioningSchema](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/OfficeDevPnP.ProvisioningSchema). Move sample files to proper location.
* The sample templates (e.g. [ProvisioningSchema-2017-05-FullSample-01.xml](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2017-05-FullSample-01.xml)) are ginormous files that try to showcase many scenarios in a single file.
* Different schema version sample files are all in the same folder [Samples](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Samples).
* The [Sample Templates](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Sample%20Templates) folder is empty. Perhaps, it should contain sample site templates (like [ProvisioningSchema-2017-05-FullSample-01.xml](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2017-05-FullSample-01.xml)), and [Samples](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Samples) folder should contain samples for relatively small scenarios.
* The [PnP Provisioning Templates](https://github.com/SharePoint/PnP-Provisioning-Templates) project appears to be abandoned and has no templates, only some concept sketches. With the project being maintained separately, it would be easy to get confused between the purpose of [Sample Templates](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Sample%20Templates), [Samples](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Samples) folders and the [PnP Provisioning Templates](https://github.com/SharePoint/PnP-Provisioning-Templates) project. Or, the samples should be moved into the [PnP Provisioning Templates](https://github.com/SharePoint/PnP-Provisioning-Templates) project (which in this case should be referenced in the [PnP-Provisioning-Schema](https://github.com/SharePoint/PnP-Provisioning-Schema) [Readme](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/README.md) file).

# Ideas for Folder Structure

Most of the time, developers are interested only in the latest version of the schema. Thus, it makes sense to have all version-related fiels in one folder.
Maintain different folders for different schema versions
* [Readme](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/README.md) file contains link to latest schema folder, schema Readme and/or documentation file(s), schema file, samples folder(s), and likns to previous version Readme files.
* Folder _2017-05_
* Folder _2016-05_
* Folder _2015-12_
* Folder _2015-08_
* Folder _2015-05_

Each folder shall contain
* _Readme_ file
* _Schema_ file
* Schema _documention_ file(s)
* _Samples_ folder
* _Sample Site Templates_ folder

# Ideas for Sample Site Templates

I would recommend to start with a few commonly used site templates that Microsoft has been using for SharePoint training, in MSDN and TechNet articles. Plus, a some common real-life site examples. 
Microsft employees and SharePoint MVPs should be able to obtain access to sample/demo sites and export the templates.

### References

* [Microsoft Office SharePoint and Office 365 Blogs](https://blogs.office.com/?filter=true&filter-product=sharepoint,office-365)
* [SharePoint 2013 blog](https://blogs.technet.microsoft.com/tothesharepoint/)
* [Overview of Search Driven Web Sites and Cross Site Publishing in Depth](https://channel9.msdn.com/Events/SharePoint-Conference/2012/SPC180)
* [Building a Modern Portal in 75 Minutes!](https://channel9.msdn.com/Events/SharePoint-Conference/2014/SPC399)
* [Creating Internet facing web sites with SharePoint on-premises or in the cloud](https://channel9.msdn.com/Events/SharePoint-Conference/2014/SPC390)

### Site Template Samples Recommendations

* [Product Catalog authoring site](https://blogs.technet.microsoft.com/tothesharepoint/2013/02/13/how-to-set-up-a-product-centric-website-in-sharepoint-server-2013/)
   * Product category term set and nested terms
   * Product catalog list
     * Fields
     * Content type
	 * List settings (index and catalog settings)
   
* [Product Catalog publishing site](https://blogs.technet.microsoft.com/tothesharepoint/2013/03/06/stage-5-connect-your-publishing-site-to-a-catalog/)
   * Cross-Site Collection Publishing feature
   * Product catalog connected site
   * Product category template
   * Product item template
   
* [Branding](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.ApplyBranding) and User Experience _(template-driven, not code-driven)_
   * [Theme](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.Themes)
   * [Logo](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.AlternateCSSAndSiteLogo)
   * [CSS](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.CustomCSS)
     * [Responsive UI](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.InjectResponsiveCSS)
   * [JavaScript](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.ClientSideRendering)
   * [JSLink](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.JSLink)
   * [Display Templates](https://github.com/SharePoint/PnP/tree/master/Samples/Branding.DisplayTemplates)
   * Custom actions
     * _Example_: Maximize page chrome (a toggle icon in Suite menu that toggles visibility of current navigation and top menu bar, thus maximizing content area)
     
* Organization/Team Site Hierarchy
  * Site directory
  * Organization structure
  * Member profile directory
  * Out of office requests
  * Team documents
  * Shared documents (search and managed metadata driven, drop-off)

* Project site
  * Project documents
  * Project members directory
  * Deliverables calendar
  * _Tasks_ list with email notification _workflow_
    * SharePoint 2013 workflow attatched to the _Tasks_ list that Sends email to task stakeholders when _task status_ changes

  
# Ideas for Sample Scenarios

* Site template package (multiple templates)
  * _Taxonomy_ template
  * _Fields_ template
  * _Content Types_ template
  * Multiple _List_ templates (reference _Fieds_, _Content Types_)
  * Standalone _List_ template (contain list-specific _Fields_, _Content Type_)
  * _Site_ template (uses [XInclude or ProvisioningTemplateFile](https://github.com/SharePoint/PnP-Sites-Core/issues/979) for _Fieds_, _Content Types_ and _Lists_)
  * Template files with different schema versions (though, not a likely real-life scenario)
  
* Taxonomy
   * Term store definitions
      * Global and site collection term stores
      * Nested terms
	  * Multiple labels
	  * Localized labels
	  * Custom sort order
	  * Navigation terms
	  * Custom Properties
	  * Term security and other properties
   * Taxonomy fields
	 * `Default` values 
	 * `Anchor` values
   * List instances with taxonomy fields
     * FieldRef display name and default value overrides

* Document Sets
   * Fields
   * Document set content type
     * Fields 
     * Allowed content types
	 * Shared fields
	 * Welcome page fields
  * Document set content type that inherits from another Document Set Content Type
    * Additional fields
    * Additional allowed content types (that shall appear before parent allowed content types)
  * List instance(s)
    * Content type bindings to document set content types
	* Removal of default content type
	* All document sets view
	* My document sets view
	* All documents view (should display shared fields to identify document set, or a link to the document set)
	* My documents view (should display shared fields to identify document set, or a link to the document set)
	* Document set welcome page view (list should not display shared welcome page fields as they appear on top of the page)
	  * Allowed content types shall appear in correct order

* Pages and Webparts
  * Script Editor webpart
    * JSOM example
  * Content Editor webpart
  * Image Viewer webpart
  * Search Box, Search Navigation, Refinement and Search Results webparts
  * Query String (URL) Filter webpart
  * HTML Form Web Part webpart
  * Organization Browser webpart
  * Site Users webpart
  * Other common SharePoint webparts

* Lists
  * JSLink on View
  * JSLink on Field
  * Managed Navigation
  
* Managed navigation
   * Global term store definition
      * Navigation term set with nested terms
   * Site collection term store definition
      * Navigation term set with pinned global navigation terms
   * `GlobalNavigation/ManagedNavigation` defintion using site collection navigation term set
   
* SharePoint 2013 workflow
   * Field definitions
   * Content type
   * List
   * [Sample workflow](https://blogs.msdn.microsoft.com/sharepointdesigner/2012/08/15/a-sample-sharepoint-2013-approval-workflow-which-can-be-recalled-by-the-initiator/)
  
 * Folders and files with metadata
   * Folders with content files
   * CSV metadata file
   * JSON metdata file

 * Localization
 
 * Security
   * Security groups
   * Permission levels
   * Security inheritance
   * Item-level security
 
* Search
  * Search pages (e.g. _Sites.aspx_)
	* Search web parts
  * Search settings
  * Search result display templates

# Other Considerations

Samples are the essential starting point to adopt the framework and a great productivity booster. 
The SIG meetings and Readme can be used to boost contribution level as more people start adoption of SharePoint PnP products.
Development of the samples can help identifying missing framework features and existing feature enhancements.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
