### ISSUE TITLE
Directories.Add not adding elements to template

### ISSUE THREAD

**Issue by tnsholding** [SharePoint/PnP-Provisioning-Schema#219]
I'm trying to programmatically modify a pnp template to add recursive folders to a document library. 

I have loaded ProvisioningTemplate into variable 'template' and have access to the object model. I'm trying to add folders and files recursively using:  
```
   OfficeDevPnP.Core.Framework.Provisioning.Model.Directory d = new OfficeDevPnP.Core.Framework.Provisioning.Model.Directory(sourceFolder, "{site}/Shared documents", true, OfficeDevPnP.Core.Framework.Provisioning.Model.FileLevel.Published, true);
template.Directories.Add(d);
```
But this doesn't seem to have the desired effect - no <pnp:Files> and <pnp:Directory> is added to the template. If I debug template.ToXML() I can verify nothing is added. 

Am I missing something? - or how would I programmatically add files to the template before applying it?

This is SharePoint 2013 OnPrem.

Best regards,
Thomas

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
