### ISSUE TITLE
DataRows KeyColumn UpdateBehavior

### ISSUE THREAD

**Issue by lccgov** [SharePoint/PnP-Provisioning-Schema#221]
Hi I have a provision template which works fine until I add  the KeyColumn and UpdateBehavior to my DataRows element. As soon as I add these I get invalid template error which trying to apply it. If I remove them again it works. Snippet below

<pnp:DataRows KeyColumn="Title" UpdateBehavior="Overwrite">
              <pnp:DataRow>
                <pnp:DataValue FieldName="Title">GoogleAnalytics</pnp:DataValue>
                <pnp:DataValue FieldName="SharedText">
                 
some text
                </pnp:DataValue>
              </pnp:DataRow>
             </pnp:DataRows>

On a side not, what should be the update value to skip?

PnP PwerShell version: SharePointPnPPowerShell2013 2.16.1706.1

Thanks

**Comment by moontear** [comment]
Same here. `KeyColumn `and `UpdateBehavior ` invalidate template.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
