### ISSUE TITLE
OneColumnSideBar wiki layout

### ISSUE THREAD

**Issue by shurick81** [SharePoint/PnP-Provisioning-Schema#224]
When try to use this wiki layout with PowerShell Apply-PnPProvisioningTemplate, I get following error:

Apply-PnPProvisioningTemplate : The provided template is not valid!
C:\GitHub\polymetal-charity\provisioninng.ps1:14 знак:1
+ Apply-PnPProvisioningTemplate .\template.xml;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

The command I use:
Apply-PnPProvisioningTemplate .\template.xml;

The template xml:
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
    <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.0.1601.0, Culture=neutral, PublicKeyToken=null" />
    <pnp:Templates ID="testsitetemplates">
        <pnp:ProvisioningTemplate ID="testportal" Version="1">
            <pnp:Pages>
                <pnp:Page Layout="OneColumnSideBar" Overwrite="true" Url="{site}/SitePages/test.aspx">
                </pnp:Page>
            </pnp:Pages>
        </pnp:ProvisioningTemplate>
    </pnp:Templates>
</pnp:Provisioning>

When I use "OneColumn" or "TwoColumns" layouts it works perfectly.

I tried with SharePoint 2013.

**Comment by joshtransient** [comment]
`<pnp:Page Layout="OneColumnSidebar" ... />`, with a lowercase "b", works. Enumeration and documentation are out of sync.

**Comment by PaoloPia** [comment]
Thanks @joshtransient for helping with this one. I will close the item as solved.
