### ISSUE TITLE
Wiki page custom layout

### ISSUE THREAD

**Issue by shurick81** [SharePoint/PnP-Provisioning-Schema#225]
What should be the wiki page layout to be able to add web parts?

I tried to use following template:
`                <pnp:Page Layout="Custom" Overwrite="true" Url="{site}/SitePages/vol.aspx">
                    <pnp:Fields>
                        <pnp:Field FieldName="WikiField"><![CDATA[​
                            <table id="layoutsTable" style="width: 100%">
                                <tbody>
                                    <tr style="vertical-align: top">
                                        <td style="width: 70%">
                                            <div class="ms-rte-layoutszone-outer" style="width: 100%">
                                                <div class="ms-rte-layoutszone-inner" style="min-height: 60px; word-wrap: break-word">
                                                </div>
                                            </div>
                                        </td>
                                        <td style="width: 30%">
                                            <div class="ms-rte-layoutszone-outer" style="width: 100%">
                                                <div class="ms-rte-layoutszone-inner" style="min-height: 60px; word-wrap: break-word">
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <span id="layoutsData" style="display: none">false,false,2</span>
                        ]]></pnp:Field>
                    </pnp:Fields>
                    <pnp:WebParts>
                        <pnp:WebPart Column="1" Row="1" Title="Content editor">
`

as a result my web part ends up inside the hidden DIV so it is not visible.
Also checked that when I apply the same layout with Set-PnPListItem, it works perfectly:

	Add-PnPWikiPage -Layout OneColumn -ServerRelativePageUrl "/sites/000004-brandingfreeteamsite/$webUrl/SitePages/$pageName"
	$wikiContent = @"
        <table id="layoutsTable" style="width: 100%">
            <tbody>
                <tr style="vertical-align: top">
                    <td style="width: 70%">
                        <div class="ms-rte-layoutszone-outer" style="width: 100%">
                            <div class="ms-rte-layoutszone-inner" style="min-height: 60px; word-wrap: break-word">
                            </div>
                        </div>
                    </td>
                    <td style="width: 30%">
                        <div class="ms-rte-layoutszone-outer" style="width: 100%">
                            <div class="ms-rte-layoutszone-inner" style="min-height: 60px; word-wrap: break-word">
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <span id="layoutsData" style="display: none">false,false,2</span>
"@;
	$item = Get-PnPListItem -List SitePages -Query "<View><Query><Where><Eq><FieldRef Name='LinkFilename'/><Value Type='Text'>$pageName</Value></Eq></Where></Query></View>"
	Set-PnPListItem -Identity $item -List SitePages -Values @{ "WikiField" = $wikiContent } | Out-Null;

    Apply-PnPProvisioningTemplate .\template.xml;

Template fragment:
                <pnp:Page Layout="OneColumn" Overwrite="false" Url="{site}/SitePages/don.aspx">
                    <pnp:WebParts>
                        <pnp:WebPart Column="1" Row="1" Title="Script Editor">

I use SharePoint 2013

**Comment by joshtransient** [comment]
Also SharePoint 2013, having a similar issue. I'd like to drop fixed HTML into one column and a "Getting started" web part into another. I tried using a custom layout with my HTML snippet in there, which works fine. The web part is on the page (at least, contents=1/the Web Parts Maintenance Page says so) and open, but hidden.

Additionally tried changing `<pnp:WebPart/>` to `<pnp:WikiPageWebPart/>`, but that throws "provided template is not valid". Not sure what's going on there, as that element is valid in the current schema.

**Comment by PaoloPia** [comment]
Hi,
Please have a look to the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml) sample template to learn how to provision sites with custom pages and web parts. I will close this item, but feel free to re-open it in case of any further need. Thanks.
