### ISSUE TITLE
Folder Content types not visible in "New" button of the document library

### ISSUE THREAD

**Issue by val0o** [SharePoint/PnP-Provisioning-Schema#226]
When you add custom "Folder" content types to a List instance, there are not "visible on new button" by default.
Is there a way to set this parameter?

**Comment by LozzieD** [comment]
Yes please, me too.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
