### ISSUE TITLE
Input string '<GUID>' is not a valid number for bulk import

### ISSUE THREAD

**Issue by shurick81** [SharePoint/PnP-Provisioning-Schema#227]
I'm trying to import documents using pnp:Directory tag:

```
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Author="Shurick81" Version="1.0" Generator="Human being :-)" />
  <pnp:Templates ID="QWERTY-IMPORT-TEMPLATECONTAINER">
    <pnp:ProvisioningTemplate ID="QWERTY-IMPORT-JFA" Version="1.0">
      <pnp:Files>
        <pnp:Directory Src=".\jfaactive" Folder="kunskap" Overwrite="true"
            Recursive="true" MetadataMappingFile=".\jfaactive.json" />
      </pnp:Files>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

Just for test, I import only one document:

`{".\\jfaactive\\67-årsreformen.doc":{"VL_KnowledgeTopic":"845c3c26-9f48-484a-bbdb-2bd5f4352ded"}`

I get this error:

```
Apply-PnPProvisioningTemplate : Input string '845c3c26-9f48-484a-bbdb-2bd5f4352ded' is not a valid number. Path '', line 1, position 36.
At line:1 char:1

```

VL_KnowledgeTopic is an internal name for managed metadata column.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
