### ISSUE TITLE
Enable Likes and Ratings on Lists

### ISSUE THREAD

**Issue by monkeymagik** [SharePoint/PnP-Provisioning-Schema#231]
There is already an extension method in PnP-Sites-Core to enable Likes and Ratings on SharePoint lists. It would be great if this could be added to the provisioning engine, so it could be included in a document library configuration.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”

**Comment by dennispg** [comment]
can we reopen this? this seems like a quick win to me...
