### ISSUE TITLE
xmlpnpschemaversion not uptodate

### ISSUE THREAD

**Issue by stact** [SharePoint/PnP-Provisioning-Schema#232]
Hello,

I'm using PowerShell to extract PnP Schema and when I'm trying to:

`Get-PnPProvisioningTemplate -Schema LATEST -Out tmp.xml`

The Schema version is 

`<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">...</pnp:Provisioning>`

Instead of the latest schema:
`<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">...</pnp:Provisioning>`

Indeed xmlpnpschemaversion  is not containing the V201705

The last schema is not working too with Apply-PnPProvisioningTemplate
There is a mistake? 

Thank you for your help!

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
