### ISSUE TITLE
Remove permission throwing an exception with new schema 2017-05

### ISSUE THREAD

**Issue by mmsharepoint** [SharePoint/PnP-Provisioning-Schema#234]
Hi!
Today I checked out the new schema 2017-05 and tried to use the remove permissions attribute.
My requirement is that members shall online have Read permissions instead of Edit on the standard Site Pages.
So apply BreakRoleInheritance with Copy=true to the library, add Read permissions (so far this works if used alone, on 2016-05 and 2017-05) and afterwards I try to remove Edit for the same group.
Here I get a typical CSOM exception:
Apply-PnPProvisioningTemplate : The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

I tested against several sites in my tenant (modern Group sites as well as classic tema site)
My short schema is:
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
	<pnp:Preferences Author="Markus Moeller" Version="1.0" Generator="Human being :-)">
		<pnp:Parameters>
			<pnp:Parameter Key="SPOMemberGroup">DEV PnP Members</pnp:Parameter>
		</pnp:Parameters>
	</pnp:Preferences>
	<pnp:Templates ID="SAMPLE-TEMPLATES">
		<pnp:ProvisioningTemplate ID="SPECIALTEAM">	
		  <pnp:Lists>
		    <pnp:ListInstance Title="Site Pages" TemplateType="119" Url="SitePages" EnableAttachments="false" RemoveExistingContentTypes="false">
			    <pnp:Security>
				    <pnp:BreakRoleInheritance CopyRoleAssignments="true" ClearSubscopes="true">
				      <pnp:RoleAssignment Principal="{parameter:SPOMemberGroup}" RoleDefinition="Read"/>
				      <pnp:RoleAssignment Principal="{parameter:SPOMemberGroup}" RoleDefinition="Edit" Remove="true"/>
				    </pnp:BreakRoleInheritance>
			    </pnp:Security>
		    </pnp:ListInstance>
		  </pnp:Lists>
		</pnp:ProvisioningTemplate>
	</pnp:Templates>
</pnp:Provisioning>

Any suggestions I am missing something or this is a bug?

**Comment by khha** [comment]
We have the same issue. It looks like it is not possible to remove an existing roleassignment.

**Comment by prawnz** [comment]
I have the same issue as well.. Seem to only error if there is a role removal

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. With the latest releases of the Provisioning Engine and Schema you can now remove RoleAssignment items. I will close this item.
