### ISSUE TITLE
In DataRows element, KeyColumn and UpdateBehavior do not work

### ISSUE THREAD

**Issue by tom-daly** [SharePoint/PnP-Provisioning-Schema#236]
http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema

Test 1
`<pnp:DataRows KeyColumn="ImageRotatorImage" UpdateBehavior="Overwrite">`
![image](https://user-images.githubusercontent.com/9259305/29233253-00b09ac0-7ebe-11e7-82a1-2b8b71bcccba.png)

Get 2 items
![image](https://user-images.githubusercontent.com/9259305/29233273-1b8dc1ba-7ebe-11e7-9762-4aec602b40e8.png)

Second run, I change the Sequence to 19 and 110.

my understanding is that the KeyColumn will find matches on the ImageRotatorImage field since I did not change it and perform the overwrite

However the results show otherwise
![image](https://user-images.githubusercontent.com/9259305/29233353-6fd19f62-7ebe-11e7-8267-f71d3454ecbd.png)

OK so maybe the encoded html inside the html-type field is not matching.. lets switch the to Sequence field. Items exist with those sequence numbers so it should make a match and then overwrite the items. In this test I've changed the ImageRotatorText field.

![image](https://user-images.githubusercontent.com/9259305/29233402-9ae41e00-7ebe-11e7-96ae-b8de1a1ed93e.png)

after running the template again. 2 more items are added - not updated.

![image](https://user-images.githubusercontent.com/9259305/29233468-e5d766ce-7ebe-11e7-84ac-499fa1e327dc.png)

I can't get this field to work as it is described.

**Comment by r998877** [comment]
Same issue here. Quite simple template:

![image](https://user-images.githubusercontent.com/20636156/31016685-0331d410-a526-11e7-8836-03d4ec42cf59.png)

When applying this template twice I get 2 items in the list with Title "LOGGIN_LIST".

**Comment by e-gallis** [comment]
Same for me...

![image](https://user-images.githubusercontent.com/32480338/31117726-25036c54-a82b-11e7-98ad-83be0f002f91.png)

Too bad it doesn't work... Could be very handing and avoid us to clear a list every time we upload the data.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
