### ISSUE TITLE
Apply-PnPProvisioning Template Access Denied Error

### ISSUE THREAD

**Issue by marcdepelteau** [SharePoint/PnP-Provisioning-Schema#237]
Hi all,

I have been working on a PowerShell Script that creates a Modern Team site by creating a group with Microsoft Graph (I'll attach the code below) and then applies a 201705 template to the site.

The template doesn't do much besides creating a page and adding a few users.

I'm not sure what's wrong in my code but I used to have the ''Modern Site Creation'' part and the ''Apply Template'' part in different script files that I would manually run one after the other and they worked fine. I decided to merge them and I have been having issues since then.

The strange part is now they don't work separately either and I keep getting the following error when applying the template:

> Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.

Earlier today, I removed the Pages section from my template and I could successfully apply it. I then re-added the Pages section and it still worked.

I tried to run the scripts another time to confirm that everything was fine, but it started throwing the error again (Access Denied).

I noticed that the user I add as the Owner shows up as the Owner, but is not present in the Owner Group. The Owner Group has ''full control'', but I suspect that my user does not have those rights.

I also noticed that for the previous modern sites I created using the same script (so I have the same pages, users, etc), I am still able to apply the template successfully, even if my user is not in the Owner Group.

**Update 1:** I created a site friday, waited over the weekend and applied the template successfully monday morning. I haven't made any changes to the site/site security/users/groups at all during this time.

**Update 2:** I did some testing today and... 

- I created a site and applied a template 5 minutes later successfully
- I created another site and have been seeing the ''access denied'' error message when applying the template for the past 30-45minutes.

**Comment by mmsharepoint** [comment]
I had a similar issue and what you can do is
a) When creating the Group with New-PnPUnifiedGroup (or similar via REST and the Graph Api) immediately add the user who connects with PnPOnline as Owner and Member
b) After creating the Group but before PnP Provisioning add the User connecting with PnPOnline as site collection admin (Advantage: The user has no access to Groups mailbox e.g.)

What's interesting about the SharePoint Groups, they get renamed after fast creation of the site.
Check the following command
Get-PnPGroup -AssociatedOwnerGroup
a) immediately after Groups creation
b) 5 mins later
c) After 1st UI access to the site ;-)

**Comment by marcdepelteau** [comment]
Thanks for the reply @mmsharepoint  ! 

I've tried your approach by executing these cmdlets:
```
#Connect to SharePoint Online
Connect-SPOService -url $AdminURL -credential $Credential
 
#Add Site collection Admin
Set-SPOUser -site $SiteCollURL -LoginName $SiteCollectionAdmin -IsSiteCollectionAdmin $True
```
After doing so, my user had access to the Advanced Permissions Settings, but was still not able to execute my Provisioning Template. 

As for the SharePoint Groups, I have noticed that at creation, the name is "Site Owners" and rapidly becomes "SiteName Owners". I haven't experienced any changes after the first UI Login..

**Comment by mmsharepoint** [comment]
That's exactly what I did and it worked for me. I had no pages inside my template since I put it all togther and provisioned directly after cretaing the group but during my testing when I provisioned ~5mins after creating in a separate step I was also able to create pages.
Did you use Set-PnPTraceLog -On to verify where exactly the provisioning breaks? Before or while applying the template to narrow down the issue?

**Comment by marcdepelteau** [comment]
@mmsharepoint Mhh I did try this and it turns out I had errors in the Security section (I was adding an extra Owner and one Administrator as well). But even after I removed the Security node, I still have an access denied error with no failing section and the following details:

```
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this resource.
At C:\Users\m.depelteau\Desktop\Site Template\Saputo Modern Site Provisioning.ps1:327 char:9
+         Apply-PnPProvisioningTemplate -Path ($siteTemplateFolder + $s ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
 
 
Detailed Provisioning Log:
 
powershell_ise.exe Information: 0 : 2017-08-23 15:57:41.1942	[OfficeDevPnP.Core]	[0]	[Information]	File Saputo Modern Template with values.xml retrieved from folder 	0ms	
powershell_ise.exe Information: 0 : 2017-08-23 15:57:41.1968	[OfficeDevPnP.Core]	[0]	[Information]	File Saputo Modern Template with values.xml retrieved from folder 	0ms	
powershell_ise.exe Information: 0 : 2017-08-23 15:57:41.2338	[Provisioning]	[12]	[Debug]	Code execution scope started	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:41.2343	[Provisioning]	[12]	[Information]	ProgressDelegate registered	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:41.2365	[Provisioning]	[12]	[Information]	MessagesDelegate registered	2ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:44.7532	[Extensibility Providers]	[12]	[Debug]	Code execution scope started	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:44.7537	[Extensibility Providers]	[12]	[Debug]	Code execution scope ended	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:44.7562	[Regional Settings]	[12]	[Debug]	Code execution scope started	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:44.8693	[Regional Settings]	[12]	[Debug]	Code execution scope ended	112ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:44.8708	[Lookup Fields]	[12]	[Debug]	Code execution scope started	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:46.1790	[Lookup Fields]	[12]	[Debug]	Code execution scope ended	1308ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:46.1795	[Files]	[12]	[Debug]	Code execution scope started	0ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:46.8074	[OfficeDevPnP.Core]	[0]	[Information]	Creating folder 'SiteAssets' under Web '/sites/MyModernSite2/'.	0ms	
powershell_ise.exe Information: 0 : 2017-08-23 15:57:46.9289	[Files]	[12]	[Debug]	Code execution scope ended	749ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
powershell_ise.exe Information: 0 : 2017-08-23 15:57:46.9294	[Provisioning]	[12]	[Debug]	Code execution scope ended	5695ms	e2b7c16d-de95-4cd3-b389-a8d7bbad36b3
```

**Comment by marcdepelteau** [comment]
It seems like you cannot apply a PnP template until your user is ''effectively'' added to the Owner Group. The user never shows up in the list under the owner group, but some time between 10 minutes and 5 hours after the group creation, he will be able to site Advanced Site Settings and other ''advanced'' options as well as apply templates. 

The only way to add the user to owner group (and see him display appropriately on screen) is to add him via a pnp-provisioning template. Both $tenant.SetSiteAdmin()   ##and Set-SPOUser -IsSiteCollectionAdmin did not work for me.

**Comment by marcdepelteau** [comment]
Bump

**Comment by mmsharepoint** [comment]
As I said, for me it worked on at least two different tenants: My personal Dev tenant and the first stage at my current customer. We decided to add the provisioning executing user only as SCA and not as an Owner once creating the Group.
Our template is not very complex as many things are not supported, that is ignored on modern sites (refer https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-sites#using-pnp-provisioning-engine-with-modern-team-sites )
So we only have:
<pnp:SiteFields>
<pnp:ContentTypes>
<pnp:Lists>
Maybe you can check with your template and if the error belongs to another specific section?

**Comment by marcdepelteau** [comment]
@mmsharepoint  I juste figured out the issue... 

The template is trying to create the folder ''Site Assets'' and doesn't have the rights to create it yet, which is why I get the ''Access Denied'' error. I tried with a different folder and it works fine...

**Comment by mmsharepoint** [comment]
In my Groups sites "Site Assets" are there by default but I didn't use a stopwatch when it's there. Maybe it lasts a bit with this fast site creation? Which might be a problem once you want to adjust that library.
But for me it works to adjust a custom content type to the Shared Documents library for instance and I am doing that "immediately" after the Groups creation ...

**Comment by marcdepelteau** [comment]
@mmsharepoint It does work for me as well in the Share Documents Library. I came to realize that the Site Assets Library is only created on the first UI access. It does not exist when I list the libraries with Get-PnPList or Get-PnPFolder -Url SiteAssets, but appears seconds after I access the site collection with the UI.

I'll either use another folder or do a web request to simulate the user browsing to that location.

**Comment by mmsharepoint** [comment]
That's really interesting @marcdepelteau 
Wonder if there is any good documentation about "What's happening when during modern site creation"?
@VesaJuvonen

**Comment by VesaJuvonen** [comment]
There's, unfortunately, no exact documentation on the what precisely happens in the context of modern site creation. This would be absolutely needed, but it's also hard to keep up to date with the constant changes in this area.

**Comment by marcdepelteau** [comment]
I see, would you (@VesaJuvonen) be able to point me in a direction to either ''simulate'' the first UI access or perhaps force the folder creation / complete setup of the Sharepoint Site using Powershell? Thank you!

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”

**Comment by SibeeshVenu** [comment]
Just share my findings here. I had a similar issue. And after I get the Term Site Admin permission from my tenant admin, everything seems to be working. I also had to enable the custom scripting, as I was getting an error as "ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped". 

Below are the steps I did finally, 

`Connect-SPOService -Url https://yoursharepoint-admin.sharepoint.com

Set-SPOsite https://yoursharepinttenant.sharepoint.com/sites/yoursharepointsite -DenyAddAndCustomizePages 0

Connect-PnPOnline https://youradmin.sharepoint.com/sites/yoursite/

Get-PnPProvisioningTemplate -Out c:/Provisioning/template.xml

Add-PnPDataRowsToProvisioningTemplate -Path c:/Provisioning/template.xml -List 'The list name' -Query '<view></view>'

Connect-PnPOnline https://youradmin.sharepoint.com/sites/yourdetinationsite

Apply-PnPProvisioningTemplate -Path C:/Provisioning/template.xml`

You can read everything in detail [here](https://medium.com/@sibeeshvenu/sharepoint-pnp-provisioning-with-data-move-your-contents-from-one-site-to-another-in-sharepoint-ed009f4a9e58).

**Comment by AjrUsf** [comment]
Notice that you need to have an account that is Term Store Administrator in order to provision the solution:
https://docs.microsoft.com/en-us/sharepoint/open-term-store-management-tool
