### ISSUE TITLE
Folders are not created in ListInstance from provisioning template

### ISSUE THREAD

**Issue by sharepointryan** [SharePoint/PnP-Provisioning-Schema#238]
I have tested and confirmed that the pnp:Folders element within a pnp:ListInstance does not provision the folders specified. An error is thrown in the PnPProvisioningJobs library:

> List does not exist.

> The page you selected contains a list that does not exist.  It may have been deleted by another user.

I am not sure what I am doing wrong, but a quick Google search tells me other users have had this problem without a resolution. What is the appropriate syntax for including one or more folders in a document library? Here is a snippet of my code for reference:
`<pnp:Folders>
			<pnp:Folder Name="Contracts" />
			<pnp:Folder Name="Deliverables" />
			<pnp:Folder Name="WorkingDocuments" />
			<pnp:Folder Name="StatusReports" />
		  </pnp:Folders>
		</pnp:ListInstance>`

Please advise as to the appropriate method for creating folders. Note my schema is 2016-05. Thanks!

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
