### ISSUE TITLE
Set envirment spefic query Sources

### ISSUE THREAD

**Issue by StefanSchoof** [SharePoint/PnP-Provisioning-Schema#239]
I want to have a Search Result Source with different Urls in the query template for the different stages. I want have `{searchTerms} path:https://mytestapp` in test and `{searchTerms} path:https://myprodapp` in production.
 I tried to use `{parameter:url}`, but it seems there is no replacement for parameters in `pnp:SearchSettings/pnp:SiteSearchSettings/SearchConfigurationSettings/SearchQueryConfigurationSettings/SearchQueryConfigurationSettings/Sources/d4p1:Source/d6p1:_QueryTemplate`.

Is there a way to get this with working?

**Comment by krunal039** [comment]
@StefanSchoof did you manage to apply path as part of searchsettings template?

**Comment by StefanSchoof** [comment]
I ended up doing a string replace in the surrounding Powershell script.
