### ISSUE TITLE
V201705 PnPProvisioningTemplate : Get AND Apply TermGroups schema error

### ISSUE THREAD

**Issue by Laul0** [SharePoint/PnP-Provisioning-Schema#242]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
By using Get-PnPProvisioningTemplate and Apply-PnPProvisioningTemplate with the new Schema V201705, the TermGroups node can be extracted and reused in another sites collection for example.

#### Observed Behavior
When I want to Apply Template, I occurred the following error :
![image](https://user-images.githubusercontent.com/15279205/29819176-ddc43052-8cbf-11e7-9e27-bf24c85ab285.png)

If I use the Get-PnPProvisioningTemplate without specify the version of schema (201605 by default), I have no error.

##### V201605
```xml
<pnp:TermGroups>
  <pnp:TermGroup Name="{sitecollectiontermgroupname}" Description="" SiteCollectionTermGroup="true">
    <pnp:TermSets>
      <pnp:TermSet Name="Provisioning" Description="">
        <pnp:Terms>
          <pnp:Term Name="English" SourceTermId="5e1af1db-f7ae-4dcf-ac80-85cd4091605f">
            <pnp:Labels>
              <pnp:Label Language="1036" Value="Français" IsDefaultForLanguage="true" />
            </pnp:Labels>
          </pnp:Term>
          <pnp:Term Name="V201705" SourceTermId="72d86758-e6f3-4002-a80c-950fc5bd1780">
            <pnp:CustomProperties>
              <pnp:Property Key="Version" Value="2.17.1708.1" />
            </pnp:CustomProperties>
          </pnp:Term>
          <pnp:Term Name="V201706" SourceTermId="5678cd2c-ce3a-4247-91ba-2b74fc4b0749">
            <pnp:CustomProperties>
              <pnp:Property Key="Version" Value="2.15.1705.0" />
            </pnp:CustomProperties>
          </pnp:Term>
        </pnp:Terms>
      </pnp:TermSet>
    </pnp:TermSets>
    <pnp:Contributors />
    <pnp:Managers />
  </pnp:TermGroup>
</pnp:TermGroups>
```

##### V201705
Note that the node `<pnp:Terms />` appear before `<pnp:Labels>` and this behavior is different compare to the previous version (maybe this is a new feature of the latest schema).

```xml
<pnp:TermGroups>
  <pnp:TermGroup Name="{sitecollectiontermgroupname}" ID="00000000-0000-0000-0000-000000000000" Description="" SiteCollectionTermGroup="true" UpdateBehavior="Overwrite">
    <pnp:TermSets>
      <pnp:TermSet Name="Provisioning" ID="00000000-0000-0000-0000-000000000000" Description="">
        <pnp:Terms>
          <pnp:Term Name="English" ID="00000000-0000-0000-0000-000000000000" SourceTermId="5e1af1db-f7ae-4dcf-ac80-85cd4091605f">
            <pnp:Terms />
            <pnp:Labels>
              <pnp:Label Language="1036" Value="Français" IsDefaultForLanguage="true" />
            </pnp:Labels>
          </pnp:Term>
          <pnp:Term Name="V201705" ID="00000000-0000-0000-0000-000000000000" SourceTermId="72d86758-e6f3-4002-a80c-950fc5bd1780">
            <pnp:Terms />
            <pnp:CustomProperties>
              <pnp:Property Key="Version" Value="2.17.1708.1" />
            </pnp:CustomProperties>
          </pnp:Term>
          <pnp:Term Name="V201706" ID="00000000-0000-0000-0000-000000000000" SourceTermId="5678cd2c-ce3a-4247-91ba-2b74fc4b0749">
            <pnp:Terms />
            <pnp:CustomProperties>
              <pnp:Property Key="Version" Value="2.15.1705.0" />
            </pnp:CustomProperties>
          </pnp:Term>
        </pnp:Terms>
      </pnp:TermSet>
    </pnp:TermSets>
  </pnp:TermGroup>
</pnp:TermGroups>
```

#### Steps to Reproduce
1. Download the latest version of PowerShell PnP module
2. Install the module
3. Enter the following command line to get the schema in V201705 and note the result :
```PowerShell
Get-PnPProvisioningTemplate -Out $path -Schema V201705 -Handlers TermGroups -IncludeSiteCollectionTermGroup
```
4. The error appear only when the TermGroups does not already exists in the Term Store of Site Collection. So, before launching the command line of the next step, delete the TermGroup or use an other sites collection
5. Enter the following command line to apply the schema V201705 and note the error message :
```PowerShell
Apply-PnPProvisioningTemplate -Path $path
```

>**Note**: I tried to reuse an schema provisioned with the V201605 and update the header in accordance with that of V201705. The result is the same.

##### Header of V201605
```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.17.1708.1, Culture=neutral, PublicKeyToken=3751622786b357c2" />
```
##### Header of V201705
```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.17.1708.1, Culture=neutral, PublicKeyToken=3751622786b357c2" />
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
