### ISSUE TITLE
Missing advanced list properties

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Provisioning-Schema#243]
Hello,

The latest version of schema lacks some advanced list features:

* `DefaultItemOpen` attribute
* `NavigateForFormsPages` attribute
* `ExcludeFromOfflineClient` attribute
* `XmlDocuments` collection
* and probably a bunch of other ones

Some of these attributes are not exposed through CSOM objects, but can be managed through SchemaXml. Implementation in the engine would be quite easy.

Is there a way to add these missing attributes ?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
