### ISSUE TITLE
In Discussion List/ Discussion Board Subject and Question are not coming in Flat view

### ISSUE THREAD

**Issue by nabhendu** [SharePoint/PnP-Provisioning-Schema#244]
Hi,
     Currently I am using OfficeDevPnP.core to provision a site in Office365. When I am provisioning the site everything is being provisioned except Discussion board or Discussion List. For these two only, body is showing in Flat view. Subject and question are not being shown over there. But when I am adding from Site content—Add an App it is coming properly. I have attached template deck also here. It would be a great help if anybody can give the solution. 
Thanks in advance.
Best Regards,
Nabhendu
[PnPProvisioningDemo.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/1273647/PnPProvisioningDemo.txt)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
