### ISSUE TITLE
FieldRefs boolean attributes should not be defaulted to false

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Provisioning-Schema#245]
Hello,

In the schema file, the `FieldRefAttributesGroup` defines both `Required` and `Hidden` yo have `false` as default value:

    <xsd:attribute name="Required" type="xsd:boolean" use="optional" default="false">
      <xsd:annotation>
        <xsd:documentation xml:lang="en">
          The Required flag for the field to bind, optional attribute.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

    <xsd:attribute name="Hidden" type="xsd:boolean" use="optional" default="false">
      <xsd:annotation>
        <xsd:documentation xml:lang="en">
          The Hidden flag for the field to bind, optional attribute.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

I think this is wrong. Default value should be `null`. In fact, hen dealing with field references in a list instance, no defining the attributes means *inherits the site content type field ref behavior*. 

With the current schema, not defining the attribute will default the value to False. It leads to weird issues when provisioning, because the pnp engine try to unhide hidden field. Not because Hidden is set to false, but because Hidden is not set.

A minimal template that can reproduce the issue is:

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.18.1709.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-FE486A81DEFD4DEEB7023AE52E252CF4">
    <pnp:ProvisioningTemplate ID="TEMPLATE-FE486A81DEFD4DEEB7023AE52E252CF4" Version="1" >
      <pnp:SiteFields>
        <Field Type="Text" DisplayName="Field to be hidden" Description="" Required="FALSE" MaxLength="255" Name="FieldToBeHidden"  ID="{613c717b-23c2-407a-bcd3-49c5d0a4783d}"  />
      </pnp:SiteFields>
      <pnp:ContentTypes>
       
        <pnp:ContentType ID="0x010060F7FC5C967C3745968A58BC8F609D78" Name="My content type" Description="" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="613c717b-23c2-407a-bcd3-49c5d0a4783d" Name="FieldToBeHidden" Hidden="true" />
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
          </pnp:FieldRefs>
        </pnp:ContentType>
     
      </pnp:ContentTypes>
      <pnp:Lists>      
        <pnp:ListInstance Title="Test List" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/OneList" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" ContentTypesEnabled="true" EnableFolderCreation="false" RemoveExistingContentTypes="true">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010060F7FC5C967C3745968A58BC8F609D78" Default="true" />
          </pnp:ContentTypeBindings>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="613c717b-23c2-407a-bcd3-49c5d0a4783d" Name="FieldToBeHidden" />
          </pnp:FieldRefs>
          <pnp:Views>
            <View Name="{CDC38FC3-E655-41BC-9852-CD2EF08AE130}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Items" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query><OrderBy><FieldRef Name="ID" /></OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="FieldToBeHidden" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
        </pnp:ListInstance>
       
      </pnp:Lists>
   
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

As a workaround, `Hidden` and `Required` attributes within lists should be explicitly set to True when the list also include the field

**Comment by stevebeauge** [comment]
After a few prototypes, I realized that the `Hidden `property is simply readonly on FieldRefs applied to a list.

So I'd suggest removing the attribute from the list fieldref attributes.

**Comment by stevebeauge** [comment]
https://blogs.msdn.microsoft.com/spblog/2013/04/27/sps2010-field-cannot-be-made-again-visible-if-defined-to-be-hidden-using-visual-studio-2010/

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
