### ISSUE TITLE
Get-PnPProvisioningTemplate generates wrong <pnp:Security> section

### ISSUE THREAD

**Issue by msgx** [SharePoint/PnP-Provisioning-Schema#246]
As I can guess, `Get-PnPProvisioningTemplate` cmdlet generates output XML with `<pnp:AdditionalAdministrators>` **after** `<pnp:AdditionalOwners>` in `<pnp:Security>` section, while XSD desribes them in opposite order in the sequence. So, `Apply-PnPProvisioningTemplate` fails with error “The provided template is not valid”.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
