### ISSUE TITLE
Provision List Field for all Content Types

### ISSUE THREAD

**Issue by NormanMann** [SharePoint/PnP-Provisioning-Schema#247]
Please support field options when provisioning a new column to a list. In particular the option to add the newly created column to all Content Types, that are already registered with that list.

The CreateField method of the ObjectListInstance class seems to always use AddFieldOptions.AddFieldInternalNameHint

        private static Field CreateField(XElement fieldElement, ListInfo listInfo, TokenParser parser, string originalFieldXml, ClientRuntimeContext context, PnPMonitoredScope scope)
        {
            Field field = null;
            fieldElement = PrepareField(fieldElement);

            var fieldXml = parser.ParseString(fieldElement.ToString(), "~sitecollection", "~site");
            if (IsFieldXmlValid(parser.ParseString(originalFieldXml), parser, context))
            {
                field = listInfo.SiteList.Fields.AddFieldAsXml(fieldXml, false, AddFieldOptions.AddFieldInternalNameHint);
                listInfo.SiteList.Context.Load(field);
                listInfo.SiteList.Context.ExecuteQueryRetry();

**Comment by stevebeauge** [comment]
maybe https://github.com/SharePoint/PnP-Sites-Core/issues/1353 is related ?

**Comment by NormanMann** [comment]
Hi @stevebeauge 
It is somewhat related. BCS fields cannot be added as site columns - only as list columns. Therefore I cannot add the column to a site content type. 

With the latest change I can still create the Field in the list but if ContentTypesEnabled=True for the list the field will never show. Athough it gets successfully created it is not added to any of the list content types.

``
               var addOptions = listInfo.TemplateList.ContentTypesEnabled
                    ? AddFieldOptions.AddFieldInternalNameHint | AddFieldOptions.AddToNoContentType
                    : AddFieldOptions.AddFieldInternalNameHint | AddFieldOptions.AddToDefaultContentType;
                field = listInfo.SiteList.Fields.AddFieldAsXml(fieldXml, false, addOptions);
                listInfo.SiteList.Context.Load(field);
                listInfo.SiteList.Context.ExecuteQueryRetry();
``

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
