### ISSUE TITLE
Additional Members Node makes the Template Invalid

### ISSUE THREAD

**Issue by marcdepelteau** [SharePoint/PnP-Provisioning-Schema#248]
Hi, 

I have tried with both 201605 and 201705 templates, but whenever I try to apply the template when the AdditionalMembers node is present, I get an error saying that the ''template is invalid''. 

The strange thing is that AdditionalOwners and AdditionalAdministrators work fine.

```
...
<pnp:Security>
    <pnp:AdditionalOwners>
        <pnp:User Name="owner@contoso.com" />
        <pnp:User Name="owner2@contoso.com" />
    </pnp:AdditionalOwners>

    <pnp:AdditionalMembers>
        <pnp:User Name="name@contoso.com" />
        <pnp:User Name="name2@contoso.com" />
    </pnp:AdditionalMembers>
</pnp:Security>
...
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
