### ISSUE TITLE
Add support for Publishing Navigation flags: AddNewPagesToNavigation and CreateFriendlyUrlsForNewPages

### ISSUE THREAD

**Issue by spcfran** [SharePoint/PnP-Provisioning-Schema#250]
I came across a requirement where I need to set these options (under `_layouts/AreaNavigationSettings.aspx`) upon provisioning a site

![image](https://user-images.githubusercontent.com/4398367/30479919-2b5a9dc2-9a0f-11e7-93cb-64fd22499245.png)

Those are boolean properties exposed on [the WebNavigationSettings](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.publishing.navigation.webnavigationsettings_members.aspx) in the client dll.

It would be nice to have a couple more elements on the schema, probably under `<pnp:Navigation>`.
The implementation should be pretty simple as well.

**Comment by VesaJuvonen** [comment]
thx Fran, we'll get this included in the future version(s).

**Comment by PaoloPia** [comment]
Thanks, it has been added to schema 201801, which is upcoming.
