### ISSUE TITLE
Updating existing Content Types with additional Fields

### ISSUE THREAD

**Issue by pitsta** [SharePoint/PnP-Provisioning-Schema#253]
Hi there, I'm trying to use the PnP Provisioning template to update existing Content Types with additional fields - it fails as soon as it discovers that the Content type exists.
i.e. Apply-PnPProvisioningTemplate : A duplicate content type "XXXXX Item" was found.
I am assuming this is by design. Or is there a way to use the provisioning engine to update content types

regards
Shaun

**Comment by parithon** [comment]
When I provision to existing content types I do not get this error. Double check the ID of the content type you're provisioning to, maybe the ID is incorrect.

**Comment by okms** [comment]
Make sure both name and ID are unique

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
