### ISSUE TITLE
 var pcomponentsToAdd = provisionsitepage.AvailableClientSideComponents(); fails while creating client side component to a modern site page

### ISSUE THREAD

**Issue by ashokaarudhan** [SharePoint/PnP-Provisioning-Schema#255]
Dear Team,

I am doing a remote provisioning of a site from WEBApi called from ASP.NET MVC application. While provisioning, my code creates a new site, adds new list to the site, activates few features, creates few modern sites pages, adds some client side components to the modern site page, associates content type to list and so on as per client requirement. If I am doing all these activities from console application everything works fine but if I do the same functionality using web application and webapi (after button click call web api), the code takes long time to execute the below code and results with timeout issue. The rest other functionalities works fine but fails only at the below code.
 
var pcomponentsToAdd = provisionsitepage.AvailableClientSideComponents();

Please advice on this. I am using PnP to provision the site. Below is the function that takes care of adding client side component to the modern page. Please advice. Below is my email id.

 try
                        {
                            var sitepagelist = site.SitePages;
                            foreach (var psitepage in site.SitePages.SitePage)
                            {
                                var provisionsitepage = provisioncontext.Web.AddClientSidePage(psitepage.Name, true);
                                provisionsitepage.AddSection(CanvasSectionTemplate.OneColumn, 2);
                                provisionsitepage.AddSection(CanvasSectionTemplate.OneColumn, 5);
                                provisionsitepage.AddSection(CanvasSectionTemplate.OneColumn, 6);
                                var pcomponentsToAdd = provisionsitepage.AvailableClientSideComponents();
                                foreach (var pwpart in psitepage.WebParts.WebPart)
                                {
                                    var pwebpart = pcomponentsToAdd.Where(s => s.Name == pwpart).FirstOrDefault();
                                    if (pwebpart != null)
                                    {
                                        int i = 0;
                                        ClientSideWebPart ccwp = new ClientSideWebPart(pwebpart) { Order = i + 1 };
                                        provisionsitepage.AddControl(ccwp, provisionsitepage.Sections[i]);
                                        i++;
                                    }
                                }
                                provisionsitepage.Save();
                            }
                        }
                        catch (Exception ex)
                        {
                            logtoFile.WriteLog(string.Format(@"Error occured in while adding modern pages types to site pages library in to the site.Error details: {0} stack strace: {1}, site url: {2}", ex.Message, ex.StackTrace, _weburl), System.Diagnostics.EventLogEntryType.Error);
                        }

Thanks,
Ashok 
ashok.aarudhan@gmail.com

**Comment by amitsaraswat83** [comment]
i am also have same requirement  using Provision Schema through XML but didn't find any solution for modern pages, client web part provisioning.

**Comment by MFSWE** [comment]
I have the same problem here: https://techcommunity.microsoft.com/t5/SharePoint-Developer/Timeout-calling-ClientSidePage-AvailableClientSideComponents/td-p/139469

I thought i solved it by writing my own solution but now i need to use the built in function and it does not work, it times out. Not even the AvailableClientSideComponents(name) works.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
