### ISSUE TITLE
Create Additional Schema to Validate Supported PnP Provisioning Engine Input

### ISSUE THREAD

**Issue by iratherscribble** [SharePoint/PnP-Provisioning-Schema#256]
Since the PnP Provisioning Engine available from the PnP Sites Core component has not implemented the full set of the Provisioning Schema, it's confusing to know what is valid and supported by the PnP Provisioning Engine and what is not.

This project's schema design is independent from the actual engine support implementation, but those utilizing PnP PowerShell to do deployments need a way to know what is supported by the engine. Those designing deployments could spend a lot of time reviewing schema information and crafting declarative deployments only to find they don't work without feedback from the PnP Provisioning Engine that something is unsupported, or from the schema validation during the execution of the engine.

There really needs to be some sort of option for keeping those that use the engine informed of what is valid _for the engine_ not just the superset specification.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
