### ISSUE TITLE
List Provision results in partial field population

### ISSUE THREAD

**Issue by dgrooms** [SharePoint/PnP-Provisioning-Schema#258]
After upgrading to 2.19.1710.1 Pnp Core, Provisioned Lists don't look correct.

One example of this is that the New Form contains only the Title field where the list has more fields that should be on the form.

Another is that creating a new item in the list doesn't set the default values. 

My example list has a Yes No field with a Default value of Yes but if I create a new item the field is Null.

This happens regardless if the field is created via java script, CSOM or using the New Form with the missing fields.

This same code worked correctly in 2.17

In these cases the list was not created with a content type, the fields were added to the OTB item.

Not sure how else to document this issue, 

Let me know if you need more information, 

Dave
[Images.zip](https://github.com/SharePoint/PnP-Provisioning-Schema/files/1396291/Images.zip)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
