### ISSUE TITLE
pnp:DataRow UpdateBehavior="Overwrite"

### ISSUE THREAD

**Issue by patrick-blanc** [SharePoint/PnP-Provisioning-Schema#259]
Hi
`
<pnp:DataRows KeyColumn="Key" UpdateBehavior="Overwrite">
  <pnp:DataRow>
    <pnp:DataValue FieldName="Key">a key</pnp:DataValue>
    <pnp:DataValue FieldName="Value">{parameter:p1}</pnp:DataValue>
  </pnp:DataRow>
</pnp:DataRows>
`

I assume that above code will "Overwrite" the list item in the list if a list item with the same KeyColumn already exists. Instead, it seems to create new entry in the list.  

It seems not... why ? Did I miss understood this overwrite parameter ?

**Comment by patrick-blanc** [comment]
![image](https://user-images.githubusercontent.com/19164315/32004064-347169d4-b9a1-11e7-9293-1692889a95f8.png)

@PaoloPia @erwinvanhunen  : Should I open this bug in PnP PowerShell repo ? 
Thanks.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
