### ISSUE TITLE
Publishing workflow definitions giving timeout error

### ISSUE THREAD

**Issue by ashavibapat** [SharePoint/PnP-Provisioning-Schema#261]
Hello,
Recently since past 10 days or so,we are getting timeout exception like below in ObjectWorkflows.ProvisionObjects.

Message : Microsoft.SharePoint.SPPrincipalManagementException: An error occurred while attempting to execute a principal management operation.  Please contact your administrator. ---> System.TimeoutException: The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: 

This worked well earlier and didn't have any issues even when we load tested with lots of requests.
The timeout is in the below code  if (templateDefinition.Published)
                                {
                                    scope.LogDebug("PublishDefinition " + templateDefinition.DisplayName);
                                    deploymentService.PublishDefinition(newDefinition.Value);//this line
                                    web.Context.ExecuteQueryRetry();
                                    
                                }
Do you have any insights on any workarounds or possible causes?
I can share my workflow template details if required.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
