### ISSUE TITLE
Ability to provision list views? 

### ISSUE THREAD

**Issue by Hulabandula** [SharePoint/PnP-Provisioning-Schema#262]
Hi! I could not find in sample (might be blind) how to provision list views e.g. a data sheet view to a list. Is this possible?

**Comment by fowl2** [comment]
Looks like this was removed in sometime between ProvisioningSchema-2015-05.xsd and [OfficeProvisioningSchema-0.5.xsd](
https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/OfficeProvisioningSchema-0.5.xsd).

`Get-PnPProvisioningTemplate` seems to generate XML of this type, even if you specified a schema version so  ¯\_(ツ)_/¯

**Comment by moontear** [comment]
The Views are unfortunately not in the samples, but you can provision them: https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2018-01.md#views - the view XML is the regular SharePoint view XML with no specific PnP markup.

**Comment by PaoloPia** [comment]
Hi,
Assuming you've got the answers you were looking for, I'm closing this item. Thanks.
