### ISSUE TITLE
pnp:NavigationNode - option to open link in new window

### ISSUE THREAD

**Issue by dgwebb** [SharePoint/PnP-Provisioning-Schema#263]
When provisioning navigation nodes via the <pnp:NavigationNode> tag, it would be great to be able to specify whether the "open link in new window" box is checked.

**Comment by PaoloPia** [comment]
Hi @dgwebb,
Thanks for your feedback. Unfortunately, we don't have this capability at CSOM/REST API level, so we cannot implement this functionality.

**Comment by sergeyz7** [comment]
@PaoloPia this is no longer the case - the current implementation of the _savemenustate_ method in the REST API seems to support the _OpenInNewWindow_ property, but the PnP provisioning schema has not caught up with that.
