### ISSUE TITLE
Webpart provisioning for newly provisioned List Instance fails

### ISSUE THREAD

**Issue by shawnadrockleonard** [SharePoint/PnP-Provisioning-Schema#269]
Upon including a webpart in the PnP:File or PnP:Page, if the List is a newly provisioned List from the collection of Instances and not an OOTB list provisioned via a Feature I receive the following standard error "The page you selected contains a list that does not exist. It may have been deleted by another user."    If i run the ApplyTemplate a 2nd time the webpart is added correctly.  This is only on the first application of the template that it fails.  I've added a post event process not an ExtensibilityHandler.   The webpart addition during a ExtensibilityHandler would also fail with the same message.   The TokenParser Web Context appears to contain the existing provisioned web context which could not find the "new" List Instance.

**Comment by shawnadrockleonard** [comment]
Updating comment to focus on the schema versus the provisioning engine functionality.    Is there a portion of the schema which will request "a-new" the collection of Tokens once the object handlers have processed a specific portion of the work?

**Comment by erwinvanhunen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1483
