### ISSUE TITLE
Not able to push .xlsx file in the <pnp:files> tag.

### ISSUE THREAD

**Issue by manishayadav** [SharePoint/PnP-Provisioning-Schema#272]
Not able to push excel files or any zip file to a sharepoint site using the <pnp:files> tag.
This is how i am using it.

        <pnp:File Overwrite="true" Src="assets/BulkFileFormat.xlsx" Folder="={site}/SiteAssets" />
        <pnp:File Overwrite="true" Src="assets/Sample.xlsx" Folder="={site}/SiteAssets" />

**Comment by PaoloPia** [comment]
Hi,
Here (https://github.com/SharePoint/sp-dev-provisioning-templates) you can find a bunch of templates that you can use to take inspiration from.
