### ISSUE TITLE
NewForm/EditForm do not show all the SharePoint Columns for Lists created from PNP Template with the Apply-PnPProvisioningTemplate Command

### ISSUE THREAD

**Issue by Arioule** [SharePoint/PnP-Provisioning-Schema#273]
Hi,

I am using  PnP PowerShell for SharePoint 2016 to add a SharePoint Custom List to a site collection: 
Here is the content of the XML Template : 

`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.20.1711.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-22D4AF33BD7E4ACC9E2B0CB7913FBF1D">
    <pnp:ProvisioningTemplate ID="TEMPLATE-22D4AF33BD7E4ACC9E2B0CB7913FBF1D" Version="1">        
      <pnp:Lists>
        
        <pnp:ListInstance Title="Workspace" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Workspace" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/Workspace/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/Workspace/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/Workspace/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=40" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{90C0DF77-C9C2-4EBD-8C81-B99074D9DA54}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Items" Url="/sites/ProvisoningSite/Lists/Workspace/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=40">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="Nom_x0020_Du_x0020_Site" />
                <FieldRef Name="Url" />
                <FieldRef Name="Description" />
                <FieldRef Name="Owner" />
                <FieldRef Name="Type_x0020_De_x0020_Site" />
                <FieldRef Name="Contributeurs" />
                <FieldRef Name="Visiteurs" />
                <FieldRef Name="Approbation" />
                <FieldRef Name="Site_x0020_Cr_x00e9__x00e9_" />
                <FieldRef Name="Statut" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off" />
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Text" DisplayName="Nom Du Site" Required="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{c6408709-f79a-44fb-87c0-a4060dce5e40}" SourceID="{{listid:Workspace}}" StaticName="Nom_x0020_Du_x0020_Site" Name="Nom_x0020_Du_x0020_Site" ColName="nvarchar3" RowOrdinal="0" Version="1" />
            <Field Type="Text" DisplayName="Url" Required="TRUE" EnforceUniqueValues="TRUE" Indexed="TRUE" MaxLength="255" ID="{007ab710-6bb9-4557-8196-e38c5144d30b}" SourceID="{{listid:Workspace}}" StaticName="Url" Name="Url" ColName="nvarchar4" RowOrdinal="0" Version="1" />
            <Field Type="Note" DisplayName="Description" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" NumLines="6" RichText="FALSE" RichTextMode="Compatible" IsolateStyles="FALSE" Sortable="FALSE" ID="{6e3d1b0d-a411-4b87-81df-8d2a9f8ae7f7}" SourceID="{{listid:Workspace}}" StaticName="Description" Name="Description" ColName="ntext2" RowOrdinal="0" Version="2" RestrictedMode="TRUE" AppendOnly="FALSE" />
            <Field Type="User" DisplayName="Owner" List="UserInfo" Required="TRUE" EnforceUniqueValues="FALSE" ShowField="Name" UserSelectionMode="PeopleOnly" UserSelectionScope="0" ID="{0c493855-2745-4e1c-8db7-9c9312d68bd5}" SourceID="{{listid:Workspace}}" StaticName="Owner" Name="Owner" ColName="int1" RowOrdinal="0" Version="1" />
            <Field Type="UserMulti" DisplayName="Contributeurs" List="UserInfo" Required="FALSE" EnforceUniqueValues="FALSE" ShowField="Name" UserSelectionMode="PeopleOnly" UserSelectionScope="0" Mult="TRUE" Sortable="FALSE" ID="{60bd4ac0-fc26-4834-9115-caa1e5e4ceb8}" SourceID="{{listid:Workspace}}" StaticName="Contributeurs" Name="Contributeurs" ColName="int2" RowOrdinal="0" Version="1" />
            <Field Type="UserMulti" DisplayName="Visiteurs" List="UserInfo" Required="FALSE" EnforceUniqueValues="FALSE" ShowField="Name" UserSelectionMode="PeopleOnly" UserSelectionScope="0" Mult="TRUE" Sortable="FALSE" ID="{8fac8ee6-84d5-4091-aa74-cf3c7b349dd3}" SourceID="{{listid:Workspace}}" StaticName="Visiteurs" Name="Visiteurs" ColName="int3" RowOrdinal="0" Version="1" />
            <Field Type="Text" DisplayName="Approbation" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{36d40e55-770f-4658-a3e1-a4bca7d05cf7}" SourceID="{{listid:Workspace}}" StaticName="Approbation" Name="Approbation" ColName="nvarchar5" RowOrdinal="0" Version="1">
              <Default>Non</Default>
            </Field>
            <Field Type="Text" DisplayName="Site Créé" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{99d6cd43-cdfb-4cb9-a9de-212683f50ff1}" SourceID="{{listid:Workspace}}" StaticName="Site_x0020_Cr_x00e9__x00e9_" Name="Site_x0020_Cr_x00e9__x00e9_" ColName="nvarchar6" RowOrdinal="0" Version="1" />
            <Field Type="Note" DisplayName="Statut" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" NumLines="6" RichText="TRUE" RichTextMode="FullHtml" IsolateStyles="TRUE" Sortable="FALSE" ID="{244fe081-40ca-4fff-8a07-fbf032f335c2}" SourceID="{{listid:Workspace}}" StaticName="Statut" Name="Statut" ColName="ntext3" RowOrdinal="0" Version="1" />
            <Field Type="Choice" DisplayName="Type De Site" Required="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="Dropdown" FillInChoice="FALSE" ID="{a21b531c-a84e-4d0d-99e0-fd9f3cc208fe}" SourceID="{{listid:Workspace}}" StaticName="Type_x0020_De_x0020_Site" Name="Type_x0020_De_x0020_Site" ColName="nvarchar7" RowOrdinal="0" Version="2">
              <Default>Public</Default>
              <CHOICES>
                <CHOICE>Public</CHOICE>
                <CHOICE>Privé</CHOICE>
              </CHOICES>
            </Field>
          </pnp:Fields>
        </pnp:ListInstance>
      </pnp:Lists>   
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>`

The list is created once the Apply-PnPProvisioningTemplate Command executed. However, when I tried to add or edit a ListItem only the title column appears in the newform (or ediform)

Here below, my list
![1png](https://user-images.githubusercontent.com/34453028/33843509-e2320e72-de9d-11e7-9010-a593cb93e8de.png)

Here below, the new form
![2](https://user-images.githubusercontent.com/34453028/33843637-3c72cdcc-de9e-11e7-85e7-200310c54772.png)

Do you know what I am doing wrong ?

Thanks for your help

Which version of the PnP-PowerShell Cmdlets are you using?

    PnP PowerShell for SharePoint 2016

What is the version of the Cmdlet module you are running?

SharePointPnPPowerShell2016             2.20.1711.0

How did you install the PnP-PowerShell Cmdlets?

    MSI Installed downloaded from GitHub

Arioule

**Comment by parithon** [comment]
It is my experience that you must add the fields to a content type, then add the content type to the list for the fields to be associated with the new/edit form. My understanding is that the PnP engine only adds the fields to the List, it does not attach the fields to the lists existing content type(s).

**Comment by Arioule** [comment]
Thanks a lot Parithon for your help

Regards
