### ISSUE TITLE
Include WriteSecurity attribute in ListInstance

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Provisioning-Schema#276]
WriteSecurity is as well as ReadSecurity [implemented in CSOM since August 2016](dev.office.com/blogs/new-sharepoint-csom-version-released-for-Office-365-august-2016-updated).

ReadSecurity is already implemented in PnP Schema for ListInstance

Please include support for WriteSecurity so that it can be handled by PnP engine

**Comment by PaoloPia** [comment]
Hi @biste5,
Thanks for your feedback. The attribute is now in the experimental branch and it will come out in May 2018. Take care.

**Comment by JulianRico** [comment]
<pnp:ListInstance Title="Favoritos" Url="Lists/favoritos" RemoveExistingContentTypes="true" ContentTypesEnabled="true" TemplateType="100" NoCrawl="true" EnableVersioning="false" ReadSecurity="???"   WriteSecurity="??????">

hi, @PaoloPia the readsecurity property is not working. What problem would it be? and when does writesecurity come out ???

**Comment by biste5** [comment]
Its implementation in the engine did come out with May 2018 release. So please confirm you're using latest release

**Comment by JulianRico** [comment]
SP 2016 standar OnPremise

**Comment by JulianRico** [comment]
question 

<pnp:Security>
        <pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false">
          <pnp:RoleAssignment Principal="userxxxxx" RoleDefinition="Full Control"/>  /// not add user --- 
        </pnp:BreakRoleInheritance>        
      </pnp:Security>  




------ full code---

 <pnp:ListInstance Title="Favoritos" Url="Lists/favoritos" ReadSecurity="11" /// no found RemoveExistingContentTypes="true" ContentTypesEnabled="true" TemplateType="100" NoCrawl="true" EnableVersioning="false">
      <pnp:ContentTypeBindings>
        <pnp:ContentTypeBinding ContentTypeID="0x0100EC1AC6A5544E457A9B4B8FF0689B1BEA" Default="true" />
      </pnp:ContentTypeBindings>
      <pnp:Security>
        <pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false">
          <pnp:RoleAssignment Principal="????????" RoleDefinition="Full Control"/>
        </pnp:BreakRoleInheritance>        
      </pnp:Security>     
     
      <pnp:Views RemoveExistingViews="true">
        <View Name="{BECED68C-5C81-4657-91E6-54E4D539380D}" DefaultView="TRUE" MobileView="TRUE" Type="HTML" DisplayName="Todos los elementos" Url="{site}/Lists/favoritos/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=39">
          <Query>
            <OrderBy>
              <FieldRef Name="ID" Ascending="false" />
            </OrderBy>
          </Query>
          <ViewFields>
            <FieldRef Name="CommonColJson"/>
            <FieldRef Name="CommonColIdUser" />
          </ViewFields>
          <RowLimit Paged="TRUE">50</RowLimit>
          <Aggregations Value="Off" />
          <JSLink>clienttemplates.js</JSLink>
          <XslLink Default="TRUE">main.xsl</XslLink>
          <Toolbar Type="Standard" />
        </View>
      </pnp:Views>
      
      
    </pnp:ListInstance>

**Comment by biste5** [comment]
Open a specific [issue in PnP-Sites-Core repo](https://github.com/SharePoint/PnP-Sites-Core/issues) reporting that you're using SP2016 On-Prem and having this issue.

You could reference
https://github.com/SharePoint/PnP-Sites-Core/commit/7f5f3abf117b79c3a7d3c216878a84f6f8b03d69

**Comment by serverless-me** [comment]
ReadSecurity and WriteSecurity on ListInstance will not work onpremises because of this lines of code in [OfficeDevPnP.Core](https://github.com/SharePoint/PnP-Sites-Core/blob/94e9248d05755bd8d096c5dcbe2658fc4c8d8e25/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs):

```
#if !ONPREMISES
, l => l.ListExperienceOptions
, l => l.ReadSecurity
, l => l.WriteSecurity
#endif
```
PnP-Sites-Core/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
