### ISSUE TITLE
Title Field Display Name

### ISSUE THREAD

**Issue by parithon** [SharePoint/PnP-Provisioning-Schema#277]
Not sure if this question has already been asked and answered, if so sorry.

Why doesn't the provision engine include the 'Title' field (and supporting fields) customizations to it's Display Name property? 

I have multiple custom tables I want to have in my provisioning template but when I use **Get-PnPProvisioningTemplate** it never includes the custom 'Title' display name properties. Therefore when I apply the template to another site, the lists 'Title' field isn't the same as the source site.

**Comment by phudt** [comment]
Hi Everyone,

I got the same issue, even I changed field title (DisplayName) in the XML file, but when I run command Apply-PnPProvisioningTemplate, site columns are created without changing Field Title (DisplayName).

Thanks,
Phu

**Comment by futsch87** [comment]
Hi, 
I got the same issue. I also changed the Display name of the title fields in several lists. Additionally i made title a not mandatory field. 

As parithon descriped the title field is not included in the ProvisioningTemplate. Can you help with this please?

**Comment by PaoloPia** [comment]
Thanks @prawnz for sharing the answer that we already shared as a "pattern". I will close this item.

**Comment by holylander** [comment]
Hi! I tried to do the same either with field "LinkFilename" and "FileLeafRef". I wanted to rename the column "name" into something else... but didnt success. Please could you suggest me some approach to solve this ? thanks!!
