### ISSUE TITLE
Reapplying a template with a calculated column results in error

### ISSUE THREAD

**Issue by parithon** [SharePoint/PnP-Provisioning-Schema#278]
When you try to re-apply an existing template it will error out when configuring the formula for a calculated column with the following error: `Apply-PnPProvisioningTemplate : The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.`

It appears when you initially apply the template it will correctly replace the following: `=[{fieldtitle:FullName}]&amp;": "&amp;[{fieldtitle:WorkZip}]` but when trying to re-apply the template it doesn't resulting in the error above.

**Comment by tomcastiglia** [comment]
I'm seeing this same behavior as well.  Any news about this?

**Comment by cerbaire** [comment]
I have the same problem! Any workaround ?

**Comment by Badajoz95** [comment]
Same issue I think: <Formula>=Title&amp;[{fieldtitle:Level_x0020_2}]&amp;[{fieldtitle:Level_x0020_3}</Formula> causes a problem when it's simple and the fields exist. It worked once but not again.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
