### ISSUE TITLE
ContentType FieldRef with hidden flag is not provisioned to List in subsite.

### ISSUE THREAD

**Issue by DeLuca-Marco** [SharePoint/PnP-Provisioning-Schema#281]
Hi SharePointPnP-Team,

This is my first Post, so I want to thank you for this cool set of tools, I love working with the provisioning engine because every time I thought "a method that does this or that, would be nice" and then I found it in your tool set. So thank you.

I don't now if it is a Bug or whether it is out of scope but I am struggling with the following issue:
I have a Site Collection with several subsites. I provision site fields, content types and also list instances to the root website as well as to the subsites. On the root website everything looks fine, site fields are provisioned correctly, content types also and my list instance contains the referenced content types as well as all fields that where referenced to the content types. So far so good. 

But on subsites something does not work as I would expect it:
My list instance on the subsites receives the content types it should, but when I look at the referenced fields to this content type I see that there are missing some fields. And I narrowed it down to field references that are flagged with hidden. Those fields are missing in my subsite's list instance. As far as I change the flag to visible the fields appear in the list instance.

Regards
Marco

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
