### ISSUE TITLE
Add a CustomAction using PnP Provisioning template - 'pnp' is an undeclared prefix error

### ISSUE THREAD

**Issue by krishnachaluvadi** [SharePoint/PnP-Provisioning-Schema#283]
Hi,
I am trying to add a custom action and below is my xml.
<pnp:CustomActions>
  <pnp:SiteCustomActions>
    <pnp:CustomAction Name="BrandingScripts" 
                           Description="Scripts for applying branding" 
                           Location="ScriptLink" 
                           Title="Branding Scripts" 
                           Sequence="100"
                           ScriptBlock="var headID = document.getElementsByTagName('head')[0]; var newScript = document.createElement('script'); newScript.type = 'text/javascript'; newScript.src = 'http://mysharepointserver.local/SiteAssets/Branding/JS/jquery-3.2.1.min.js'; headID.appendChild(newScript);"/>
</pnp:SiteCustomActions>
</pnp:CustomActions>

And I used below PnP-PowerShell command to insert the custom action
Apply-PnPProvisioningTemplate -Path C:\Code\BrandingAutomation\BrandingCustomAction.xml

I get below error:

Apply-PnPProvisioningTemplate : 'pnp' is an undeclared prefix. Line 1, position 2. At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path C:\Code\BrandingAutomation\Bran...
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], XmlException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Is there anything wrong in xml structure?
Why 'pnp' is an undeclared prefix error? 
Could some one help me in fixing the issue? 
Environment details:
SharePoint 2016 On-Premise.

**Comment by DeLuca-Marco** [comment]
Hi, I provisioned several CustomActions with the provisioning engine and it worked like a charm. Could you share your full template content, because your XML looks just like an extract. Additionally your opening tags for pnp:CustomActions and pnp:SiteCustomActions are missing < >.

**Comment by jimmywim** [comment]
I had this recently, I was trying to be clever by splitting up my template into smaller files and using an `xi:include` to pull them in.

If you do this, all your "child" template files must declare the pnp namespace on the first node in that child template.

So it has to look like this:

```
<pnp:Lists xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema">
...

```

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. If you still need support on this item, please share the whole template and we will try to do our best to support you. In the meantime, I will close this item, but feel free to re-open it attaching the template.
