### ISSUE TITLE
Get-PnPProvisioningTemplate returns "The property or field 'StringId' has not been initialized" error

### ISSUE THREAD

**Issue by arutHubfly** [SharePoint/PnP-Provisioning-Schema#284]
I tried to get the site provisioning using C# and PS scripts from Sharepoint Online site in both the cases I am getting the below error
"The property or field 'StringId' has not been initialized. It has not been requested or the request 
has not been executed. It may need to be explicitly requested."

![image](https://user-images.githubusercontent.com/25049230/35916012-f7600556-0c2e-11e8-832f-2aa93f0e7abd.png)

**Comment by JayakumarB** [comment]
I too face this issue in SharePoint Online, please let me know if any fix available.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
