### ISSUE TITLE
Add FavIcon functionality

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Provisioning-Schema#285]
Currently, the schema and core implementation are missing the favicon functionality. My understanding is that SharePoint master pages contain a `SharePoint:SPShortcutIcon` tag that renders out the default SharePoint icon `/_layouts/images/favicon.ico`. The icon file is stored in the SharePoint file hive, and there is no way to change it in a controlled manner other than modifying of the master page or implementing script-based workarounds. Modifying of master page is not the recommended approach for SharePoint Online and there is no CSOM or REST API to replace the hard-coded URL with an URL to an icon file that is relative to a site. It would be nice if you could influence SharePoint architects to either change the default location of the favicon in the out-of-the-box master pages to a location on the site, like in the `{masterpagecatog}` for example, or to add favicon functionality to SharePoint APIs so that we would be able to specify an alternative icon in the [provisioning template schema](https://github.com/SharePoint/PnP-Provisioning-Schema) and implement in the [sp-sites-core](https://github.com/SharePoint/PnP-Sites-Core) (e.g. FavIcon attribute on the WebSettings element).

___
*[Yet another SharePoint pain that kills productive time](https://sp-pains-gains.blogspot.ca/2018/02/sharepoint-favicon.html)*

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Please write this request in the https://github.com/SharePoint/sp-dev-docs/issues repo or in UserVoice. As such, I will close this item. Thanks.
