### ISSUE TITLE
Add Intellisense to Visual Studio Code for this Schema

### ISSUE THREAD

**Issue by PerOve** [SharePoint/PnP-Provisioning-Schema#286]
Intellisense for XML is not supported in Visual Studio Code. Please add support for Intellisense in Visual Studio Code, so we do not have to use other tools like the full Visual Studio installation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, we cannot manage to extend VSCode, but you can always search for a third party extension if any.
