### ISSUE TITLE
PnP Provisioning: Parameters dont work with ClientSidePage's PageName Attribute

### ISSUE THREAD

**Issue by Sohryu7** [SharePoint/PnP-Provisioning-Schema#288]
Trying the following:
Apply-PnPProvisioningTemplate -Path C:\temp5.xml -Parameters @{"CompanyName"="contoso"}

with the Template:
[...]
        <pnp:ClientSidePage PageName="{parameter:CompanyName}" PromoteAsNewsArticle="false" Overwrite="false">
[...]

Page gets created as 
CompanyName}.aspx

if i use the same token for example as navigation node in the same template, it is created correctly

PowerShell Version: 2.23.1802.0
Template Schema: 201801

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
