### ISSUE TITLE
Add support for ErrorAction attribute at handler level

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Provisioning-Schema#292]
Allow to have attribute at handler level to declare to "silently continue", or "fail", or "whatever else" in case of exception while applying a template.

**Comment by PaoloPia** [comment]
It is better to use the PowerShell flag, rather than a custom property in the schema.

**Comment by ruslanurban** [comment]
You may want to control it at  different levels. Like if an error happens in a list instance View, you may want to report an error rather than break on an error
