### ISSUE TITLE
{webname} token returns nothing.

### ISSUE THREAD

**Issue by ChitraSMudumba** [SharePoint/PnP-Provisioning-Schema#306]
Hii,

I need to  use Group email address dynamically  in the provisioning template.I saw in PnP-Site-Core available Tokens and thought of combining "{webname}@onmicrosoft.com" but webname token Returns no value.

any help would be appreciated.

Thanks,
Chitra

**Comment by PaoloPia** [comment]
Hi,
Here (https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/ProvisioningEngineTokens.md) you can find the list of supported tokens. Thanks.
