### ISSUE TITLE
Expose QuickLaunchEnabled property on WebSettings element

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#310]

**Comment by Frost-on-Web** [comment]
I come back on this idea because it would be usefull on one of my project.
Currently, we have to conjugate a PowerShell script with our templates in order to apply this parameter (and some others).
Thanks !

**Comment by PaoloPia** [comment]
This capability was added in schema 201807 and it's already there.
