### ISSUE TITLE
SharePoint Online Site provisioning slowness issue

### ISSUE THREAD

**Issue by dips23** [SharePoint/PnP-Provisioning-Schema#311]
Hi All,

We are facing following issue in provisioning SharePoint Online site through PNP.

Currently, a site is being provisioning in O365 tenant (US) through PNP Provisioning code, adding Add-ins and applying customization etc. The time required to provision sites is quite variable.Sometimes, it is done in 2-3 minutes during off time period while it takes around 15 minutes during US business hours.

However, The usual process takes around 35/40 minutes as mentioned follows ( which should have been finished within 5/10 minutes ):
SharePoint Online Site creation - 7-10  minutes
Add ins + template customization ( Root Site ) - 5/10 minutes
Branding customization ( Root Site ) - 1-2 minutes
Sub site creation - 1/2 minutes
Add ins + Template Customization ( Subsite ) - 5/10 minutes
Branding customization ( Sub site ) - 1/2 minutes

Has anyone in the past faced such a situation? Is there any best practices to follow to avoid longer time period for the deployment ? Or it could  be related O365 tenant configuration ?

Any help will be highly appreciated, Thank you in advance !

Best Regards,

**Comment by val0o** [comment]
Indeed I also notice some performance issues with PnP.
For instance, after updating the schema from 201705 to 201805, the provisioning time gets slower.
Another example, before 201805 we had csom code to remove the header of Client Side Pages. This is now part of 201805 schema but it takes quite more time than pure CSOM...

Any advice, feedbacks for these performance issues would be welcome!

**Comment by val0o** [comment]
@jansenbe @erwinvanhunen Any hints?

**Comment by Luis-Art-Guerra** [comment]
I'm currently experiencing the same issue, i published more details [here](https://sharepoint.stackexchange.com/questions/242307/applyprovisioningtemplate-function-from-sharepointpnpcoreonline-is-taking-too-mu).

Basically, my process is taking up to 90 minutes to complete provisioning (I already tested it with the C# engine and the PowerShell tool).

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
