### ISSUE TITLE
Folders are not created in ListInstance from provisioning template

### ISSUE THREAD

**Issue by stephenhuen** [SharePoint/PnP-Provisioning-Schema#314]
Same error is in #238. PowerShell is fine but CSOM fails with same error

> Microsoft.SharePoint.Client.ServerException
>   HResult=0x80131500
>   Message=List does not exist.
> 
> The page you selected contains a list that does not exist.  It may have been deleted by another user.

The template xml is like:

`          <pnp:Folders>
            <pnp:Folder Name="11. PROJECT CONTROLS"/>
          </pnp:Folders>
        </pnp:ListInstance>`

As a workaround I tried to use PnP:Directory but it seems to create folders only if they contain files. My structure are all empty folders. Please advise. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
