### ISSUE TITLE
Unable to extract "ApplicationLifecycleManagement" handler for sub site

### ISSUE THREAD

**Issue by anupam-ujjwal** [SharePoint/PnP-Provisioning-Schema#316]
I connected to a sub site and run the below command,

Get-PnPProvisioningTemplate -Out <Path> -Handlers ApplicationLifecycleManagement

It generated a blank template. The same command works if used for root site.

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.26.1805.1, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-EA5393531E36430789188BBB7C73B673">
    <pnp:ProvisioningTemplate ID="TEMPLATE-EA5393531E36430789188BBB7C73B673" Version="1" BaseSiteTemplate="CMSPUBLISHING#0" Scope="Web" />
  </pnp:Templates>
</pnp:Provisioning>

Not : There is already some SPFX components installed.

**Comment by wpo365** [comment]
Did you ever find a solution this? It also seems not possible to manually create such a provisioning template and then apply it successfully to a sub site. The ApplicationLifecycleManagement node seems to be ignored.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
