### ISSUE TITLE
Apply-PnPProvisioningTemplate Access Denied

### ISSUE THREAD

**Issue by hernanborda** [SharePoint/PnP-Provisioning-Schema#317]
Hi, I need deploy a template from DEV envieroment to PRD, when i test the import into TST envieroment, the process is successfull but when the same template is importe en PRD, the follow error appers

![image](https://user-images.githubusercontent.com/39628347/40553402-86b1ecc6-6010-11e8-9fef-b5d8f7d288b2.png)

and in tracelog file the error is

![image](https://user-images.githubusercontent.com/39628347/40553596-22964a38-6011-11e8-8acc-f2127c61c00d.png)

the PRD enverioment is a root site collection

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
