### ISSUE TITLE
Promoted Lists creation failed - New-PnPList : Invalid list template

### ISSUE THREAD

**Issue by roroinlondon** [SharePoint/PnP-Provisioning-Schema#318]
Hello,

I am trying to create a new Promoted Links list with the following command:
`New-PnPList -Title "Test" -Url "Lists/Test" -Template PromotedLinks -EnableVersioning`

I get this error message:
> New-PnPList : Invalid list template.
> At line:1 char:1
> + New-PnPList -Title "Test" -Url "Test" -Template PromotedLinks -Enable ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [New-PnPList], ServerException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Lists.NewList
 
It used to work.
I recently updated the version of PnPPowerShell to '2.26.1805.1'.

Could someone help me with this issue please?

**Comment by Lysakers** [comment]
Having the same problem, any news or workarounds for this issue?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is a PowerShell related issue/request. Could you please insert this item, if still needed, in the PnP-PowerShell repository (https://github.com/SharePoint/PnP-PowerShell/issues/)? Thanks. I will close this item, because out of context.
