### ISSUE TITLE
List data sheet view is not visible in view selector menu using PnP-Provsioning

### ISSUE THREAD

**Issue by arskselva** [SharePoint/PnP-Provisioning-Schema#320]
The **data sheet view** is not visible in **view selector menu** when create a view using PnP XML provisioning. The same issue was occurring when creating data sheet view using CSOM. But which was fixed with below code changes. So please help to fix this issue via PnP XML provisioning.
**viewObject.ViewTypeKind = ViewType.Grid | ViewType.Html;**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
