### ISSUE TITLE
WebApiPermissions on Graph are not set on the Tenant

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/PnP-Provisioning-Schema#321]
I was very pleased to see that the webApiPermissions can now be set into the pnp template but infortunatly, i am not able to make this work...

Below is the template i'm trying to use...
Maybe i'm doing soething wrong but my api interface stays empty and i got no error from the power shell command
I use the following commands to apply the template : 
Connect-PnPOnline -Url https://<MY_TENANT>-admin.sharepoint.com
Apply-PnPProvisioningTemplate -Path <My_TEMPLATE>.xml

The term sets are created but the permissions are not set...
My Module version is : 2.26.1805.1

`<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Version="1.0"></pnp:Preferences>
  <pnp:Tenant>
    <pnp:WebApiPermissions>
      
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="Mail.Read"/>
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="User.Read"/>
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="User.ReadBasic.All"/>
      
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="Tasks.Read"/>
      
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="Directory.Read.All"/>
      
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="Calendars.Read"/>
      <pnp:WebApiPermission Resource="Microsoft.Graph" Scope="MailboxSettings.ReadWrite"/>
    </pnp:WebApiPermissions>
  </pnp:Tenant>
   <pnp:Templates ID="Container_Taxonomies">
    <pnp:ProvisioningTemplate ID="Taxonomies" Version="1">
      <pnp:TermGroups>
        <pnp:TermGroup Name="Taxonomies_Portail_Eden" ID="7cb0ee23-4f1c-4d83-842c-5f4e6705a60e" UpdateBehavior="Overwrite">
          <pnp:TermSets>
            <pnp:TermSet Name="Processus" ID="db8db6cd-db8f-4015-837a-f991f592f83b" Language="1036" IsOpenForTermCreation="true">
              <pnp:Terms>
                <pnp:Term Name="PM10" IsAvailableForTagging="false" Language="1036">
                  <pnp:Terms>
                    <pnp:Term Name="PM103" IsAvailableForTagging="false" Language="1036"></pnp:Term>
                  </pnp:Terms>
                </pnp:Term>
              </pnp:Terms>
            </pnp:TermSet>
            <pnp:TermSet Name="Thématiques" ID="02ff2b7e-3498-4f63-898d-40f70e4cdbe5" Language="1036" IsOpenForTermCreation="true">
              <pnp:Terms>
                <pnp:Term Name="RH" IsAvailableForTagging="false" Language="1036">
                </pnp:Term>
              </pnp:Terms>
            </pnp:TermSet>
          </pnp:TermSets>
        </pnp:TermGroup>
      </pnp:TermGroups>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
  
</pnp:Provisioning>`

**Comment by PaoloPia** [comment]
Please, have a look at this sample template (https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml) to see how to work with custom permissions. Thanks.
