### ISSUE TITLE
Better support to provision a list based on an stp/list definion

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Provisioning-Schema#322]
If you export multiple lists as stp's, they (can) end up with the same feature id and typeid. This means if you create a template

```xml
<pnp:Lists>
	<pnp:ListInstance Title="Foo" TemplateType="100" Url="Lists/Foo" TemplateFeatureID="00BFEA71-DE22-43B2-A848-C05709900100" />
	<pnp:ListInstance Title="Bar" TemplateType="100" Url="Lists/Bar" TemplateFeatureID="00BFEA71-DE22-43B2-A848-C05709900100" />
</pnp:Lists>
```

Each of this lists could refer to different stp's in `_catalogs/lt`, but they would use the same list definition. List definitions also has an `InternalName` which is the name of the stp, so it would be ideal to somehow be able to specify `pnp:ListInsance` based on the internal name instead of the featureid perhaps? Or a combination.

Suggestion is an optional `TemplateInternalName` attribute, which can be used to filter out the correct stp in the provisioning engine.

**Comment by wobba** [comment]
This issue relates to https://github.com/SharePoint/PnP-Sites-Core/issues/1806

**Comment by wobba** [comment]
@PaoloPia had any time to consider this into the schema so we can add it to core? :)

**Comment by wobba** [comment]
Pinging @PaoloPia @erwinvanhunen. Edge case but should be easy to get into the schema so we can solve the stp issue once and for all.

**Comment by wobba** [comment]
Ping

**Comment by PaoloPia** [comment]
Hi @wobba,
It's been added to schema 201903. As soon as the schema will be in Core ... we will accept PRs to the described capability ;-) ...
