### ISSUE TITLE
PnP SP2016 When using pnp:security, the process is blocked

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/PnP-Provisioning-Schema#324]
Any pnp security code seems to block the process

### Code in the template
```
<pnp:Security BreakRoleInheritance="true" CopyRoleAssignments="false" ClearSubscopes="true">
        <pnp:SiteGroups>
          <pnp:SiteGroup Title="{sitename} Owners" Description="Use this group to grant people full control permissions to the SharePoint site: test" Owner="{sitename} Owners" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false" RequestToJoinLeaveEmailSetting="jeff.angama@monacoinformatiqueservice.mc">
            <pnp:Members>
              <pnp:User Name="i:0#.w|ddd\ccc" />
            </pnp:Members>
          </pnp:SiteGroup>
          <pnp:SiteGroup Title="{sitename} Members" Description="Use this group to grant people contribute permissions to the SharePoint site: test" Owner="{sitename} Owners" AllowMembersEditMembership="true" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false" RequestToJoinLeaveEmailSetting="jeff.angama@monacoinformatiqueservice.mc">
            <pnp:Members>
              <pnp:User Name="i:0#.w|ddd\aaa" />
              <pnp:User Name="i:0#.w|ddd\bbb" />
            </pnp:Members>
          </pnp:SiteGroup>
```

### Output
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

 Applying template to https://siteurl.mc/sites/test3
    Site Security
    [ooooooooooooooooooooooooooo                                                                                 ]

https://siteurl.mc/sites/test3
Connecting to https://siteurl.mc/sites/test3...
Site context obtained
Creating PnP template...
powershell.exe Information: 0 : 2018-06-21 17:35:42.6661        [OfficeDevPnP.Core]     [0]     [Information]   File PnpTemplateClientSite_v1.1.xml retrieved from folder       0ms
powershell.exe Information: 0 : 2018-06-21 17:35:42.6691        [OfficeDevPnP.Core]     [0]     [Information]   File PnpTemplateClientSite_v1.1.xml retrieved from folder       0ms
powershell.exe Information: 0 : 2018-06-21 17:35:43.5762        [Provisioning]  [10]    [Debug] Code execution scope started    0ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:43.5782        [Provisioning]  [10]    [Information]   ProgressDelegate registered     2ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:43.5782        [Provisioning]  [10]    [Information]   MessagesDelegate registered     3ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:45.9244        [Extensibility Providers]       [10]    [Debug] Code execution scope started    11ms    6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:45.9254        [Extensibility Providers]       [10]    [Debug] Code execution scope ended      13ms    6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:45.9454        [Regional Settings]     [10]    [Debug] Code execution scope started    0ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:46.0244        [Regional Settings]     [10]    [Debug] Code execution scope ended      78ms    6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:46.0424        [Supported UI Languages]        [10]    [Debug] Code execution scope started    0ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:46.5100        [Supported UI Languages]        [10]    [Debug] Code execution scope ended      468ms   6320a3b1-6135-4d73-a22b-fa59e461f4b0
powershell.exe Information: 0 : 2018-06-21 17:35:46.5590        [Site Security] [10]    [Debug] Code execution scope started    0ms     6320a3b1-6135-4d73-a22b-fa59e461f4b0

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
