### ISSUE TITLE
CanvasColumn element implementation

### ISSUE THREAD

**Issue by James-Randal** [SharePoint/PnP-Provisioning-Schema#326]
The schema refers to CanvasColumn element, however there does not seem to be any reference to what its parent should be. Upon inspecting code I cannot find an implementation for it.

Could someone please advise the status of this element and how can be used.

I have a ClientSidePage that utilizes 1 section with 6 columns (factor is 2 for each). There is one webpart per column.

When extracting the template, the canvas controls are all placed into 1 Section->Controls-> N CanvasControl. Upon reapplying the template it fails (Index Bounds) because the Column attribute the CanvasControl stills reflects the column based on a 6 column grid. 

It is my interpretation from the schema documentation that CanvasColumn would be able to correct this.

**Comment by James-Randal** [comment]
Bump

**Comment by jansenbe** [comment]
@James-Randal : can you share the template that failed?

CanvasControl needs to live inside the controls collection.

```XML
<pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="SamplePage" PromoteAsNewsArticle="true" Overwrite="true" Publish="true" Layout="Article" EnableComments="true">
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl
                  WebPartType="Image"
                  CustomWebPartName="..."
                  JsonControlData="{}"
                  ControlId="0eaba53f-55d8-44b5-9f7c-61301c7f1e0e"
                  Order="1">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="" Value="{token}" />
                  </pnp:CanvasControlProperties>
                </pnp:CanvasControl>
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
```

**Comment by PaoloPia** [comment]
Hi @James-Randal,
I don't see any answer from you, and it looks like Bert gave you proper advice. Thus, I will close this item. Feel free to re-open it if still needed.
