### ISSUE TITLE
Apply-PnPProvisioningTemplate : The provided template is not valid!

### ISSUE THREAD

**Issue by jainmilan002** [SharePoint/PnP-Provisioning-Schema#327]
Provisioning Template 
 
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.27.1806.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />

 <pnp:Templates ID="CONTAINER-TEMPLATE-E5A0C5AE3C724A0182536976D0F2EDCF">
    <pnp:ProvisioningTemplate ID="TEMPLATE-E5A0C5AE3C724A0182536976D0F2EDCF" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Sunday" FirstWeekOfYear="0" LocaleId="1033" ShowWeeks="false" Time24="false" TimeZone="13" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />

      <pnp:SiteFields>
        <Field
           ID="{2F78536A-C227-4CF4-AC2C-B8060688E7D4}"
           StaticName="c775af9c64a940dd86e5b8324b0c8030"
           Name="c775af9c64a940dd86e5b8324b0c8030"
           DisplayName="Author_0"
           Type="Note"
           ShowInViewForms="FALSE"
           Required="FALSE"
           Hidden="TRUE"
           CanToggleHidden="TRUE"
           SourceID="http://schemas.microsoft.com/sharepoint/v3"
        />
        <Field Type="TaxonomyFieldTypeMulti" DisplayName="Author" Name="Author0" StaticName="Author0" ShowField="Term1031"
             Description="Author"  Required="FALSE" EnforceUniqueValues="FALSE" Group="EC Meeting Columns"
               ID="{23B8D482-0C33-441A-A62A-0D1197CC6980}" Sortable ="FALSE">
          <Customization>
            <ArrayOfProperty>
              <Property>
                <Name>SspId</Name>
                <Value xmlns:q1="http://www.w3.org/2001/XMLSchema" p4:type="q1:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">08ee6db1-67e1-4668-972a-86b01ed1577b</Value>
              </Property>
              <Property>
                <Name>TermSetId</Name>
                <Value xmlns:q2="http://www.w3.org/2001/XMLSchema" p4:type="q2:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">F39CFCD1-4A4C-496A-A247-98B703647E87</Value>
              </Property>
              <Property>
                <Name>TextField</Name>
                <Value xmlns:q6="http://www.w3.org/2001/XMLSchema" p4:type="q6:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">2F78536A-C227-4CF4-AC2C-B8060688E7D4</Value>
              </Property>
              <Property>
                <Name>IsPathRendered</Name>
                <Value xmlns:q7="http://www.w3.org/2001/XMLSchema" p4:type="q7:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
              </Property>
              <Property>
                <Name>IsKeyword</Name>
                <Value xmlns:q8="http://www.w3.org/2001/XMLSchema" p4:type="q8:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
              </Property>
            </ArrayOfProperty>
          </Customization>
        </Field>
      </pnp:SiteFields>

      <pnp:ContentTypes>
        <pnp:ContentType ID="0x010100FFBB0F19A0BF44D786F0C84014EC90E7"
            Name="EC Meeting Content Type" Description="EC Meeting Content Type Desc" Group="EC Meeting CT">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="23B8D482-0C33-441A-A62A-0D1197CC6980" Name="Author0" Required="FASLE" />
          </pnp:FieldRefs>
        </pnp:ContentType>
      </pnp:ContentTypes>
      
      <pnp:TermGroups>
        <pnp:TermGroup Name="AuthorGroup" ID="1475E61C-EA43-426F-8A0B-A0F7D07C960A">
          <pnp:TermSets>
            <pnp:TermSet Name="Author" ID="F39CFCD1-4A4C-496A-A247-98B703647E87" Language="1031">
              <pnp:Terms>
                <pnp:Term Name="Bendig, Dr. Tim - Lenze" ID="D5AE2AD3-92CE-4840-B53A-D2BF3E279655"></pnp:Term>
                <pnp:Term Name="Cesaretti, Davide - SAG" ID="55BBDCD9-4DA4-4FFB-8EB0-73F721DA229A"></pnp:Term>
                <pnp:Term Name="Chan, Gary - Lenze" ID="0753B1E6-9F69-4F91-98EC-940DC063A3EF"></pnp:Term>
                <pnp:Term Name="Cord, Dr. Thomas - Lenze" ID="6B48EDB6-7762-4F80-AF85-EC628D9BA4EE"></pnp:Term>
              </pnp:Terms>
            </pnp:TermSet>
          </pnp:TermSets>
        </pnp:TermGroup>
      </pnp:TermGroups>
      
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

When i want to apply above template while creating new site.
New ""Team Site" created successfully and while applying template it gives me --> Template is not valid

here is PnP Command 
$site = New-PnPSite -Type TeamSite  -Title $siteTitle -Alias $siteUrl

Connect-PnPOnline -Url $siteCollUrl -Credentials $cred;

$web = Get-PnPWeb

#apply Template
Write-Output $("Applying Pnp Template [{0}] to site [{1} ({2})])..." -f $path,$web.Title,$web.Url);
Apply-PnPProvisioningTemplate -Web $web -Path $path;

Thanks for the Help in Advance,

Milan Jain

**Comment by ruslanurban** [comment]
It looks like you exported the template from an existing site. Did you make any changes manually? I had experienced invalid XML in exported templates in the past in the webpart zone attribute, but it looks like you are not using it...
Try to validate the XML against PnP schema (e.g. using XML tools plugin in Notepad++).

**Comment by Frost-on-Web** [comment]
My advice to debug this kind of annoying thing : use "dichotomy" method... remove some parts of your code, mostly criticals if possible, and try again... if the error occured yet, remove some other parts and repeat...
When @PnP-Provisioning-Schema would learn to have good error messages, we will live in a happy world !

**Comment by PaoloPia** [comment]
Hi,
I would suggest you to validate the XML with the corresponding XSD schema. You should be able to figure out what the issue is.
