### ISSUE TITLE
{listurl} token stopped working?

### ISSUE THREAD

**Issue by awdhaan** [SharePoint/PnP-Provisioning-Schema#328]
I have succesfully provisioned sites that last couple of days, using the token {listurl} for the url of a library instance. Since this morning (27 July 2018) this seemed to stop working for 2 completely separate customers.

Basic details:
- SharePoint Online;
- Provisioning site is a modern teamsite (GROUP#0);
- OfficeDevPnP PowerShell (2.28.1807.0) was used for provisioning;
- The template xml validated against the 2018-05 schema;
- I'm using the url in various places. the complete xml is attached.

The following template part was used to provision the lists:
<pnp:ListInstance Title="Documents" TemplateType="101" Url="{listurl:Documents}" EnableFolderCreation="false">
	<pnp:ContentTypeBindings>
		<pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true" />
		<pnp:ContentTypeBinding ContentTypeID="0x0120" />
	</pnp:ContentTypeBindings>
	<pnp:Views>
		<View Name="{8F1CF5F4-0443-4528-9653-7EDF7C8C3AF7}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="{site}/{listurl:Documents}/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=44">
			<Query>
				<OrderBy>
					<FieldRef Name="FileLeafRef" />
				</OrderBy>
			</Query>
			<ViewFields>
				<FieldRef Name="DocIcon" />
				<FieldRef Name="LinkFilename" />
				<FieldRef Name="Modified" />
				<FieldRef Name="Editor" />
				<FieldRef Name="DocumentType" />
				<FieldRef Name="ActiveNonActive" />
			</ViewFields>
			<RowLimit Paged="TRUE">30</RowLimit>
			<JSLink>clienttemplates.js</JSLink>
		</View>
	</pnp:Views>
	<pnp:FieldRefs>
		<pnp:FieldRef ID="e5d89314-6a19-4e56-ac70-55019056bde1" Name="g3d1c5caa9df481297677773234a8417" Hidden="true" DisplayName="DocumentType_0" />
		<pnp:FieldRef ID="03d1c5ca-a9df-4812-9767-7773234a8417" Name="DocumentType" Required="true" DisplayName="Document type" />
		<pnp:FieldRef ID="2724060f-850c-4c3a-a003-009662c8c280" Name="ActiveNonActive" DisplayName="Active/Non-active" />
	</pnp:FieldRefs>
</pnp:ListInstance>

The provisioning breaks with the following error message:
The name of the file or folder contains characters that are not allowed. Use a different name.
When hardcoding the url element of the listinstance, the issue doesn't occur.

Apparently this problem only occurs when the team site is created in a specific language as the url is "Shared Documents" for 1033 and "Gedeelde documenten" for 1043.

**Comment by awdhaan** [comment]
[siteconfig.xml.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/2236181/siteconfig.xml.txt)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
