### ISSUE TITLE
Add ScriptLink support

### ISSUE THREAD

**Issue by Frost-on-Web** [SharePoint/PnP-Provisioning-Schema#332]
[Next version idea]
I wish have support to ScriptLink integration like this kind of stuff : 

```
Add-PnPJavaScriptLink -Name React -Url "https://cdnjs.cloudflare.com/ajax/libs/react/15.6.2/react.js" -Sequence 100
Add-PnPJavaScriptLink -Name ReactDom -Url "https://cdnjs.cloudflare.com/ajax/libs/react-dom/15.6.2/react-dom.js" -Sequence 200
Add-PnPJavaScriptLink -Name PolyfillPromise -Url "https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js" -Sequence 300
Add-PnPJavaScriptLink -Name HeaderFooter -Url "$RootUrl/Style%20Library/Scripts/bundleClassicHeaderFooter.js" -Sequence 400
```

It's very usefull when we want integrate Modern and Classic UI Extension (like Header or Footer).
Currently, I add my scripts with this PnP-PowerShell commands.

**Comment by phawrylak** [comment]
It's already there. You can use `<pnp:CustomActions>` element for this.

**Comment by Frost-on-Web** [comment]
Hi,
I will test that nextly.
It seemed to me that CustomActions and JavaScriptLink was two different things.
Thanks for you reply.

**Comment by jansenbe** [comment]
Answered by @phawrylak , closing now
