### ISSUE TITLE
Taxonomy Term Update Functionality

### ISSUE THREAD

**Issue by venkatkonjeti** [SharePoint/PnP-Provisioning-Schema#333]
The updating taxonomy terms using Import-PnPTermGroupFromXml with XML/Path parameter is not working. I am not sure it is not supporting or not working.

Here is an example

I have imported a term using this command. The xml as follows
`<pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:TermGroup Name="Group Name" ID="a5f1f831-cfd8-4a69-9bd8-c0ba7f8a36b2" Description="" UpdateBehavior="Overwrite">
    <pnp:TermSets>
      <pnp:TermSet Name="Term Set name" ID="4048c56a-0ba7-4f0d-bc2a-4aaf5f48348c" Description="">
        <pnp:Terms>
          <pnp:Term Name="Client" ID="4681f229-e9d1-4d83-af9a-56da7a371090" Owner="owner" Description="" SourceTermId="4681f229-e9d1-4d83-af9a-56da7a371090">
            <pnp:Terms />
		   </pnp:Term>
        </pnp:Terms>
      </pnp:TermSet>
    </pnp:TermSets>
  </pnp:TermGroup>
</pnp:TermGroups>`

I want to deprecate this term(In my case I have 50000 records). So, i have modified the script by adding a property IsDeprecated="true" to term XML as follows.

`<pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:TermGroup Name="Group Name" ID="a5f1f831-cfd8-4a69-9bd8-c0ba7f8a36b2" Description="" UpdateBehavior="Overwrite">
    <pnp:TermSets>
      <pnp:TermSet Name="Term Set name" ID="4048c56a-0ba7-4f0d-bc2a-4aaf5f48348c" Description="">
        <pnp:Terms>
          <pnp:Term Name="Client" ID="4681f229-e9d1-4d83-af9a-56da7a371090" Owner="owner" Description="" IsDeprecated="true" SourceTermId="4681f229-e9d1-4d83-af9a-56da7a371090">
            <pnp:Terms />
		   </pnp:Term>
        </pnp:Terms>
      </pnp:TermSet>
    </pnp:TermSets>
  </pnp:TermGroup>
</pnp:TermGroups>`

This doesn't deprecating the term.

In the schema I dont see an option to tell the term to update.

Can someone please help me on this.

**Comment by PaoloPia** [comment]
Hi,
The @IsDeprecated attribute in the schema is supported by the engine. I would suggest you to try again with the latest version of the engine. In case of any further problem, feel free to re-open this issue.
