### ISSUE TITLE
Webpart installed and added in the same template is not really added

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/PnP-Provisioning-Schema#334]
Hi

Just a small issue we ran into : 
When we install a custom webpart through pnp:ApplicationLifecycleManagement
<pnp:ApplicationLifecycleManagement>
    <pnp:Apps>
      <pnp:App Action="Install" AppId="{parameter:myWebpart}"/>
    </pnp:Apps>
</pnp:ApplicationLifecycleManagement>

When we try to add the webpart into a ClientSidePage in the same template, the webpart is not really added to the page.

However, if we split this in two dfferent templates (one with the pnp:ApplicationLifecycleManagement then another with the clientSidepage) then it works...

I did not see this in the documentation so is it a known limitation?

Thanks

**Comment by PaoloPia** [comment]
Hi,
I would suggest you to have a look at SP Starter Kit sample solution (https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml), where we install app packages and create client-side pages with webparts through a unique template. You can take inspiration from there. Thanks.
