### ISSUE TITLE
Get-PnPProvisioningTemplate -Schema LATEST Returns  Generates 2018/05

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/PnP-Provisioning-Schema#336]
The command
`Get-PnPProvisioningTemplate -Schema LATEST `

Generates the following
```

<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.1.1809.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
```

I was expecting 2018/07 in the xmlns.

**Comment by PaoloPia** [comment]
The output depends on the version of PowerShell that you're using. Consider also that usually the schema is released a couple of months before the engine supports it. Thus, please update it to the latest one. I will close the item in the meantime.
