### ISSUE TITLE
Apply-PnPProvisioningTemplate - Error: "Access denied. You do not have permission to perform this action or access this resource."

### ISSUE THREAD

**Issue by tomcastiglia** [SharePoint/PnP-Provisioning-Schema#337]
I have been seeing this Access Denied error frequently when running Apply-PnPProvisioningTemplate with most provisioning templates.  From what I can tell, this error only occurs after all aspects of the template have been successfully executed.  So essentially the behavior of the template seems to work properly with the exception of this error being displayed at the end.  I have only reproduced this when running my PowerShell scripts from VS Code.  When executing the Powershell from Azure Functions or Azure Automation (using the same templates), I have not seen this.

I've uploaded a sample of a template that causes this, but it seems like now I see this error with almost every template.  I am connecting with a user that is an Owner of the group (along with being a Global Admin).

[BEPRJ-Fields.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/2426622/BEPRJ-Fields.txt)

**Comment by tomcastiglia** [comment]
Ok, I think I identified the cause of this.  In my PowerShell, if I have the statement for "Import-Module SharePointPnPPowerShellOnline" at the top, this error goes away.  When I had this statement commented out, the Apply-PnPProvisioningTemplate cmdlet would still run, but cause this error after the template was applied.  I'm curious if this is standard behavior.

**Comment by PaoloPia** [comment]
RIP my friend! :-(
