### ISSUE TITLE
Include Custom Search Navigation in Model

### ISSUE THREAD

**Issue by mkorek** [SharePoint/PnP-Provisioning-Schema#338]
Hello,

When applying a model to a newly created site, it adds the custom top nav and side nav to the newly created site but am not able to apply the custom search nav from the model site.  To go around this I use the following PnP-PowerShell command to update the new sites search navigation:

Add-PnPNavigationNode **-Location SearchNav** -Title $blah -Url $blahh

So, I was wondering if you could extend the provisioning schema to include search navigation as well?

Thanks,
Matt

**Comment by PaoloPia** [comment]
I've just added a new element in schema 201903 for the Search Navigation settings. Thanks.
