### ISSUE TITLE
"A term set already exists with the name specified." error 

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/PnP-Provisioning-Schema#340]
This is the XML we are using
```
<pnp:TermGroup Name="{sitecollectiontermgroupname}" ID="00000000-0000-0000-0000-000000000000" Description="" SiteCollectionTermGroup="true" UpdateBehavior="Overwrite">
          <pnp:TermSets>
            <pnp:TermSet  Name="Nav{siteid}" ID="00000000-0000-0000-0000-000000000000" Description="">
```
This works well on first run but when I run it again I get the error:
"A term set already exists with the name specified."

Expected behaviour for me is that the TermSet is overwritten.

**Comment by IshitaSingh01** [comment]
HI All, 

I am getting the same problem as above, "{"A term set already exists with the name specified."}", while it is expected that the changes in the TermSet is overwritten. This was not the case with SP 2013 provisioning. Recently our farm has been upgraded to 2016 and ApplyProvisioningTemplate has started throwing this issue.

My code is as below : 

`<pnp:TermGroups>
        <pnp:TermGroup Name="{sitecollectiontermgroupname}" Description="" SiteCollectionTermGroup="true">
          <pnp:TermSets>
            <pnp:TermSet Name="{parameter:lcSiteTermsetName}" Description="">
              <pnp:CustomProperties>
                <pnp:Property Key="_Sys_Nav_IsAvailableForTagging" Value="True" />
                <pnp:Property Key="_Sys_Nav_IsNavigationTermSet" Value="True" />
              </pnp:CustomProperties>
</pnp:TermSet>
  </pnp:TermSets>
          <pnp:Contributors />
          <pnp:Managers />
        </pnp:TermGroup>`

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
