### ISSUE TITLE
FeatureRequest: Add Option to set DateFields FriendlyDisplayFormat Attribute via XML Schema

### ISSUE THREAD

**Issue by chrriedel** [SharePoint/PnP-Provisioning-Schema#342]
For a SharePoint Field of Type Date there is a Property FriendlyDisplayFormat which is normaly set to Userfriendly so that a Date is shown as "Friday 21. September 2018". In SharePoint UI there is the posibility to set this to Standard what shows the date in Format DD/MM/YYYY hh:mm. 

This can't be done via a PnP Template.

To do this at some Point at the ContentType creation or at the ListInstance an option to set FriendlyDisplayFormat=disabled or related must be added to the schema. 

In CSOM for the FriendlyDisplayFormat there is an ENUM where 1 = disabled 2 = relative 

I would appricate to have this in one of the next schema versions.

Greats Chris

**Comment by phawrylak** [comment]
Fields in PnP Provisioning Schema are flexible and not limited to specific set of attributes. When you look in provisioning engine, you will see that Field elements are used directly in `FieldCollection.AddFieldAsXml()` method. This means that you can just add `FriendlyDisplayFormat="Relative"` in Date Field XML and it should work.

**Comment by jansenbe** [comment]
Answered by @phawrylak
