### ISSUE TITLE
Question: Having only one provisioning template per communication site to create ?

### ISSUE THREAD

**Issue by guillaume-kizilian** [SharePoint/PnP-Provisioning-Schema#350]
Hi.

[X] Question

**Expecting**
Do all the provisioning steps in one template for creating one communication site ?

**Actual**
We have to create multiple templates to separate some steps.

**Exemples**
- Creating a new content type (inherit Modern Page) and setting it as default content type for a library (SitePages) then provisioning pages.
- Install a webpart, then add it on a page.

Are you aware of this type of behavior ?
Is it depending on our implementation  ? 

Is there something to list all thoses cases?

Thanks you.

**Comment by PaoloPia** [comment]
Please, have a look to the SP Starter Kit (https://github.com/SharePoint/sp-starter-kit/blob/master/provisioning/starterkit.xml) sample template to see how to handle this kind of needs. In case of any further need, please re-open this issue. Thanks.
