### ISSUE TITLE
Question: Is there a way to associate a flow to a list provisioned with the template?

### ISSUE THREAD

**Issue by anisiaalexandra** [SharePoint/PnP-Provisioning-Schema#351]
Hi,

I was wondering if there is a way to associate directly a flow to a list provisioned with the template and if so where and how to do the configurations?

Thank you in advance.

Br,
Anisia Pop

**Comment by PaoloPia** [comment]
Hi, 
Unfortunately, due to a lack of APIs, we cannot do that yet.
