### ISSUE TITLE
Add the new client side web parts in enum of 1st party web parts

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Provisioning-Schema#354]
https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-web-part-updates-Yammer-Conversations-My-Documents/ba-p/303719

**Comment by jansenbe** [comment]
Changes in PnP-Sites-Core are done, we can get the list of webparts from there

**Comment by PaoloPia** [comment]
This is in sync at schema level.
