### ISSUE TITLE
Support disabling oob footer for modern pages

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Provisioning-Schema#360]
Support web.FooterEnabled and see what else properties from the oob footer can be set? Whatever is available for remote APIs, should be supported in the Web object.

**Comment by PaoloPia** [comment]
I added support for a structure like the following one:

      <pnp:Footer Enabled="true" Logo="logo.png" NameVisibility="true">
        <pnp:FooterLinks>
          <pnp:FooterLink DisplayName="Link 01" Url="www.link01.com" />
          <pnp:FooterLink DisplayName="Link 02" Url="www.link02.com" />
          <pnp:FooterLink DisplayName="Link 03" Url="www.link03.com" />
          <pnp:FooterLink DisplayName="Link Master 04">
            <pnp:FooterLink DisplayName="Child Link 04-01" Url="www.link04-01.com" />
            <pnp:FooterLink DisplayName="Child Link 04-02" Url="www.link04-02.com" />
            <pnp:FooterLink DisplayName="Child Link 04-03" Url="www.link04-03.com" />
          </pnp:FooterLink>
          <pnp:FooterLink DisplayName="Link Master 05">
            <pnp:FooterLink DisplayName="Child Link 05-01" Url="www.link05-01.com" />
            <pnp:FooterLink DisplayName="Child Link 05-02" Url="www.link05-02.com" />
          </pnp:FooterLink>
          <pnp:FooterLink DisplayName="Link Master 06">
            <pnp:FooterLink DisplayName="Child Link 06-01">
              <pnp:FooterLink DisplayName="Child Link 06-01-01" Url="www.link06-01-01.com" />
              <pnp:FooterLink DisplayName="Child Link 06-01-02" Url="www.link06-01-02.com" />
            </pnp:FooterLink>
            <pnp:FooterLink DisplayName="Child Link 06-02" Url="www.link06-02.com" />
          </pnp:FooterLink>
        </pnp:FooterLinks>
      </pnp:Footer>

**Comment by ruslanurban** [comment]
Links often have icons (e.g. RSS, Twitter), class and target properties. Would it make sense to use HTML snippets in the footer instead of just the links? Seems to be limiting what information can go into the footer....
