### ISSUE TITLE
Applying provisioning template "Access Denied" if you login with -SPOManagementShell switch

### ISSUE THREAD

**Issue by marqueezi** [SharePoint/PnP-Provisioning-Schema#362]
If you use Connect-PnPOnline with SPOManagementShell -switch and then try to apply PnP Provisioning template, you'll get Access Denied error when provisioning lists. If you connect with "normally" by using username and password, provisoining works normally. However, we were able to create provisioning template from a site by using SPOManagementShell-login.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
