### ISSUE TITLE
Can't provision modern team subsite using <pnp:Sequence>

### ISSUE THREAD

**Issue by LarterStyles** [SharePoint/PnP-Provisioning-Schema#363]
The following very simple provisioning template successfully creates a modern team site collection, but fails while attempting to create the **modern team sub-site** with an _"Object reference not set to an instance of an object"_ exception:

```
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema https://raw.githubusercontent.com/OfficeDev/PnP-Provisioning-Schema/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2018-07.xsd">
  <pnp:Preferences Author="Nick Larter" Version="1.0" />
  <pnp:Sequence ID="Test">
    <pnp:SiteCollections>
      <pnp:SiteCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:type="pnp:TeamSite"
                          Title="Team site collection"
                          DisplayName="Team site collection"
                          Description=""
                          Alias="sitecollection"
                          IsPublic="false"
                          IsHubSite="false">
        <pnp:Sites>
          <pnp:Site xsi:type="pnp:TeamSubSiteNoGroup"
                    Title="Team sub-site"
                    Description=""
                    Url="subsite"
                    QuickLaunchEnabled="true"
                    UseSamePermissionsAsParentSite="false"
                    TimeZoneId="73"
                    Language="3081">
          </pnp:Site>
        </pnp:Sites>
      </pnp:SiteCollection>
    </pnp:SiteCollections>
  </pnp:Sequence>
</pnp:Provisioning>
```

```
Connect-PnPOnline -Url "https://{tenant}-admin.sharepoint.com"
Apply-PnPTenantTemplate -Path "$PSScriptRoot\Test.xml"
```

**Get-PnPException** returns the following:

![pnpexception](https://user-images.githubusercontent.com/2833830/50946033-834c1580-14d2-11e9-9748-124fd0ace47b.PNG)

The error originates in [ObjectHierarchySequenceSites.CreateSubSites()](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs), and it appears to be due to a null **TokenParser** object.

I can confirm that my PnP PowerShell cmdlets are up to date:

![version](https://user-images.githubusercontent.com/2833830/50946339-aa571700-14d3-11e9-91aa-45be1427d33d.PNG)

I can also confirm that the error persists whether the O365 tenant is configured for either targeted or standard release.

Interestingly, if I create the modern team subsite manually (i.e. via the browser) and re-run this script, it still fails with the same error (i.e. the exception is thrown even when the provisioning template is applied to an existing site hierarchy).

I appreciate your help!

Nick

**Comment by LarterStyles** [comment]
Hi all, hoping someone can let me know if they're able to repro this please? It's proving difficult to live with at the moment. Thanks!

**Comment by val0o** [comment]
Hi @LarterStyles 
I got same issue as yours and not able to figure out if I'm doing something wrong or if it's an actual bug...
@PaoloPia any help please?

**Comment by LarterStyles** [comment]
Still no fix as far as I’m aware. As a workaround, we’re creating all our sub-sites with custom PowerShell, then applying templates to them via Apply-PnPProvisioningTemplate.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
