### ISSUE TITLE
PnP Site Proviosning Exclude Specific Site Fields 

### ISSUE THREAD

**Issue by manik-bansal** [SharePoint/PnP-Provisioning-Schema#364]
Hi,

While creating a site proviosning template, we are not able to exclude specific site columns. Is there any command available to exclude them the same way we can exclude for content types.

**Comment by PaoloPia** [comment]
Hi,
Unfortunately, as far as I know, we don't have such a capability. You can always create a custom extension to do that, if needed. Thanks.
