### ISSUE TITLE
Added `UpdateChildren` property to FieldRef

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Provisioning-Schema#373]
Added `UpdateChildren` property to FieldRef. This allows to update/not update inheriting content types as in the [documentation](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee544078(v%3Doffice.15)).

See https://github.com/SharePoint/PnP-Sites-Core/pull/2049 for an implementation done by @maxali.

**Comment by PaoloPia** [comment]
I've added to schema v. 201903 the UpdateChildren attribute to FieldRef for ContentTypes

**Comment by SteveClements** [comment]
@jansenbe @PaoloPia 
This doesn't appear to be working as expected.

**Template**:

```
 <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema">
       <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.9.1905.2, Culture=neutral,PublicKeyToken=5e633289e95c321a" />
      <pnp:Templates>

```
.....

`

>         <pnp:ContentType ID="0x0101" Name="Document">
>           <pnp:FieldRefs>
>             <pnp:FieldRef ID="{48D055D6-6502-4B4E-9C9F-9F4A1AF18143}" Name="Owner" UpdateChildren="false" />
>           </pnp:FieldRefs>
>         </pnp:ContentType>


`

**Version**:
![image](https://user-images.githubusercontent.com/5147797/57985705-34a81c80-7a6c-11e9-9fdd-ffa9b8e0693e.png)

```
Apply-PnPProvisioningTemplate : The content type "Office Data Connection File" at "/sites/test1" is read only.
The content type "Universal Data Connection File" at "/sites/test1" is read only.
The content type "Design File" at "/sites/test1" is sealed.
The content type "Unknown Document Type" at "/sites/test1" is read only.
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:5 char:1
```
The error is being thrown the same as it did in previous versions, because it's trying to update child content types of Document which are sealed.

Something I'm missing?

**Comment by SteveClements** [comment]
I've created a new Issue in SP Core for this.

https://github.com/SharePoint/PnP-Sites-Core/issues/2251
