### ISSUE TITLE
Error while provisioning content type and define a list with said item

### ISSUE THREAD

**Issue by SharePointPnP** [SharePoint/PnP-Provisioning-Schema#376]
I have declared a XML-provisioning schema that I try to provision out content types with site columns attached to it. Content types are defined in the content type hub and so are the site columns (which are attached to the content types). 

I have looked at examples etc, but no mater what I try, it doesnt work. See attached file for the code. 

  The error message I get while I tyr to upload it via PowerShell is.
`
```
Apply-PnPProvisioningTemplate : The provided template is not valid!
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path C:\xml\xmlSchema.xml
```
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate`

[example.zip](https://github.com/SharePoint/PnP-Provisioning-Schema/files/2899524/example.zip)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, we don't have support for the Content Type Hub at the engine level.
