### ISSUE TITLE
URL callout 'extension'

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#377]
Add an element to do a callout after provisioning of a template. Allow people to specify the url to the endpoint (can be anything, not necessarily only flow) and allow them to send an arbitraty list of parameters.

**Comment by PaoloPia** [comment]
What about something like that:

      <pnp:ProvisioningTemplateWebhooks>
        <pnp:ProvisioningTemplateWebhook Url="https://mywebhook.azurefunctions.net/function01?par1={WebhookParam:Param01}&amp;site={sitecollection}&amp;par2={WebhookParam:Param02}&amp;par3={WebhookParam:Param03}"
                                         Method="GET" Kind="ProvisioningStarted">
          <pnp:Parameter Key="Param01" Value="Value01"/>
          <pnp:Parameter Key="Param02" Value="Value02"/>
          <pnp:Parameter Key="Param03" Value="Value03"/>
        </pnp:ProvisioningTemplateWebhook>
        <pnp:ProvisioningTemplateWebhook Url="https://mywebhook.azurefunctions.net/function01"
                                         Method="POST" Kind="ProvisioningCompleted" BodyFormat="Json">
          <pnp:Parameter Key="Param01" Value="Value01"/>
          <pnp:Parameter Key="Site" Value="{sitecollection}"/>
        </pnp:ProvisioningTemplateWebhook>
      </pnp:ProvisioningTemplateWebhooks>

**Comment by PaoloPia** [comment]
Added to schema 201903.
