### ISSUE TITLE
Update the documentation for token: AppPackageId

### ISSUE THREAD

**Issue by JonasBjerke89** [SharePoint/PnP-Provisioning-Schema#384]
The latest sample of the PnP Provisioning Template (https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2018-07-FullSample-01.xml) refers to the token "AppPackageId" for dynamically replacing the installed app guid in a template.

But the samples and documentation states, that we should use the name of the package with the extension (.sppkg) like this:
`<pnp:App AppId="{AppPackageId:spfx-discuss-now.sppkg}" Action="Update" SyncMode="Asynchronously" />`

That is **not** the case as the extension must be removed in the template. If not, the engine cannot find the App Package. See the changed xml element: 
`<pnp:App AppId="{AppPackageId:spfx-discuss-now}" Action="Update" SyncMode="Asynchronously" />`

Is that expected behaviour? If so, we should properly update the samples and the documentation too.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Yes, the value for the token has to be the "Package Name" and not the package file name. We will fix it in docs and samples.

**Comment by JonasBjerke89** [comment]
I have made a PR with the changes (https://github.com/SharePoint/PnP-Provisioning-Schema/pull/428)
