### ISSUE TITLE
Clear Owners, Members, Visitors

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Provisioning-Schema#386]
Make it possible to clear users in Owners, Members, and Visitors groups

**Comment by PaoloPia** [comment]
We now have, in schema v. 201903, a @ClearExistingItems attribute on the groups to clear existing items. Here is a sample excerpt:

      <pnp:Security BreakRoleInheritance="true"
                    CopyRoleAssignments="false"
                    ClearSubscopes="true"
                    AssociatedGroups="Test Value"
                    AssociatedMemberGroup="{parameter:AssociatedMemberGroup}"
                    AssociatedOwnerGroup="{parameter:AssociatedOwnerGroup}"
                    AssociatedVisitorGroup="{parameter:AssociatedVisitorGroup}"
                    RemoveExistingUniqueRoleAssignments="true"
                    ResetRoleInheritance="true" >
        <pnp:AdditionalAdministrators ClearExistingItems="false">
          <pnp:User Name="user@contoso.com"/>
          <pnp:User Name="U_SHAREPOINT_ADMINS"/>
        </pnp:AdditionalAdministrators>
        <pnp:AdditionalOwners ClearExistingItems="true">
          <pnp:User Name="user@contoso.com"/>
          <pnp:User Name="U_SHAREPOINT_ADMINS"/>
        </pnp:AdditionalOwners>
        <pnp:AdditionalMembers>
          <pnp:User Name="user@contoso.com"/>
          <pnp:User Name="U_SHAREPOINT_ADMINS"/>
        </pnp:AdditionalMembers>
        <pnp:AdditionalVisitors>
          <pnp:User Name="user@contoso.com"/>
          <pnp:User Name="U_SHAREPOINT_ADMINS"/>
        </pnp:AdditionalVisitors>
        <pnp:SiteGroups>
          <pnp:SiteGroup
              Title="Power Users"
              Description="Group of Power Users"
              Owner="admin@contoso.com">
            <pnp:Members ClearExistingItems="true">
              <pnp:User Name="user1@contoso.com" />
              <pnp:User Name="user2@contoso.com" />
              <pnp:User Name="user3@contoso.com" />
            </pnp:Members>
          </pnp:SiteGroup>
        </pnp:SiteGroups>
        <pnp:Permissions>
          <pnp:RoleDefinitions>
            <pnp:RoleDefinition Name="Manage List Items" Description="Allows a user to manage list items">
              <pnp:Permissions>
                <pnp:Permission>ViewListItems</pnp:Permission>
                <pnp:Permission>AddListItems</pnp:Permission>
                <pnp:Permission>EditListItems</pnp:Permission>
                <pnp:Permission>DeleteListItems</pnp:Permission>
              </pnp:Permissions>
            </pnp:RoleDefinition>
          </pnp:RoleDefinitions>
          <pnp:RoleAssignments>
            <pnp:RoleAssignment Principal="Power Users" RoleDefinition="Manage List Items"/>
            <pnp:RoleAssignment Principal="user1@contoso.com" RoleDefinition="Manage List Items"/>
            <pnp:RoleAssignment Principal="user2@contoso.com" RoleDefinition="Full Control"/>
            <pnp:RoleAssignment Principal="user3@contoso.com" RoleDefinition="Full Control" Remove="true"/>
          </pnp:RoleAssignments>
        </pnp:Permissions>
      </pnp:Security>

@LauraKokkarinen

**Comment by rohit404404** [comment]
@PaoloPia is there a way to define this while provisioning template (xml) from existing site? may be through handler

we are currently generating xml and then have to manually remove group members and group owners from xml file :(
