### ISSUE TITLE
Changelog is not up to date?

### ISSUE THREAD

**Issue by shurick81** [SharePoint/PnP-Provisioning-Schema#397]
It is expected that https://github.com/SharePoint/PnP-Provisioning-Schema/blob/e4c0b2eb853a9a3ccb7ea985830c162b678c8eec/CHANGELOG.md should include the list of schema changes in 201903 but it does not seem including them

**Comment by pcardosolei** [comment]
Any news on this matter?

**Comment by PaoloPia** [comment]
Good catch! I will update it ... thanks.
