### ISSUE TITLE
[Question] What is the template elements sequence to apply?

### ISSUE THREAD

**Issue by PedroMordeP** [SharePoint/PnP-Provisioning-Schema#399]
Anyone knows where I can find some information of the sequence used by PnP to apply each root elements?

For example the <pnp:WebSettings />is one of the first elements on the xml template but is the last to be applied to the site.

The root element of the SharePoint Provisioning Template.
[https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2019-03.md#provisioningtemplate](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2019-03.md#provisioningtemplate)

Thank you

**Comment by PaoloPia** [comment]
You can have a look at the engine itself: https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs#L77
