### ISSUE TITLE
Introduce Update/modification ID for certain team template artifacts

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Provisioning-Schema#401]
To update a team we need to be able to reference the specific artifact. Currently this is done by name, which can fail in specific scenarios (updating the display name for instance). Introduce a specific ID atrribute which should -not- be called 'ID' to allow to point to a specific artifact in a team to update that artifact during re-apply of template.

Introduce tokens to be able to resolve IDs at application time based on name.

**Comment by PaoloPia** [comment]
I created an attribute called InternalId for Teams, Channels, Tabs. It will be available in schema 201909.
