### ISSUE TITLE
Missing PnP:DataRow Support for List Attachments

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Provisioning-Schema#409]
As for the Content Extraction and Provisioing it would be good to have the possibility to specify File attached to ListItems.

Based on AttachmentCreationInformation we would need a FileName and TypeId to fully specify a attached File. I would suggest to have a it like:
<pnp:DataRows>
<pnp:DataRow rowId=1>
</pnp:DataRow>
<pnp:DataRowAttachments>
<pnp:DataRowAttachment rowId=1 FileName="myFile1.txt" TypeId="">
<pnp:DataRowAttachment rowId=1 FileName="myFile2.txt" TypeId="">
</pnp:DataRowAttachments>
</pnp:DataRows>

In that way we have no need to change DataRow from a Dictionary to a more complex object and can still have attachments assigned to ListItems - would mean:
<pnp:DataRowAttachment rowId="xsy:int" FileName="xsd:string" TypeId="xsd:string" >

**Comment by PaoloPia** [comment]
Hi @czullu,
Thanks for the input. I've just added the Attachments collection to the DataRow. You will find it in schema 201909.
