### ISSUE TITLE
Missing Properties on pnp:Folder in Order to support DocumentSet

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Provisioning-Schema#412]
While working on the ObjectListInstanceDataRows Extract i run into the issue, that i can not handle DocumentSet since i have no way to store that Data into the current Schema.

Therefore i would suggest to add this to schema (same as on pnp:File)
<pnp:FolderProperties>
   <pnp:Property />
</pnp:FolderProperties>

In addition to Properties we would need the ability to specify the ContentTypeId of the Folder in order to  create a DocumentSet with the correct ContenType in Case it's not 0x0120

**Comment by PaoloPia** [comment]
Hi @czullu,
Thanks for your input. I've just added this capability to schema 201909.
