### ISSUE TITLE
Adding SearchScope as a WebSetting property

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Provisioning-Schema#415]
I propose to add SearchScope as a setting to the WebSetting property.

https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2019-03.md#websettings

`<pnp:WebSettings  SearchScope="xsd:string" />`

Ref announcement at: https://developer.microsoft.com/en-us/project/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-march-2019/

**Comment by PaoloPia** [comment]
Done! It will show up in schema 201909.
