### ISSUE TITLE
Question: List Fields - what is the best way to handle ShowInNewForm and ShowInEditForm

### ISSUE THREAD

**Issue by nateforsyth** [SharePoint/PnP-Provisioning-Schema#416]
I am unsure if I am failing here due to a mistake or flat out doing it wrong.

At what point is the best way to handle ShowInNewForm and ShowInEditForm settings on a ListInstance using PNP provisioning templates?

I note that FieldRefs is used to reference Content Type Fields from a Content Type attached to a List.

I've been reading the schema but I cannot find any clarity upon the mentioned attributes on a Field or FieldRef XML element.

**I have tried the following:**

### pnp:ListInstance > pnp:FieldRefs > pnp:FieldRef

I've then added attributes for ShowInNewForm and ShowInEditForm and set them to false.

```xml
<pnp:FieldRef 
    ID="aa219bdb-b4a3-43bd-a583-fcd9c4ad65b6" 
    Name="BCSActivity" 
    DisplayName="BCS Activity"  
    ShowInNewForm="FALSE" 
    ShowInEditForm="FALSE"
/>
```

**As well as the following:**

### pnp:ListInstance > pnp:Fields > pnp:Field

I've then added an entire **Field** element for my Site Column following the pattern that out of the box hidden fields follow, with attributes for ShowInNewForm and ShowInEditForm and set them to false - as follows.

```xml
<Field Type="TaxonomyFieldType"
    Name="BCSActivity"
    DisplayName="BCS Activity"
    ID="{aa219bdb-b4a3-43bd-a583-fcd9c4ad65b6}"
    Group="Solar Rec Mgmt Columns (Published)"
    Required="TRUE"
    ShowField="Term1033" 
    SourceID="{961f0eba-2cdc-4e3b-8248-cb5511ba686e}" 
    StaticName="BCSActivity" 
    List="{{listid:TaxonomyHiddenList}}" 
    WebId="{siteid}" 
    Description="ADMIN: Please select a default BCS Activity and set to column hidden" 
    AllowDeletion="TRUE"  
    ShowInNewForm="FALSE" 
    ShowInEditForm="FALSE">
</Field>
```

But neither are working for me.

I have to be honest - I am scraping the bottom of my proverbial barrel trying to work this one out (read: barrel = brain).

Any assistance is appreciated.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your request. At the moment, we don't have support for ShowInNewForm and ShowInEditForm settings at schema level for fields referenced in a list instance. As such, there is no way to do what you're looking for. We have support for those properties in Site Columns definition, which can be then referenced in a Content Type used in a List.
