### ISSUE TITLE
Cannot set properties of complex objects like People web part.

### ISSUE THREAD

**Issue by vilmarci** [SharePoint/PnP-Provisioning-Schema#420]
The people web part properties contain arrays that cannot be set in the template (or at least I didn't find any documentation about it and none of my attempts were successful). Looks like this:

`{"id": "7f718435-ee4d-431c-bdbf-9c4ff326f46e", "instanceId": "2c0ce1ac-0a27-42be-a612-1ddd93cb4f39", "title": "People", "description": "Display selected people and their profiles", "dataVersion": "1.3", "properties": {"layout":1,"persons":[{"id":"someone@mytenant.com","upn":"","role":"consultant","department":"IT support,"phone":"","sip":""}]}, "serverProcessedContent": {"htmlStrings":{},"searchablePlainTexts":{"title":"","persons[0].name":"Someone","persons[0].email":"someone@mytenant.com"},"imageSources":{},"links":{}}, "dynamicDataPaths": {}, "dynamicDataValues": {}}`

I can set the main properties like this:

```
<pnp:CanvasControlProperties>
  <pnp:CanvasControlProperty Key="id" Value="7f718435-ee4d-431c-bdbf-9c4ff326f46e" />
  <pnp:CanvasControlProperty Key="instanceId" Value="2c0ce1ac-0a27-42be-a612-1ddd93cb4f39" />
  <pnp:CanvasControlProperty Key="title" Value="People" />
  <pnp:CanvasControlProperty Key="dataVersion" Value="1.3" />
</pnp:CanvasControlProperties>
```

But not the persons array.

**Comment by PaoloPia** [comment]
Hi,
I would suggest you to use the following PowerShell cmdlet to export a pre-configured page (using the browser):

Get-PnPProvisioningTemplate -Out C:\temp\template.xml -PersistBrandingFiles -IncludeAllClientSidePages
