### ISSUE TITLE
Vertical section support for modern pages needed in the schema

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Provisioning-Schema#422]
We checked in the bits that enable the modern page API to read, create and update pages having a vertical section. A vertical section is essentially a regular section but with one extra column that spans the complete page height. I've introduced 5 new section templates:
OneColumnVerticalSection
TwoColumnVerticalSection
ThreeColumnVerticalSection
TwoColumnLeftVerticalSection
TwoColumnRightVerticalSection

For the engine we'll need to extend the schema to support the new section types + since a vertical section column can have it's own emphasis we need a new VerticalSectionEmphasis attribute on the Section element.

**Comment by PaoloPia** [comment]
Is this (https://github.com/SharePoint/PnP-Provisioning-Schema/blob/experimental/Samples/ProvisioningSchema-2019-09-FullSample-01.xml#L955) what you are looking for?

**Comment by PaoloPia** [comment]
Done! It will show up in schema 201909.
