### ISSUE TITLE
Add support for Group lifecycle policies, classification list and blocked words etc.

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/PnP-Provisioning-Schema#424]
Would love if we can add additional tenant settings as below in upcoming schemas, happy to contribute PRs:

1) Add support for Group lifecycle policies - ability set group expiration policy / expire groups after specified number of days (probably default to 180 days)  - [groupLifecyclePolicy resource type
](https://docs.microsoft.com/en-us/graph/api/resources/grouplifecyclepolicy?view=graph-rest-1.0).

Would be great if we can setup expiry for groups(all, selected, none) and specify expiration for specific groups

2) Set the classification list for groups, add blocked words, modify usage guidelines url as in below image. Would like if we can implement [this](https://docs.microsoft.com/en-us/graph/api/groupsetting-update?view=graph-rest-1.0&tabs=http) entirely:

![Capture2](https://user-images.githubusercontent.com/8832018/64010464-75b5cf80-cb37-11e9-812f-8217b82045bf.PNG)

**Comment by PaoloPia** [comment]
Hi @gautamdsheth,
I just added support for Group Lifecycle Policies at schema level in schema 201909. About the AAD settings, I will keep it on hold and I will let you know what we can do. I'm not sure we can include it in the upcoming schema 201909, but in the worst case I will do my best to have it in the next one.

**Comment by PaoloPia** [comment]
I just included a dictionary to collect the directory settings, too. It will show up in 201909 schema.
