### ISSUE TITLE
Add support to teamify site and hideTeamify prompt

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/PnP-Provisioning-Schema#425]
For modern team site backed by O365 group, add support for `TeamfySite` and `HideTeamify` prompt attributes, both boolean and default set to false.

Something like this:

```xml

<pnp:TeamSite
      Alias="pnp:ReplaceableString"
      DisplayName="pnp:ReplaceableString"
      IsPublic="xsd:boolean"
      TeamifySite="xsd:boolean"
      HideTeamifyPrompt="xsd:boolean"
      Classification="pnp:ReplaceableString">
</pnp:TeamSite>
```

We have already added the necessary methods in the SiteCollection class and the client context extension, so wont be much work to implement it :)

**Comment by PaoloPia** [comment]
Thanks for your contribution. It's done and it will show up in schema 201909.
