### ISSUE TITLE
Add support to invoke custom site design

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/PnP-Provisioning-Schema#431]
Currently, we have support for adding custom site scripts and site design.
Would be great if we can also apply/invoke these custom site design as part of the provisioning.

We can reuse the SiteDesign parameter for all modern sites and if we find a valid site design, we can invoke it.

**Comment by erkanch** [comment]
CommunicationSite has support for this but the team sites don't have a SiteDesgin attribute. I agree it'd be great to add the team site support for this.

**Comment by PaoloPia** [comment]
Hi, 
Thanks for your feedback. I just added the SiteDesign attribute to the modern Team site element. It will become available in schema 202002.
