### ISSUE TITLE
Add support for org-level external sharing settings in SharePoint and Onedrive

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/PnP-Provisioning-Schema#432]
Add support to set/modify the external sharing settings of an O365 tenant.

We can allow settings as mentioned here - https://social.technet.microsoft.com/wiki/contents/articles/39365.sharepoint-online-sharing-settings-with-csom.aspx

We can set Sharing capabilities, Anonymous link access, default sharing link type etc.

Would be also great if we can include these at individual site collection level.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We're working on making this settings available in schema 202002.

**Comment by lennertcc** [comment]
> Would be also great if we can include these at individual site collection level.

Could you please also reply to this?
