### ISSUE TITLE
pnp:App for existing app (An instance of this App already exists at the specified location)

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP-Provisioning-Schema#433]
Can we put additional option for pnp:App if `An instance of this App already exists at the
specified location` . Maybe to specify action to ignore or update if it's already installed, something like `Action="install/update"`

Also I noticed sometimes it takes forever for an app to be installed then throw `App Install timeout hit, could not determine installed state`, is it possible to still continue the script if an error like this has occurred instead of stopping?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We already have the Action attribute for the pnp:App element: 

https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2019-09.xsd#L6365

Thanks,
Paolo

**Comment by manoj75** [comment]
The template fails if the app exists in the site already. There needs to be an InstallOrUpdate option or and OverWrite option with Action="Install"
