### ISSUE TITLE
Apply-PnPProvisioningTemplate not working with version 2019/09

### ISSUE THREAD

**Issue by kadu-jr** [SharePoint/PnP-Provisioning-Schema#438]
For some reason I can't seem to work with the new approved version, 2019/09. Whenever I change the "xmlns:pnp" property to the new version URI as mentioned in the home page to reflect the new schema, if I try to run the "Apply-PnPProvisioningTemplate" command it doesn't work. The yellow progress message "Applying template to..." shows up only to disappear less than a second later. The same thing happens if I set the "xmlns:pnp" property to a non-existent schema.

I updated my PnP-PowerShell to the latest version(3.13.1909.0). Are we still not able to use the new approved schema?

Regards,

**Comment by pconnell99** [comment]
Same here - flashes up a progress bar in PS IDE, then end with no error - template not applied.

**Comment by kadu-jr** [comment]
I was able to get it to work updating to the [October release](https://github.com/SharePoint/PnP-PowerShell/releases/tag/3.14.1910.1). I would suggest you to do the same.
