### ISSUE TITLE
What are the defaults for optional attributes?

### ISSUE THREAD

**Issue by pconnell99** [SharePoint/PnP-Provisioning-Schema#443]
When an attribute is listed as 'optional', it would be useful for users to know what the default is if the attribute is NOT provided.

Example - **WebSettings-NoCrawl: Boolean - optional** - but if I do not provide it, what is is set to by default by the engine?  Documentation is missing this information, so I would have to set every optional attribute to 'something' to guarantee a setting rather than relying on the defaults if they are okay for my purposes.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We will do our best to improve the generation of documentation. At the same time, we're working on a PR to make it easier the handling of default values for optional attributes.
