### ISSUE TITLE
Missing Property in CanvasControl to specify if in VerticalSection

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Provisioning-Schema#447]
Using Dev Branch with Commits up to 20.09 and Schema 201909.
I did want to fix CanvasControl positioning to be in vertical section but did not find any property to tell that the CanvasControl that it is in the Vertical Section. 

@PaoloPia @jansenbe  To me a simple boolean on CanvasControl would be enought to specify that the canvascontrol belongs to the vertical section.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Actually, at schema level we can configure one single section to be the vertical section. As such, all the controls in that section will be in the vertical section of the page. The attribute is pnp:Section/@Type.
