### ISSUE TITLE
Read-PnPTenantTemplate not working with the latest schema

### ISSUE THREAD

**Issue by erkanch** [SharePoint/PnP-Provisioning-Schema#448]
Using <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema" results in the following error. Changing it to /03/ fixes it. What do I need to do to use the latest schmea? I need the latest schema to use "<pnp:SiteSettings AllowDesigner="false" />"

Read-PnPTenantTemplate : There is an error in XML document (0, 0).
At line:1 char:1
+ Read-PnPTenantTemplate -Path C:\pnpsite ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-PnPTenantTemplate], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant
   .ReadTenantTemplate

**Comment by pvranich** [comment]
I get the same error using the new schema and version 3.13.1909.0 of the SharePointPnpPowerShellOnline cmdlets

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This problem should be fixed. Please, try again with the latest schema and the latest PowerShell command lets. In case of any further issue, open a new issue item.
