### ISSUE TITLE
Apply-PnPTenantTemplate not working with 2019-09 schema

### ISSUE THREAD

**Issue by pvranich** [SharePoint/PnP-Provisioning-Schema#451]
Hi,

I have implemented a new template using the new, **http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema**.

When running the **Apply-PnPTenantTemplate** cmdlet from SharePointPnPPowerShellOnline version 3.13.1909.0 I get the following error:

```
Apply-PnPTenantTemplate : There is an error in XML document (0, 0).
At C:\repos\dark-stars\qt-provisioning\provisioning-scripts\Apply-Template.ps1:8 char:1
Apply-PnPTenantTemplate -Path .\templates\provisioning-template-works ...
    + CategoryInfo          : WriteError: (:) [Apply-PnPTenantTemplate], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate
```

I imagine this is related to the same issue here #448 

Any ideas?

Thanks in advance
Pete

**Comment by joananms** [comment]
i have the same issue.

**Comment by ganeshlathi** [comment]
i have the same issue. Trying to create a xml file with the new vertical section

**Comment by pconnell99** [comment]
Resolution here doesn't help me - I'm applying the template to a site collection so I need to target that specifically?  This template yupe will not apply, even if the template originated from the same tenant!

**Comment by joananms** [comment]
If you want to apply a template to a site collection connect without "-admin" in url.

**Comment by pvranich** [comment]
This is now working for me with the latest powershell cmdlets.
