### ISSUE TITLE
HubSiteUrl should be fully qualified in samples

### ISSUE THREAD

**Issue by rlv-dan** [SharePoint/PnP-Provisioning-Schema#460]
The provisioning samples say to use a relative URL for HubSiteUrl:

`HubSiteUrl="/sites/hubsite"`

This would not work for me. I needed to write a fully qualified URL in my template:

`HubSiteUrl="https://contoso.sharepoint.com/sites/hubsite"`

Suggest changing templates to avoid confusion

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. You're right, and we are going to update the samples accordingly.
