### ISSUE TITLE
Apply-PnPProvisioningTemplate - Not able to add Vertical Section

### ISSUE THREAD

**Issue by atullw** [SharePoint/PnP-Provisioning-Schema#464]
Hello,

I am not able to add vertical section in ClientSidePages using Apply-PnPProvisioningTemplate. The schema version 201903 does not have type for adding vertical section and the schema version 201909 does not work.

Any ideas as to how i can add vertical section using PnPProvisioningTemplate.

Thanks in advance.

Best,
Atul.

**Comment by ganeshlathi** [comment]
i am facing the same issue.

**Comment by pconnell99** [comment]
Same here - silence is deafening.

**Comment by Mohankumar1978** [comment]
I'm too facing the similar issue, at the moment the only option is to ignore Vertical Section and go back to 201903 schema

**Comment by alooft** [comment]
Also experiencing this issue. Hoping for a quick solution.

**Comment by manishkaushal2015** [comment]
I am facing this issue too. Vertical section is not getting added on Apply-PnPProvisioningTemplate in SharePoint Online. Please update once the issue is fixed.

**Comment by PaoloPia** [comment]
Hi,
If you want to see how to use Vertical Sections, you can take inspiration from the Look Book templates, which are available here: https://github.com/SharePoint/sp-dev-provisioning-templates. For example, you can take inspiration from the following sample template: https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/thelanding/source/template.xml.
