### ISSUE TITLE
Add support for SearchBoxInNavBar in WebSetting and SiteSettings

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Provisioning-Schema#465]
Property: SearchBoxInNavBar
Values:
* Inherit = 0,
* AllPages = 1,
* ModernOnly = 2,
* Hidden = 3

Already added to SiteSettings.cs/WebSettings.cs/ObjectSiteSettings.cs/ObjectWebSettings.cs

**Comment by PaoloPia** [comment]
Hi @wobba,
Thanks for your feedback, we really value your contribution ;-). I just created the attributes in WebSettings and SiteSettings elements and they will show up in schema v.202002.
