### ISSUE TITLE
Apply-PnPProvisioningTemplate : The 'value' argument cannot be null.

### ISSUE THREAD

**Issue by atullw** [SharePoint/PnP-Provisioning-Schema#467]
Hello,

I am getting this error on provisioning template that used to work. This happens when the provisioning engine attempts to add a custom content type. 
Interestingly when running the apply pnp-provision it does actually put the content types in, (even though it errors). So if you re-run the command sufficient times, eventually the template is successfully applied.

Thanks in advance.

Best,
Atul.

**Comment by jcharikofsky** [comment]
I experienced the same issue. Upgrading to the latest SharePointPnPPowerShellOnline (3.15.1911.0) seems to have correct the issue. I'd give that a shot.

Jeff

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The issue should be now fixed. Could you please try with the latest release of the schema and of the engine? In case of any further need, please create a new issue. Thanks.
