### ISSUE TITLE
pnp:PropertyBagEntry does not allow to specify Value Type

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Provisioning-Schema#472]
As the PropertyBag Value is of type Object we could store also int values for example. Since Schema does not allow to specify for the Type, all Values are handled as string.

It would be nice, if in future we could specify the objectType in order to provision the correct type.
My personal favorite would be to make the Value a JSON if it's of a complex Type and for have it string for the simple Type (for example int).

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, the collection of property bags always returns a string type, no matter what the stored value is, so we cannot support the suggested scenario.
