### ISSUE TITLE
Canvas Section Template in ClientSidePages

### ISSUE THREAD

**Issue by atullw** [SharePoint/PnP-Provisioning-Schema#473]
Hello,

The TwoColumnRightVerticalSection canvas section by default selects one-third left column layout. It cannot be changed to one-third right column layout.

Any ideas as to how i can make the layout as one-third right.

Thanks in advance.

Best,
Atul.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The options provided by the schema (OneColumnVerticalSection, TwoColumnVerticalSection, ThreeColumnVerticalSection, TwoColumnLeftVerticalSection, TwoColumnRightVerticalSection) are those available in SharePoint Online and the rendering behavior is provided accordingly to the default behavior of SharePoint Online.
