### ISSUE TITLE
Error when applying content types in template 

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/PnP-Provisioning-Schema#474]
Apply-PnPProvisioningTemplate : Expected hex 0x in '{0}'.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path .\schemas\lists\buspecific-list.x ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

**Comment by aslanovsergey** [comment]
Verbose last lines:

powershell.exe Information: 0 : 2019-12-12 16:34:52.9613        [Fields]        [14]    [Debug] Updating field {cc2e4b47-6e93-47eb-9fde-68ac4d47848c} in site   78147ms f193ea10-80c1-44af-97d2-67c4550f2e34
powershell.exe Information: 0 : 2019-12-12 16:34:54.4920        [Fields]        [14]    [Debug] Updating field {a92c2190-c11a-4153-8a6d-844e9c8ef7d5} in site   79677ms f193ea10-80c1-44af-97d2-67c4550f2e34
powershell.exe Information: 0 : 2019-12-12 16:34:55.6690        [Fields]        [14]    [Debug] Code execution scope ended      80855ms f193ea10-80c1-44af-97d2-67c4550f2e34
powershell.exe Information: 0 : 2019-12-12 16:34:55.6700        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope started    0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:55.6700        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope ended      0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:55.6710        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope started    0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:55.6710        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope ended      0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:55.6720        [Content Types] [14]    [Debug] Code execution scope started    0ms     f193ea10-80c1-44af-97d2-67c4550f2e34
powershell.exe Information: 0 : 2019-12-12 16:34:56.9719        [Content Types] [14]    [Debug] Code execution scope ended      1300ms  f193ea10-80c1-44af-97d2-67c4550f2e34
powershell.exe Information: 0 : 2019-12-12 16:34:56.9729        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope started    0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:56.9729        [ProvisioningTemplate WebHook Call]     [14]    [Debug] Code execution scope ended      0ms     f193ea10-80c1-44af-97d2-67c4550f2e34  
powershell.exe Information: 0 : 2019-12-12 16:34:56.9739        [Provisioning]  [14]    [Debug] Code execution scope ended      83830ms f193ea10-80c1-44af-97d2-67c4550f2e34

**Comment by NerijusV** [comment]
It could be problem with content type ID that should have proper format.
Could you please share part of your template that is causing problem?

**Comment by PaoloPia** [comment]
Hi,
This repository is about the design of the XML schema for provisioning templates. If you are experiencing an issue with a specific template or functionality of the engine, you should create an issue in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core).
