### ISSUE TITLE
pnp:ListInstanceFieldRef node has required attribute "DisplayName"

### ISSUE THREAD

**Issue by NerijusV** [SharePoint/PnP-Provisioning-Schema#475]
It is noted in documentation that `FieldRef` node in `ListInstance` element has optional attribute `DisplayName`. 

![image](https://user-images.githubusercontent.com/12279131/70807706-ba076b80-1dc6-11ea-97ed-dd43fb8ae4fa.png)

But in XSD schema it is marked as required:
```
<xsd:attribute name="DisplayName" type="xsd:string" use="required">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      The display name of the field to bind, only applicable to fields that will be added to lists, optional attribute.
    </xsd:documentation>
  </xsd:annotation>
</xsd:attribute>
```

In result, schema like this (that is fully working in 2016-05 schema version) is not validated:
```xml
<pnp:ListInstance Title="MyList" TemplateType="100" ... >
         ....
          <pnp:FieldRefs>
                   <pnp:FieldRef ID="83757427-31bf-4f23-a4f3-fd8c66746f3e" />
          </pnp:FieldRefs>
</pnp:ListInstance>
```
Error is thrown:
`[Error] Template is not valid: The required attribute 'DisplayName' is missing`

I believe it should NOT be a required attribute but should inherit `DisplayName` from site column.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback and good catch! It was a bug in the schema definition. It is now fixed in the experimental branch and we're going to merge it with the next schema/engine release.

**Comment by advdberg** [comment]
@PaoloPia can it be that this one is re-introduced in the latest version 2021/03? This is particularly annoying if you're using fieldrefs to existing sitefields which already have (translated) displaynames, you then don't want to define them with a fixed language in your template.
