### ISSUE TITLE
Content Type "Update Sites and Lists" setting will not work when re-provision content type using PnP

### ISSUE THREAD

**Issue by Kenn-o** [SharePoint/PnP-Provisioning-Schema#476]
We've re-provisioned the content type to specify the document template using PnP. The Document template URL will get updated at site collection level but will not get pass down to list level.

**Site Collection Level Content type setting**
![image](https://user-images.githubusercontent.com/56100281/71223373-af8d2a80-230e-11ea-8adc-374c19727fc1.png)

**List Level Content Type setting**
![image](https://user-images.githubusercontent.com/56100281/71223394-caf83580-230e-11ea-8980-cf371139e4f4.png)

**Behaviour observed/ Findings**
If i manually update the content type settings using UI, the setting will get pass down to list level correctly. I think this setting is missing from the PnP schema/Engine???
![image](https://user-images.githubusercontent.com/56100281/71223441-f713b680-230e-11ea-831f-fd13b68e9bab.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this repository is for the provisioning schema design and not about the engine itself. Could you please provide this feedback in the correct repository (https://github.com/SharePoint/PnP-Sites-Core)? Thanks.
