### ISSUE TITLE
Disable access requests

### ISSUE THREAD

**Issue by SpliceVW** [SharePoint/PnP-Provisioning-Schema#477]
The Schema currently allows you to specify RequestAccessEmail in SiteSettings. However, once set, this property seemingly cannot be un-set. Providing the value as a null string just results in the previously set value remaining. I'm proposing that providing a null string (or other mechanism, if this doesn't fit the paradigm) should disable access requests.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this repository is for the provisioning schema design and not about the engine itself. Could you please provide this feedback in the correct repository (https://github.com/SharePoint/PnP-Sites-Core)? Thanks.

**Comment by SpliceVW** [comment]
pnp/PnP-Sites-Core#2605
