### ISSUE TITLE
Lcid 1034 not supported

### ISSUE THREAD

**Issue by joananms** [SharePoint/PnP-Provisioning-Schema#478]
The Spanish 1034 language is not supported with New-PnpTenantSite and Apply-PnPProvisioningTemplate.

Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, this repository is for the provisioning schema design and not about the engine itself. Could you please provide this feedback in the correct repository (https://github.com/SharePoint/PnP-Sites-Core or https://github.com/SharePoint/PnP-PowerShell)? Thanks.
