### ISSUE TITLE
Can I copy “App permissions” settings to other sites using PnP Provisioning?

### ISSUE THREAD

**Issue by watarufuka** [SharePoint/PnP-Provisioning-Schema#479]
I am performing a list item permission change in an app step in SharePoint Designer 2013 Workflow.

I want to copy this to other sites using PnP Provisioning.
SharePoint Designer 2013 Workflow could be copied.
However, the "App permissions" setting could not be copied.
Therefore, changing the permissions of the list item using the app step does not work.

Grant full control permission to a workflow
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo#grant-full-control-permission-to-a-workflow

Can I copy “App permissions” settings using PnP Provisioning?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. At the time of this writing, we don't have support in the provisioning engine for provisioning app permissions for the AddIn model.
