### ISSUE TITLE
Custom Actions: Rights type change from INT to STRING makes it required

### ISSUE THREAD

**Issue by olemp** [SharePoint/PnP-Provisioning-Schema#89]
Rights type change from INT to STRING makes it required.

Schema should reflect this. Quickfix was to set Rights="" for all of our CustomActions in our templates.

Commit: https://github.com/OfficeDev/PnP-Provisioning-Schema/commit/55e1e35350984fd28d202f7ed1f046d4c4878ce7

**Comment by PaoloPia** [comment]
Hi, can you expand a little bit more on this? Thanks.

**Comment by PaoloPia** [comment]
Hi, due to no response I will close this one. Please feel free to reopen and expand on this, if needed. Thanks.

**Comment by olemp** [comment]
@PaoloPia Completely forgot to respond.

There's been a schema change for the Custom Actions changing the property Rights from INT to STRING, so now a value is required. If you don't want to set any Rights for the custom actions, you need to set Rights = "" (Empty string).

**Comment by olemp** [comment]
@PaoloPia Not sure how to re-open the issue.
